export const paymentFixture = {
  key: "payment",
  case_id: "case",
  account_id: "account",
  source_document_id: "document",
  ingestion_run_id: "run",
  statement_period_id: null,
  ref_id: "TX-123",
  row_index: 0,
  amount_minor: "9007199254740993",
  currency: "EUR",
  direction: "credit",
  running_balance_minor: null,
  transaction_date: "2026-09-01",
  posted_date: null,
  value_date: null,
  effective_date: null,
  ordering_date: "2026-09-01",
  ordering_date_source: "transaction",
  description: "Payment <script>bad()</script>",
  counterparty_raw: null,
  transaction_type: null,
  bank_reference: null,
  proof_class: "p3",
  extraction_layer: 1,
  ledger_status: "admitted",
  quarantine_reason: null,
  superseded_by_id: null,
}
