import { z } from "zod"

const minor = z.union([z.string().regex(/^-?\d+$/), z.number().int().safe()])
export const transactionDetail = z.object({
  account_type: z.string().optional(),
  account_label: z.string().optional(),
  key: z.string(),
  case_id: z.string(),
  account_id: z.string(),
  source_document_id: z.string(),
  ingestion_run_id: z.string(),
  statement_period_id: z.string().nullable(),
  ref_id: z.string(),
  row_index: z.number(),
  amount_minor: minor,
  currency: z.string(),
  direction: z.string(),
  running_balance_minor: minor.nullable(),
  transaction_date: z.string().nullable(),
  posted_date: z.string().nullable(),
  value_date: z.string().nullable(),
  effective_date: z.string().nullable(),
  ordering_date: z.string(),
  ordering_date_source: z.string(),
  ordering_date_context: z.literal("statement_end_ordering_only").optional(),
  description: z.string().nullable(),
  counterparty_raw: z.string().nullable(),
  transaction_type: z.string().nullable(),
  bank_reference: z.string().nullable(),
  proof_class: z.string(),
  extraction_layer: z.number(),
  ledger_status: z.string(),
  quarantine_reason: z.string().nullable(),
  superseded_by_id: z.string().nullable(),
  locator: z.unknown().optional(),
})
