"""Shared export metadata and disclosure helpers."""

from __future__ import annotations

import re
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from html import escape
from typing import Any


class AIDisclosureLevel(str, Enum):
    NONE = "none"
    AI_GENERATED = "ai_generated"
    AI_ASSISTED_HUMAN_REVIEWED = "ai_assisted_human_reviewed"


AI_DISCLOSURE_STATEMENTS = {
    AIDisclosureLevel.AI_GENERATED: (
        "This document includes AI-generated summaries. "
        "Content has not been independently verified by a human reviewer."
    ),
    AIDisclosureLevel.AI_ASSISTED_HUMAN_REVIEWED: (
        "This document includes AI-generated content that has been reviewed by a human investigator."
    ),
}


CSV_METADATA_COLUMNS = [
    "Export ID",
    "Case ID",
    "Generated At",
    "Generated By",
    "Filters / Scope",
    "AI Disclosure",
    "Source Citations",
]


@dataclass(frozen=True)
class ExportMetadata:
    export_id: str
    case_id: str
    generated_at: datetime
    generated_by: str
    filters_description: str | None = None
    ai_disclosure: AIDisclosureLevel = AIDisclosureLevel.NONE
    scope_description: str | None = None
    source_citations: tuple[str, ...] = field(default_factory=tuple)


def generate_export_id() -> str:
    return f"exp_{uuid.uuid4().hex[:12]}"


def safe_filename(name: str, *, fallback: str = "export", max_length: int = 80) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9._-]+", "-", str(name or "").strip().lower())
    normalized = re.sub(r"-{2,}", "-", normalized).strip("-._")
    return (normalized or fallback)[:max_length]


def format_export_datetime(value: datetime) -> str:
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def ai_disclosure_statement(level: AIDisclosureLevel | str | None) -> str:
    try:
        disclosure_level = AIDisclosureLevel(level or AIDisclosureLevel.NONE)
    except ValueError:
        disclosure_level = AIDisclosureLevel.NONE
    return AI_DISCLOSURE_STATEMENTS.get(disclosure_level, "")


def render_metadata_block_html(meta: ExportMetadata) -> str:
    rows = [
        ("Export ID", meta.export_id),
        ("Case ID", meta.case_id),
        ("Generated", format_export_datetime(meta.generated_at)),
        ("Generated by", meta.generated_by),
    ]

    scope = _scope_text(meta)
    if scope:
        rows.append(("Filters / scope", scope))

    citations = _citation_summary(meta.source_citations)
    if citations:
        rows.append(("Source citations", citations))

    disclosure = ai_disclosure_statement(meta.ai_disclosure)
    if disclosure:
        rows.append(("AI / human review", disclosure))

    items = "".join(
        "<div style=\"display: grid; grid-template-columns: 116px minmax(0, 1fr); gap: 6px;\">"
        f"<dt style=\"margin: 0; color: #64748b; font-weight: 700;\">{escape(label)}</dt>"
        f"<dd style=\"margin: 0; color: #172033; overflow-wrap: anywhere;\">{escape(str(value))}</dd>"
        "</div>"
        for label, value in rows
        if str(value).strip()
    )
    return (
        '<div class="export-metadata" '
        'style="border: 1px solid #d8dee8; border-left: 4px solid #475569; '
        'background: #f8fafc; border-radius: 7px; padding: 10px 12px; '
        'margin: 12px 0 16px; font-size: 10.5px;">'
        f'<dl style="display: grid; gap: 5px; margin: 0;">{items}</dl>'
        "</div>"
    )


def render_metadata_block_docx(document: Any, meta: ExportMetadata) -> None:
    document.add_heading("Export Metadata", level=1)
    document.add_paragraph(f"Export ID: {meta.export_id}")
    document.add_paragraph(f"Case ID: {meta.case_id}")
    document.add_paragraph(f"Generated: {format_export_datetime(meta.generated_at)}")
    document.add_paragraph(f"Generated by: {meta.generated_by}")

    scope = _scope_text(meta)
    if scope:
        document.add_paragraph(f"Filters / scope: {scope}")

    citations = _clean_citations(meta.source_citations)
    if citations:
        document.add_paragraph("Source citations:")
        for citation in citations[:20]:
            document.add_paragraph(citation, style="List Bullet")
        if len(citations) > 20:
            document.add_paragraph(f"{len(citations) - 20} additional source citation(s) omitted.")

    disclosure = ai_disclosure_statement(meta.ai_disclosure)
    if disclosure:
        document.add_paragraph(f"AI / human review: {disclosure}")


def render_metadata_csv_columns() -> list[str]:
    return list(CSV_METADATA_COLUMNS)


def render_metadata_csv_values(meta: ExportMetadata) -> dict[str, str]:
    return {
        "Export ID": meta.export_id,
        "Case ID": meta.case_id,
        "Generated At": format_export_datetime(meta.generated_at),
        "Generated By": meta.generated_by,
        "Filters / Scope": _scope_text(meta),
        "AI Disclosure": ai_disclosure_statement(meta.ai_disclosure),
        "Source Citations": "; ".join(_clean_citations(meta.source_citations)),
    }


def _scope_text(meta: ExportMetadata) -> str:
    parts = [
        str(value).strip()
        for value in (meta.filters_description, meta.scope_description)
        if str(value or "").strip()
    ]
    return " | ".join(parts)


def _citation_summary(citations: tuple[str, ...]) -> str:
    cleaned = _clean_citations(citations)
    if not cleaned:
        return ""
    shown = cleaned[:5]
    suffix = f"; and {len(cleaned) - len(shown)} more" if len(cleaned) > len(shown) else ""
    return "; ".join(shown) + suffix


def _clean_citations(citations: tuple[str, ...]) -> list[str]:
    cleaned: list[str] = []
    for citation in citations or ():
        text = str(citation or "").strip()
        if text and text not in cleaned:
            cleaned.append(text)
    return cleaned
