"""
Testing checklist — single source of truth for the QA testing hub.

This is the catalogue of testable behaviours shipped in the Cellebrite work
(PRs #56–#83). It is consumed by the `testing` router which serves both the
standalone hub page and the JSON the page renders from. Keep `item id`s stable
once shipped — tester feedback is keyed on them.

Each item:
    id   : stable slug (do NOT change once testers have used it)
    t    : title (plain language)
    how  : how to test it
    tag  : 'data' (underlying data/logic already verified — mainly visual check)
           or 'ui' (built + compiles, behaviour not yet exercised — test properly)
    pr   : PR reference(s)
    ticket: sprint ticket id(s)
    note : optional caveat
"""

CHECKLIST = [
    {
        "h": "Timeline — reading messages & identities",
        "d": "The Timeline tab: rows now show more about each message and who was involved.",
        "items": [
            {"id": "tl-inline-body", "t": "Message body shows inline (no clicking)",
             "how": "Scroll the Timeline. You should read the actual message text in each row (up to ~3 lines), not just a one-line snippet. Hover for the full text.",
             "tag": "data", "pr": "#56/#76", "ticket": "S1-15"},
            {"id": "tl-to-from-numbers", "t": "To/From phone numbers appear on the row",
             "how": "On a message/call row, each party shows as \u201cName \u00b7 +number\u201d. Rows with no number just show the name.",
             "tag": "data", "pr": "#56", "ticket": "S1-13"},
            {"id": "tl-device-local-name", "t": "Recipient shows the name saved on the sending phone",
             "how": "Open a contact saved under different names on two phones. The recipient should show the name as stored on the device that sent the message (not one global name).",
             "tag": "ui", "pr": "#56", "ticket": "S1-11"},
            {"id": "tl-time-hover", "t": "Full date & time on hover",
             "how": "Hover the time on any row \u2014 a tooltip shows the full date and time.",
             "tag": "data", "pr": "#57", "ticket": "S1-06"},
            {"id": "tl-tz-offset", "t": "Timezone offset on day headers",
             "how": "Each day header shows the active timezone (e.g. \u201c\u00b7 UTC\u22124\u201d). Switch the timezone selector and confirm it updates; a day that spans a daylight-saving change shows the right offset.",
             "tag": "data", "pr": "#57", "ticket": "S1-07"},
            {"id": "tl-comms-numbers", "t": "Numbers also shown in the Comms view",
             "how": "In the Comms Center, message rows show the other party's number beside the name.",
             "tag": "ui", "pr": "#57", "ticket": "S1-12"},
        ],
    },
    {
        "h": "Timeline — media in the row (your \u201czero-click\u201d ask)",
        "d": "Images and voice notes now appear directly in the timeline row. Needs a case WITH media \u2014 the demo data has none, so test on real data.",
        "items": [
            {"id": "media-voice-inline", "t": "Voice notes play right in the row",
             "how": "Find a message with a voice note. A small audio player appears in the row \u2014 press play and it plays, no need to open the message.",
             "tag": "ui", "pr": "#76", "ticket": "S1-17",
             "note": "Demo data has no media \u2014 must be tested on a real case."},
            {"id": "media-voice-preload", "t": "Voice notes don't fetch bytes until you press play",
             "how": "On a thread full of voice notes, scrolling shouldn't fire dozens of audio downloads. Bytes load only when you press play (preload=none).",
             "tag": "ui", "pr": "#76", "ticket": "S1-17",
             "note": "Best confirmed via the Network tab on a media-heavy real case."},
            {"id": "media-image-thumbs", "t": "Image thumbnails show inline",
             "how": "A message with photos shows the thumbnails in the row.",
             "tag": "ui", "pr": "#76", "ticket": "S1-16",
             "note": "Demo data has no media \u2014 test on a real case."},
            {"id": "media-image-lightbox", "t": "Clicking a thumbnail opens the full image",
             "how": "Click an inline thumbnail \u2014 the full-size image opens in a viewer/lightbox. Closing it returns you to the same scroll position.",
             "tag": "ui", "pr": "#76", "ticket": "S1-16",
             "note": "Demo data has no media \u2014 test on a real case."},
            {"id": "media-smooth-scroll", "t": "Scrolling stays smooth with media rows",
             "how": "Scroll quickly through a media-heavy stretch \u2014 no jumpiness, blank gaps, or freezing.",
             "tag": "ui", "pr": "#75/#76", "ticket": "S1-18"},
        ],
    },
    {
        "h": "Timeline — navigation & stability",
        "d": "Sorting, jumping to a day, loading more, and not crashing on bad data.",
        "items": [
            {"id": "nav-virtualized-rows", "t": "Variable-height rows render correctly (virtualized)",
             "how": "Rows of different heights (short text vs. long body vs. media) all render fully with no overlap or clipping as you scroll \u2014 the list measures each row.",
             "tag": "ui", "pr": "#75", "ticket": "S1-14"},
            {"id": "nav-sort-toggle", "t": "Sort newest-first / oldest-first toggle",
             "how": "Use the sort toggle in the Timeline header. It flips both the day groups and the rows. Reload the page \u2014 your choice is remembered for that case.",
             "tag": "data", "pr": "#58", "ticket": "S1-05"},
            {"id": "nav-jump-to-day", "t": "Jump-to-day (scrubber) lands correctly",
             "how": "Use the date scrubber to jump to a day. The list scrolls to the right day \u2014 try it in both sort directions.",
             "tag": "ui", "pr": "#75", "ticket": "S1-14"},
            {"id": "nav-load-more-events", "t": "\u201cLoad more\u201d reaches older events",
             "how": "On a big case, scroll to the bottom \u2014 a \u201cLoad more\u201d button appears and the count climbs (\u201cShowing N of TOTAL\u201d). Narrowing the date range hides the button.",
             "tag": "data", "pr": "#59", "ticket": "S3-02"},
            {"id": "nav-load-more-comms-files", "t": "\u201cLoad more\u201d on Comms threads & Files too",
             "how": "The Comms threads list and the Files list also show \u201cLoad more\u201d past their limits.",
             "tag": "ui", "pr": "#59", "ticket": "S3-04"},
            {"id": "nav-keyset-fast", "t": "Deep paging stays fast (keyset)",
             "how": "Backend behaviour: loading far into a very large event list stays fast (no re-reading earlier pages). Confirm the timeline doesn't slow down as you load more.",
             "tag": "data", "pr": "#60", "ticket": "S3-03"},
            {"id": "nav-no-invalid-date", "t": "No \u201cInvalid Date\u201d crashes",
             "how": "Events with a missing/bad timestamp show \u201c\u2014\u201d or blank, never \u201cInvalid Date\u201d, and never crash the view.",
             "tag": "data", "pr": "#61", "ticket": "S1-02"},
            {"id": "nav-empty-error-states", "t": "Clear empty / error states",
             "how": "With no phones selected, or zero results, or a backend error, each tab shows a clear message (and a Retry where relevant) instead of a blank screen.",
             "tag": "ui", "pr": "#58", "ticket": "S1-03"},
        ],
    },
    {
        "h": "Timeline — duplicate-message clean-up (the bug you spotted)",
        "d": "The same message no longer appears three times across device sources.",
        "items": [
            {"id": "dedup-collapse", "t": "Duplicated message now shows once",
             "how": "Find the message that used to appear 3\u00d7 (e.g. across Native Messages / IMS Service / Android CallLog). It now shows a single row with a subtle \u201c\u00b7 +N sources\u201d chip \u2014 hover it to see the other sources it was extracted from.",
             "tag": "data", "pr": "#83", "ticket": "S2-31"},
            {"id": "dedup-sources-chip", "t": "The \u201c+N sources\u201d chip lists the other sources",
             "how": "Hover/inspect the \u201c+N sources\u201d chip on a collapsed message \u2014 it names the other extraction sources (apps) the duplicate came from.",
             "tag": "data", "pr": "#83", "ticket": "S2-31"},
            {"id": "dedup-no-false-merge", "t": "Genuinely different messages are NOT merged",
             "how": "Two distinct messages that happen to share a time still show separately. Only true duplicates (same time + text + sender) collapse.",
             "tag": "data", "pr": "#83", "ticket": "S2-31"},
        ],
    },
    {
        "h": "Cross-Phone Graph — direction & flow of communication",
        "d": "An opt-in \u201cFlow view\u201d shows who initiated contact and which way it flowed. Default \u201cConnection view\u201d is unchanged.",
        "items": [
            {"id": "flow-arrows", "t": "Flow view shows arrows on comms edges",
             "how": "On the Cross-Phone Graph, turn on Messages/Calls, then click \u201cFlow view\u201d. Edges between people show arrows (initiator \u2192 recipient). Resource/structural edges have no arrows.",
             "tag": "data", "pr": "#63/#68", "ticket": "S2-17",
             "note": "Only Person\u2194Person call/message/email edges get arrows \u2014 make sure such edges exist."},
            {"id": "flow-particles", "t": "Flowing particles show volume & one-sidedness",
             "how": "In Flow view, busy edges have more/faster animated particles; a one-sided conversation (X messages Y a lot, rarely back) flows faster than a balanced one.",
             "tag": "ui", "pr": "#64", "ticket": "S2-19"},
            {"id": "flow-legend", "t": "Flow-view legend appears",
             "how": "In Flow view a small legend explains the arrows (direction) and particles (flow). It's hidden in Connection view.",
             "tag": "ui", "pr": "#65", "ticket": "S2-20"},
            {"id": "flow-direction-counts", "t": "Edge direction reflects who initiated",
             "how": "Arrow direction/weighting matches the real initiator\u2192recipient counts (the per-direction tallies computed on the backend).",
             "tag": "data", "pr": "#63", "ticket": "S2-18"},
            {"id": "flow-connection-unchanged", "t": "Default Connection view is unchanged",
             "how": "With Flow view OFF, the graph looks and behaves exactly as before \u2014 no arrows, same edge widths.",
             "tag": "data", "pr": "#63", "ticket": "S2-17"},
        ],
    },
    {
        "h": "Cross-Phone Graph — complete search (the \u201cPiney Bench Road\u201d case)",
        "d": "Search now finds places by their address/attributes, not just node names, and pulls them onto the canvas.",
        "items": [
            {"id": "search-by-attribute", "t": "Search finds a place by its address",
             "how": "Search a place like \u201cPiney Bench Road\u201d. It resolves the location even though that text is an address attribute, not a node label.",
             "tag": "data", "pr": "#66", "ticket": "S2-13"},
            {"id": "search-subgraph", "t": "Search returns the node plus its surrounding context",
             "how": "A search result comes back with its immediate neighbourhood (a small subgraph), not just a lone node.",
             "tag": "data", "pr": "#66", "ticket": "S2-14"},
            {"id": "search-pull-onto-canvas", "t": "Off-screen results get pulled in with context",
             "how": "A matching node that wasn't on the canvas (beyond the render cap) is pulled in via \u201cShow on canvas / Frame + neighbours\u201d, framed and highlighted.",
             "tag": "ui", "pr": "#67", "ticket": "S2-15"},
            {"id": "search-expand-neighbours", "t": "\u201cExpand neighbours\u201d grows the view one hop",
             "how": "From a found node, \u201cexpand neighbours\u201d adds one more ring of connections and re-frames.",
             "tag": "ui", "pr": "#67", "ticket": "S2-16"},
            {"id": "search-pivot", "t": "Pivot from a result to Timeline / Comms",
             "how": "From a search result (or selected node card), \u201copen in Timeline / Comms\u201d lands in that tab pre-filtered to the entity.",
             "tag": "ui", "pr": "#67", "ticket": "S2-16"},
            {"id": "graphbug-search-rebuilds", "t": "Searching rebuilds the graph (doesn't just dim)",
             "how": "Run a graph search/filter that should change what's drawn \u2014 the canvas actually rebuilds to the new set (camera/positions preserved), rather than leaving the old graph on screen.",
             "tag": "ui", "pr": "#66/#67", "ticket": "S2-05"},
            {"id": "graphbug-selection-canvas", "t": "Selecting a result shows on the canvas",
             "how": "Click a search result / select nodes \u2014 the selected node(s) get a visible ring on the canvas, not just a highlighted list row.",
             "tag": "ui", "pr": "#67", "ticket": "S2-06"},
            {"id": "graphbug-filters-narrow", "t": "Edge-type filters actually narrow the graph",
             "how": "Toggle comm-type filters (messages/calls/email) \u2014 edges of the deselected types disappear from the canvas and the per-node pie reflects only what's left.",
             "tag": "ui", "pr": "#67", "ticket": "S2-07"},
        ],
    },
    {
        "h": "Cross-Phone Graph — detail & flow panels (your \u201cflow through data\u201d ask)",
        "d": "Click into edges, see one combined event stream, lay the graph out by time, and trace how two people connect.",
        "items": [
            {"id": "edge-click-detail", "t": "Click an edge \u2192 the messages between that pair",
             "how": "Click a directional edge between two people. A panel shows their actual calls/messages/emails in time order, with the per-direction counts in the header.",
             "tag": "data", "pr": "#70", "ticket": "Flow-edge"},
            {"id": "edge-detail-not-empty", "t": "Edge detail is populated (the empty-panel bug is fixed)",
             "how": "The edge panel actually lists messages (previously it came back empty for group-chat participants). Confirm a pair you know talked shows their real messages.",
             "tag": "data", "pr": "#71", "ticket": "Flow-edge"},
            {"id": "flow-event-stream", "t": "\u201cEvent stream\u201d = one timeline across the whole graph",
             "how": "Click \u201cEvent stream\u201d in the graph header. A panel shows one chronological feed of every call/message/email across the people currently shown, grouped by day. Clicking a row opens its detail.",
             "tag": "data", "pr": "#72", "ticket": "Flow-1"},
            {"id": "flow-time-layout", "t": "\u201cTimeline layout\u201d lays people out by time",
             "how": "Click \u201cTimeline layout\u201d. People spread left\u2192right by their earliest activity (earliest on the left). Toggle it off to return to the normal layout.",
             "tag": "data", "pr": "#73", "ticket": "Flow-2"},
            {"id": "flow-trace-path", "t": "\u201cTrace path\u201d between two people",
             "how": "Rubber-band-select exactly two people \u2192 a \u201cTrace path\u201d button appears \u2192 the panel shows how they're connected (the shortest path, e.g. via a shared chat) and the messages along each hop.",
             "tag": "data", "pr": "#74", "ticket": "Flow-3"},
            {"id": "flow-drill", "t": "\u201cDrill\u201d re-anchors the graph on a person",
             "how": "Click a person \u2192 in the flyout click \u201cDrill\u201d. The graph rebuilds around that person (you'll see a \u201cPerspective\u201d chip and a smaller focused graph).",
             "tag": "data", "pr": "#69", "ticket": "Flow-drill"},
        ],
    },
    {
        "h": "Adding your own nodes (with provenance)",
        "d": "Investigators can author nodes, and they're clearly marked as user-created vs imported phone data.",
        "items": [
            {"id": "node-add", "t": "Add a node from the Cross-Phone Graph",
             "how": "Click \u201cAdd node\u201d in the graph header \u2192 fill in name/type \u2192 create. The graph refreshes and the new node appears.",
             "tag": "ui", "pr": "#79", "ticket": "S2-25"},
            {"id": "node-distinct-style", "t": "Authored nodes look different from imported data",
             "how": "In the main case graph, a node you created shows a distinct amber dashed ring, so it's unmistakable from imported nodes.",
             "tag": "data", "pr": "#80", "ticket": "S2-26",
             "note": "Visible once you've created at least one node."},
            {"id": "node-provenance", "t": "Authored nodes carry an audit trail",
             "how": "Backend: a created node records who made it and when (user_created / created_by / created_at). You won't see this directly, but it underpins the distinct styling above.",
             "tag": "data", "pr": "#78", "ticket": "S2-28"},
            {"id": "node-bool-serialization", "t": "Provenance flags serialize correctly (true, not 1)",
             "how": "Backend: the user_created flag stores as a real boolean true in the graph, not the integer 1. (Underpins reliable filtering/styling of authored nodes.)",
             "tag": "data", "pr": "#78", "ticket": "S2-28"},
        ],
    },
    {
        "h": "Client report (PDF)",
        "d": "Turn analysis into a client deliverable: device summaries, flagged key events, and a PDF export.",
        "items": [
            {"id": "report-device-cards", "t": "Per-device summary cards",
             "how": "On the Report tab, each device shows a summary card (owner, model, activity window, contact/message/call counts, aliases).",
             "tag": "data", "pr": "#62", "ticket": "S3-06"},
            {"id": "report-star-callout", "t": "Star key events as \u201ccallouts\u201d",
             "how": "On the Timeline, click the \u2605 on an important event. Reload \u2014 it stays starred (saved). Click again to unstar. Starring shouldn't open the row's detail flyout.",
             "tag": "data", "pr": "#81", "ticket": "S3-07"},
            {"id": "report-export-pdf", "t": "Export PDF includes the device summary",
             "how": "Go to the Report tab, click \u201cExport PDF\u201d. A PDF downloads with the per-device summary section.",
             "tag": "ui", "pr": "#62/#82", "ticket": "S3-05"},
            {"id": "report-callouts-in-pdf", "t": "Exported PDF includes the callouts section",
             "how": "Star a few events, then Export PDF. The PDF has a \u201cKey Events / Callouts\u201d section listing them chronologically with your notes.",
             "tag": "ui", "pr": "#82", "ticket": "S3-08",
             "note": "With no callouts, that section reads \u201cNo callouts flagged.\u201d"},
            {"id": "report-visualization-slot", "t": "Report has a visualization section",
             "how": "The assembled report includes a visualization section/slot. Live graph images embedded into the report are a known follow-up.",
             "tag": "ui", "pr": "#82", "ticket": "S3-09",
             "note": "Embedding live graph images is a documented follow-up."},
        ],
    },
    {
        "h": "Search & Discovery center \u2014 REBUILT into a detailed search engine",
        "d": "The Search & Discovery tab was rebuilt from a shallow tab-launcher into a real search engine. It now searches EVERY data type Cellebrite holds (not just person/message/location/\u201cOther\u201d/file), every result EXPANDS in place to show the full record, and \u201copen in tab\u201d actually lands you on the exact record pre-filtered. The phantom \u201cscoped to N phones\u201d is fixed. (Search runs on Enter/the Search button \u2014 an all-types scan is heavy, so it doesn't fire on every keystroke.)",
        "items": [
            {"id": "disc-tab-exists", "t": "\u201cSearch & Discovery\u201d tab is present",
             "how": "Open a case \u2192 Phone Reports workspace \u2192 \u201cSearch & Discovery\u201d tab (after Report). It shows a big search box; press Enter or the Search button to run.",
             "tag": "data", "pr": "S&D rebuild", "ticket": "S2-01"},
            {"id": "disc-search-all-types", "t": "Searches EVERY data type, not just a few",
             "how": "Type a term and Enter. Results should span far more than before \u2014 e.g. People, Contacts, Calls, Messages, Emails, Locations, Web history, Searches, Accounts, Wi-Fi, Installed apps, Notes, Social media, Files, etc. The old single \u201cOther\u201d bucket should be gone; each type is named with its own count.",
             "tag": "data", "pr": "S&D rebuild", "ticket": "S2-01"},
            {"id": "disc-families", "t": "Results grouped into named categories under families",
             "how": "Matches are grouped by category (Calls, Emails, Web history\u2026) under colour-coded family headers (People, Communications, Location, Web & Apps, Accounts & Security, Calendar & Notes, Social & Media, Media & Files, Device & System). Each shows a count.",
             "tag": "data", "pr": "S&D rebuild", "ticket": "S2-02"},
            {"id": "disc-expand", "t": "Expand any result to read the full record in place",
             "how": "Click a result row (or its chevron). It expands to a labelled field list \u2014 message body+thread, email subject/body, file category/size, location address/coords, account fields, etc. \u2014 WITHOUT leaving the tab. (This is the \u201ccan't click to expand\u201d bug.)",
             "tag": "ui", "pr": "S&D rebuild", "ticket": "S2-02"},
            {"id": "disc-family-toggle", "t": "Family chips show/hide categories",
             "how": "The chip row (one per family, with a count) toggles whole families in/out of the results. Toggling is instant (no re-search).",
             "tag": "ui", "pr": "S&D rebuild", "ticket": "S2-02"},
            {"id": "disc-more-counts", "t": "Groups show true totals + \u201c+N more\u201d",
             "how": "A category with many matches shows the first several plus \u201c+N more \u2014 refine your search\u201d, and the header count is the real total.",
             "tag": "data", "pr": "S&D rebuild", "ticket": "S2-02"},
            {"id": "disc-deeplink-people", "t": "Open a person/contact \u2192 Comms FILTERED to them",
             "how": "Expand a People/Contacts result \u2192 \u201cOpen in Comms Center\u201d. It switches to Comms ALREADY filtered to that person's communications (not an unfiltered feed).",
             "tag": "ui", "pr": "S&D rebuild", "ticket": "S2-03"},
            {"id": "disc-deeplink-message", "t": "Open a message/email \u2192 Comms opens that thread",
             "how": "Open a Messages or Emails result \u2192 Comms deep-searches the text and auto-opens the matching thread (you land ON the conversation, not an empty feed).",
             "tag": "ui", "pr": "S&D rebuild", "ticket": "S2-03"},
            {"id": "disc-deeplink-file", "t": "Open a file \u2192 Files FILTERED to that filename",
             "how": "Open a Files result \u2192 the Files tab opens already searched to that filename (was: landed in Files with no filter).",
             "tag": "ui", "pr": "S&D rebuild", "ticket": "S2-03"},
            {"id": "disc-deeplink-location", "t": "Open a location \u2192 Locations seeded with the place",
             "how": "Open a Locations/cell-tower result \u2192 the Locations tab opens with that place/address pre-searched.",
             "tag": "ui", "pr": "S&D rebuild", "ticket": "S2-03"},
            {"id": "disc-scope-fixed", "t": "No phantom \u201cscoped to N phones\u201d",
             "how": "With all phones selected (the default), there should be NO \u201cscoped to\u2026\u201d note \u2014 it searches everything. Only after you DESELECT some phones should it read \u201cscoped to N of M phones\u201d and limit results to those devices.",
             "tag": "ui", "pr": "S&D rebuild", "ticket": "S2-01"},
            {"id": "disc-show-in-graph", "t": "\u201cShow in graph\u201d sends a result to the Cross-Phone Graph",
             "how": "Use the graph (\u2317) action on a People/resource result \u2014 it switches to the Cross-Phone Graph (anchored on that person where applicable).",
             "tag": "ui", "pr": "S&D rebuild", "ticket": "S2-04"},
            {"id": "disc-address-search", "t": "Finds a place by its address (the \u201cPiney Bench Road\u201d ask)",
             "how": "Search an address that lives on a location's attributes (not its name). It surfaces under Locations. Diacritics fold too (e.g. \u201cdia\u201d matches \u201cD\u00eda\u201d).",
             "tag": "data", "pr": "S&D rebuild", "ticket": "S2-04",
             "note": "Stylised-unicode names (e.g. a fancy-font/emoji name) are NOT yet matched by plain text \u2014 tracked as a separate bug (user-bug-2)."},
        ],
    },
    {
        "h": "Regression check \u2014 pre-existing features (not changed this round)",
        "d": "These shipped BEFORE this round of work. They're listed only so QA can confirm nothing regressed while the new features were added \u2014 they are not new deliverables.",
        "items": [
            {"id": "reg-comms-type-filter", "t": "Comms multi-select type filter still works",
             "how": "In the Comms Center, toggle message/call/email types \u2014 the feed filters accordingly.",
             "tag": "ui", "pr": "pre-existing", "ticket": "S2-22"},
            {"id": "reg-comms-combined-filters", "t": "Combined comms filters still compose",
             "how": "Combine type \u00d7 participant \u00d7 app \u00d7 attachment-only filters in the Comms Center \u2014 they narrow together as expected.",
             "tag": "ui", "pr": "pre-existing", "ticket": "S2-23"},
            {"id": "reg-events-playback", "t": "Events Center playback bar still works",
             "how": "In Location & Events, the playback bar animates events over time on the map.",
             "tag": "ui", "pr": "pre-existing", "ticket": "(pre-existing)"},
        ],
    },
    {
        "h": "Your reported bugs — fixes to verify (round 2)",
        "d": "Fixes for the bugs/requests Alex logged in the hub on 2026-06-09. Please re-test each and Pass/Fail.",
        "items": [
            {"id": "fix-phone-lens-names", "t": "Contacts show from the VIEWING phone's perspective",
             "how": "Isolate C5 then C6 (phone selector) and open the Timeline / Comms. A number saved differently per phone should now show how THAT phone saved it (e.g. Pefro / Mry), not a single global 'Trabajo 444'. Applies to messages, calls and emails in the timeline, the event detail rail, and call/email threads. (Chat messages already did this.)",
             "tag": "data", "pr": "fixes r2", "ticket": "user-bug-1",
             "note": "Phase 1: device-lens names. The optional 'universal label alongside the device name' idea is a separate follow-up."},
            {"id": "fix-unicode-search", "t": "Stylised-unicode names are searchable by plain text",
             "how": "In the Comms/Contacts/Timeline search boxes, search a plain word (e.g. 'kathia') for a contact saved with fancy letters/emoji (e.g. a fancy-font/emoji name). It should now match. Accents fold too (Día ↔ dia).",
             "tag": "data", "pr": "fixes r2", "ticket": "user-bug-2",
             "note": "Fixed for client-side filters. Backend Search & Discovery against stylised STORED names is a follow-up (needs a normalised index)."},
            {"id": "fix-comms-timeline-window", "t": "Comms Timeline flyover fills its window (no white gap)",
             "how": "Open the cross-type Timeline flyover in the Comms Center and drag it taller. The content should fill the panel — no empty white gap below.",
             "tag": "ui", "pr": "fixes r2", "ticket": "user-bug-3"},
            {"id": "fix-pdf-export", "t": "Export filtered comms to PDF",
             "how": "In the Comms Center, set a filter (participants + date range), then click 'Timeline PDF' or 'Conversation PDF' under the toolbar. A PDF opens in a new tab. Timeline = chronological list; Conversation = grouped by thread. (Media is omitted; very large/unfiltered exports are capped at 2,000 items with a note.)",
             "tag": "ui", "pr": "fixes r2", "ticket": "user-feature-4"},
            {"id": "fix-events-time-hover", "t": "Full date & time on hover in the Events table",
             "how": "In Location & Events, hover the time cell of a row — a tooltip shows the full date+time. (Timeline already had this.)",
             "tag": "ui", "pr": "fixes r2", "ticket": "tl-time-hover"},
            {"id": "fix-media-scroll", "t": "Smoother scrolling in media-heavy threads",
             "how": "Open a thread with many images/voicenotes and scroll. Images now reserve space (less jank) and voicenotes don't all pre-fetch. Should feel smoother.",
             "tag": "ui", "pr": "fixes r2", "ticket": "media-smooth-scroll"},
            {"id": "fix-timeline-copy", "t": "Can select & copy text in the Comms Timeline",
             "how": "In the Comms Center's cross-type Timeline (bottom flyover), drag to select a message's text and copy it (Ctrl/Cmd+C). Selecting text should NOT open the row's detail; a normal click still does.",
             "tag": "ui", "pr": "fixes r3", "ticket": "user-bug-5"},
            {"id": "fix-timeline-duplicates", "t": "No duplicate messages in the Comms Timeline",
             "how": "In the cross-type Timeline, the same message captured on two phones now shows ONCE, not multiple times. Calls are unaffected.",
             "tag": "data", "pr": "fixes r3", "ticket": "user-bug-6"},
            {"id": "fix-timeline-scroll", "t": "Comms Timeline keeps loading as you scroll",
             "how": "Scroll to the bottom of the cross-type Timeline (List view) on a large filter - it should keep loading more rows automatically until everything is loaded, not stop after the first page.",
             "tag": "ui", "pr": "fixes r3", "ticket": "user-bug-7"},
            {"id": "fix-cross-identity-filter", "t": "Cross-identity filter (Link identities)",
             "how": "In the Comms Center there's a 'Link identities' checkbox (on by default, next to the Export buttons). With it ON, filtering by a contact also pulls in their OTHER app/device identities that share a phone number, handle or email (e.g. one person across phone + Snapchat + Instagram). Turn it off to see only the exact identity you picked. Watch the timeline/thread counts change as you toggle.",
             "tag": "data", "pr": "fixes r4", "ticket": "user-bug-8"},
            {"id": "known-name-only-identities", "t": "KNOWN LIMIT: identities linked ONLY by name aren't auto-merged",
             "how": "If two identities share NO phone/handle/email (only the same display name, e.g. two different 'Kathy' nodes), 'Link identities' will NOT combine them - that's deliberate (many people share a name). Use Contacts -> Merge identities to link those manually; the filter then respects the merge.",
             "tag": "ui", "pr": "fixes r4", "ticket": "user-bug-8",
             "note": "By design - name is too weak a signal to auto-merge. Manual merge is the path for name-only cases."},
        ],
    },
]


def flat_items():
    """Yield (section_heading, item) for every item, for validation/iteration."""
    for sec in CHECKLIST:
        for it in sec["items"]:
            yield sec["h"], it


def item_count() -> int:
    return sum(len(sec["items"]) for sec in CHECKLIST)


def all_ids():
    return [it["id"] for _, it in flat_items()]
