"""
Testing checklist — single source of truth for the QA testing hub.

This is the catalogue of testable behaviours shipped in the Cellebrite work
(PRs #56–#83). It is consumed by the `testing` router which serves both the
standalone hub page and the JSON the page renders from. Keep `item id`s stable
once shipped — tester feedback is keyed on them.

Each item:
    id   : stable slug (do NOT change once testers have used it)
    t    : title (plain language)
    what : plain-language explanation of the feature itself
    how  : how to test it
    tag  : 'data' (underlying data/logic already verified — mainly visual check)
           or 'ui' (built + compiles, behaviour not yet exercised — test properly)
    pr   : PR reference(s)
    ticket: sprint ticket id(s)
    note : optional caveat
"""

CHECKLIST = [
    {
        "h": "Timeline — reading messages & identities",
        "d": "The Timeline tab: rows now show more about each message and who was involved.",
        "items": [
            {"id": "tl-inline-body", "t": "Message body shows inline (no clicking)",
             "what": "Instead of a clipped one-line preview, each timeline row displays the message's actual text. An investigator can read the conversation while scanning the case chronologically, without opening every message one by one.",
             "how": "Scroll the Timeline. You should read the actual message text in each row (up to ~3 lines), not just a one-line snippet. Hover for the full text.",
             "tag": "data", "pr": "#56/#76", "ticket": "S1-15"},
            {"id": "tl-to-from-numbers", "t": "To/From phone numbers appear on the row",
             "what": "Phone numbers are shown alongside every sender and recipient name. Names alone can be ambiguous \u2014 different phones save different names for the same person \u2014 so the number is the reliable identifier an investigator anchors on.",
             "how": "On a message/call row, each party shows as \u201cName \u00b7 +number\u201d. Rows with no number just show the name.",
             "tag": "data", "pr": "#56", "ticket": "S1-13"},
            {"id": "tl-device-local-name", "t": "Recipient shows the name saved on the sending phone",
             "what": "Contacts are shown from each phone's own perspective \u2014 the name exactly as that device saved it, never one merged global name. How a suspect labelled someone in their own phone (a nickname, an alias) is itself evidence and must not be papered over.",
             "how": "Open a contact saved under different names on two phones. The recipient should show the name as stored on the device that sent the message (not one global name).",
             "tag": "ui", "pr": "#56", "ticket": "S1-11"},
            {"id": "tl-time-hover", "t": "Full date & time on hover",
             "what": "Every event keeps its exact full date and time behind the compact display, so an investigator can pin an event to the precise moment when reconstructing a sequence of events.",
             "how": "Hover the time on any row \u2014 a tooltip shows the full date and time.",
             "tag": "data", "pr": "#57", "ticket": "S1-06"},
            {"id": "tl-tz-offset", "t": "Timezone offset on day headers",
             "what": "All timestamps are stored in UTC and rendered in a display timezone the investigator selects. The day headers state the offset in force, so it is always unambiguous which clock the timeline is being read in \u2014 vital when events span timezones or daylight-saving changes.",
             "how": "Each day header shows the active timezone (e.g. \u201c\u00b7 UTC\u22124\u201d). Switch the timezone selector and confirm it updates; a day that spans a daylight-saving change shows the right offset.",
             "tag": "data", "pr": "#57", "ticket": "S1-07"},
            {"id": "tl-comms-numbers", "t": "Numbers also shown in the Comms view",
             "what": "The number-alongside-name rule applies in the Comms Center too: conversation rows show the other party's phone number next to the saved name, so identity is never left to a possibly misleading contact label.",
             "how": "In the Comms Center, message rows show the other party's number beside the name.",
             "tag": "ui", "pr": "#57", "ticket": "S1-12"},
        ],
    },
    {
        "h": "Timeline — media in the row (your \u201czero-click\u201d ask)",
        "d": "Images and voice notes now appear directly in the timeline row. Needs a case WITH media \u2014 the demo data has none, so test on real data.",
        "items": [
            {"id": "media-voice-inline", "t": "Voice notes play right in the row",
             "what": "Voice notes recovered from a phone can be played directly inside the timeline row, so an investigator can listen to audio evidence in its conversational context without opening a separate detail view.",
             "how": "Find a message with a voice note. A small audio player appears in the row \u2014 press play and it plays, no need to open the message.",
             "tag": "ui", "pr": "#76", "ticket": "S1-17",
             "note": "Demo data has no media \u2014 must be tested on a real case."},
            {"id": "media-voice-preload", "t": "Voice notes don't fetch bytes until you press play",
             "what": "Audio files are only downloaded when the investigator actually presses play. This keeps media-heavy cases fast to scroll and avoids pulling down megabytes of recordings nobody listened to.",
             "how": "On a thread full of voice notes, scrolling shouldn't fire dozens of audio downloads. Bytes load only when you press play (preload=none).",
             "tag": "ui", "pr": "#76", "ticket": "S1-17",
             "note": "Best confirmed via the Network tab on a media-heavy real case."},
            {"id": "media-image-thumbs", "t": "Image thumbnails show inline",
             "what": "Photos attached to a message appear as small previews right in the timeline row, so image evidence is visible while reading the conversation rather than hidden behind a click.",
             "how": "A message with photos shows the thumbnails in the row.",
             "tag": "ui", "pr": "#76", "ticket": "S1-16",
             "note": "Demo data has no media \u2014 test on a real case."},
            {"id": "media-image-lightbox", "t": "Clicking a thumbnail opens the full image",
             "what": "Any inline thumbnail can be enlarged to full size for proper inspection of the image, and closing the viewer puts the investigator back exactly where they were in the timeline.",
             "how": "Click an inline thumbnail \u2014 the full-size image opens in a viewer/lightbox. Closing it returns you to the same scroll position.",
             "tag": "ui", "pr": "#76", "ticket": "S1-16",
             "note": "Demo data has no media \u2014 test on a real case."},
            {"id": "media-smooth-scroll", "t": "Scrolling stays smooth with media rows",
             "what": "The timeline is engineered to stay responsive even when rows contain images and audio players, so reviewing a media-heavy case doesn't turn into a slow, stuttering experience.",
             "how": "Scroll quickly through a media-heavy stretch \u2014 no jumpiness, blank gaps, or freezing.",
             "tag": "ui", "pr": "#75/#76", "ticket": "S1-18"},
        ],
    },
    {
        "h": "Timeline — navigation & stability",
        "d": "Sorting, jumping to a day, loading more, and not crashing on bad data.",
        "items": [
            {"id": "nav-virtualized-rows", "t": "Variable-height rows render correctly (virtualized)",
             "what": "The timeline only draws the rows currently on screen so huge cases stay fast, while still coping with rows of wildly different heights \u2014 short texts, long bodies, media \u2014 which is what makes the inline-content features possible at scale.",
             "how": "Rows of different heights (short text vs. long body vs. media) all render fully with no overlap or clipping as you scroll \u2014 the list measures each row.",
             "tag": "ui", "pr": "#75", "ticket": "S1-14"},
            {"id": "nav-sort-toggle", "t": "Sort newest-first / oldest-first toggle",
             "what": "Investigators can read a case newest-first (what happened most recently) or oldest-first (how events unfolded from the start), and the app remembers the choice for that case.",
             "how": "Use the sort toggle in the Timeline header. It flips both the day groups and the rows. Reload the page \u2014 your choice is remembered for that case.",
             "tag": "data", "pr": "#58", "ticket": "S1-05"},
            {"id": "nav-jump-to-day", "t": "Jump-to-day (scrubber) lands correctly",
             "what": "A date scrubber lets the investigator jump straight to a specific day instead of scrolling through months of events \u2014 essential when working from a known date of interest, like the day of an offence.",
             "how": "Use the date scrubber to jump to a day. The list scrolls to the right day \u2014 try it in both sort directions.",
             "tag": "ui", "pr": "#75", "ticket": "S1-14"},
            {"id": "nav-load-more-events", "t": "\u201cLoad more\u201d reaches older events",
             "what": "Big cases load in pages: the timeline always states how many events are shown out of the true total and offers a way to load the rest, so no evidence is ever silently cut off.",
             "how": "On a big case, scroll to the bottom \u2014 a \u201cLoad more\u201d button appears and the count climbs (\u201cShowing N of TOTAL\u201d). Narrowing the date range hides the button.",
             "tag": "data", "pr": "#59", "ticket": "S3-02"},
            {"id": "nav-load-more-comms-files", "t": "\u201cLoad more\u201d on Comms threads & Files too",
             "what": "The same no-silent-cutoff principle applies to the Comms thread list and the Files list: long lists declare their totals and let you keep loading rather than quietly truncating.",
             "how": "The Comms threads list and the Files list also show \u201cLoad more\u201d past their limits.",
             "tag": "ui", "pr": "#59", "ticket": "S3-04"},
            {"id": "nav-keyset-fast", "t": "Deep paging stays fast (keyset)",
             "what": "The server pages through events efficiently, so loading deep into a case with hundreds of thousands of events is as quick as loading the first page \u2014 investigators on large extractions don't get punished for going back in time.",
             "how": "Backend behaviour: loading far into a very large event list stays fast (no re-reading earlier pages). Confirm the timeline doesn't slow down as you load more.",
             "tag": "data", "pr": "#60", "ticket": "S3-03"},
            {"id": "nav-no-invalid-date", "t": "No \u201cInvalid Date\u201d crashes",
             "what": "Real phone extractions contain events with missing or malformed timestamps. The app degrades gracefully on those (showing a dash) instead of crashing or printing \u201cInvalid Date\u201d, so one bad record can never block review of the rest of the case.",
             "how": "Events with a missing/bad timestamp show \u201c\u2014\u201d or blank, never \u201cInvalid Date\u201d, and never crash the view.",
             "tag": "data", "pr": "#61", "ticket": "S1-02"},
            {"id": "nav-empty-error-states", "t": "Clear empty / error states",
             "what": "When there is nothing to show \u2014 no phones selected, zero results, or a server problem \u2014 the app says why and offers a way forward. An investigator should never mistake an empty screen for an empty case or a broken app.",
             "how": "With no phones selected, or zero results, or a backend error, each tab shows a clear message (and a Retry where relevant) instead of a blank screen.",
             "tag": "ui", "pr": "#58", "ticket": "S1-03"},
        ],
    },
    {
        "h": "Timeline — duplicate-message clean-up (the bug you spotted)",
        "d": "The same message no longer appears three times across device sources.",
        "items": [
            {"id": "dedup-collapse", "t": "Duplicated message now shows once",
             "what": "Phones often store the same message in several places (the SMS app, a sync service, a log database) and the extraction reports every copy. The timeline now collapses true duplicates into one row, so an investigator isn't misled into thinking a message was sent three times.",
             "how": "Find the message that used to appear 3\u00d7 (e.g. across Native Messages / IMS Service / Android CallLog). It now shows a single row with a subtle \u201c\u00b7 +N sources\u201d chip \u2014 hover it to see the other sources it was extracted from.",
             "tag": "data", "pr": "#83", "ticket": "S2-31"},
            {"id": "dedup-sources-chip", "t": "The \u201c+N sources\u201d chip lists the other sources",
             "what": "The collapsing is transparent, not destructive: a chip on the row reveals every extraction source the message was found in, preserving the forensic detail of where each copy lived on the device.",
             "how": "Hover/inspect the \u201c+N sources\u201d chip on a collapsed message \u2014 it names the other extraction sources (apps) the duplicate came from.",
             "tag": "data", "pr": "#83", "ticket": "S2-31"},
            {"id": "dedup-no-false-merge", "t": "Genuinely different messages are NOT merged",
             "what": "De-duplication is deliberately strict \u2014 only messages identical in time, text and sender collapse \u2014 so two genuinely separate messages are never merged together and no evidence is ever hidden by the clean-up.",
             "how": "Two distinct messages that happen to share a time still show separately. Only true duplicates (same time + text + sender) collapse.",
             "tag": "data", "pr": "#83", "ticket": "S2-31"},
        ],
    },
    {
        "h": "Cross-Phone Graph — direction & flow of communication",
        "d": "An opt-in \u201cFlow view\u201d shows who initiated contact and which way it flowed. Default \u201cConnection view\u201d is unchanged.",
        "items": [
            {"id": "flow-arrows", "t": "Flow view shows arrows on comms edges",
             "what": "Flow view is an opt-in mode of the Cross-Phone Graph that adds direction to relationships: arrows show who initiated contact with whom. Direction matters for investigative questions like who recruits, who instructs, and who merely responds.",
             "how": "On the Cross-Phone Graph, turn on Messages/Calls, then click \u201cFlow view\u201d. Edges between people show arrows (initiator \u2192 recipient). Resource/structural edges have no arrows.",
             "tag": "data", "pr": "#63/#68", "ticket": "S2-17",
             "note": "Only Person\u2194Person call/message/email edges get arrows \u2014 make sure such edges exist."},
            {"id": "flow-particles", "t": "Flowing particles show volume & one-sidedness",
             "what": "Animated particles along a connection convey at a glance how heavy and how one-sided a relationship is \u2014 someone who constantly messages a person who rarely replies looks visibly different from a balanced two-way conversation.",
             "how": "In Flow view, busy edges have more/faster animated particles; a one-sided conversation (X messages Y a lot, rarely back) flows faster than a balanced one.",
             "tag": "ui", "pr": "#64", "ticket": "S2-19"},
            {"id": "flow-legend", "t": "Flow-view legend appears",
             "what": "A small legend explains what the arrows and particles mean, so an investigator \u2014 or anyone seeing a screenshot of the graph \u2014 can interpret Flow view correctly without training.",
             "how": "In Flow view a small legend explains the arrows (direction) and particles (flow). It's hidden in Connection view.",
             "tag": "ui", "pr": "#65", "ticket": "S2-20"},
            {"id": "flow-direction-counts", "t": "Edge direction reflects who initiated",
             "what": "The arrows aren't decorative: they're driven by real counts of who initiated each call and message in each direction, so the visual story matches the underlying evidence.",
             "how": "Arrow direction/weighting matches the real initiator\u2192recipient counts (the per-direction tallies computed on the backend).",
             "tag": "data", "pr": "#63", "ticket": "S2-18"},
            {"id": "flow-connection-unchanged", "t": "Default Connection view is unchanged",
             "what": "Flow view is strictly additive \u2014 the default Connection view that investigators already rely on looks and behaves exactly as before unless they explicitly opt in to the new mode.",
             "how": "With Flow view OFF, the graph looks and behaves exactly as before \u2014 no arrows, same edge widths.",
             "tag": "data", "pr": "#63", "ticket": "S2-17"},
        ],
    },
    {
        "h": "Cross-Phone Graph — complete search (the \u201cPiney Bench Road\u201d case)",
        "d": "Search now finds places by their address/attributes, not just node names, and pulls them onto the canvas.",
        "items": [
            {"id": "search-by-attribute", "t": "Search finds a place by its address",
             "what": "Graph search now looks inside a node's stored details (like a location's street address), not just its display name. An investigator can find \u201cthe place on Piney Bench Road\u201d even though no node is literally named that.",
             "how": "Search a place like \u201cPiney Bench Road\u201d. It resolves the location even though that text is an address attribute, not a node label.",
             "tag": "data", "pr": "#66", "ticket": "S2-13"},
            {"id": "search-subgraph", "t": "Search returns the node plus its surrounding context",
             "what": "A search hit comes back together with its immediate connections, because in an investigation the value of a node is usually who and what it's linked to, not the node in isolation.",
             "how": "A search result comes back with its immediate neighbourhood (a small subgraph), not just a lone node.",
             "tag": "data", "pr": "#66", "ticket": "S2-14"},
            {"id": "search-pull-onto-canvas", "t": "Off-screen results get pulled in with context",
             "what": "Very large cases can't draw every node at once, so something you search for may not currently be on screen. Search can pull such a node onto the canvas with its neighbours \u2014 the drawing limit never hides a result from the investigator.",
             "how": "A matching node that wasn't on the canvas (beyond the render cap) is pulled in via \u201cShow on canvas / Frame + neighbours\u201d, framed and highlighted.",
             "tag": "ui", "pr": "#67", "ticket": "S2-15"},
            {"id": "search-expand-neighbours", "t": "\u201cExpand neighbours\u201d grows the view one hop",
             "what": "From any found node the investigator can grow the picture one hop at a time, gradually revealing the surrounding network around an entity of interest without redrawing the whole case.",
             "how": "From a found node, \u201cexpand neighbours\u201d adds one more ring of connections and re-frames.",
             "tag": "ui", "pr": "#67", "ticket": "S2-16"},
            {"id": "search-pivot", "t": "Pivot from a result to Timeline / Comms",
             "what": "Search results are a launchpad, not a dead end: one click jumps from an entity in the graph to that same entity's messages in Comms or events in the Timeline, already filtered, keeping the investigation flowing between views.",
             "how": "From a search result (or selected node card), \u201copen in Timeline / Comms\u201d lands in that tab pre-filtered to the entity.",
             "tag": "ui", "pr": "#67", "ticket": "S2-16"},
            {"id": "graphbug-search-rebuilds", "t": "Searching rebuilds the graph (doesn't just dim)",
             "what": "When a search or filter changes which nodes should be shown, the canvas genuinely redraws to the new set. Previously it could merely dim the old picture, leaving stale, no-longer-relevant evidence on screen.",
             "how": "Run a graph search/filter that should change what's drawn \u2014 the canvas actually rebuilds to the new set (camera/positions preserved), rather than leaving the old graph on screen.",
             "tag": "ui", "pr": "#66/#67", "ticket": "S2-05"},
            {"id": "graphbug-selection-canvas", "t": "Selecting a result shows on the canvas",
             "what": "Selecting a result highlights the node on the canvas itself, so the investigator can see where that entity sits in the network \u2014 not just that a row lit up in a side list.",
             "how": "Click a search result / select nodes \u2014 the selected node(s) get a visible ring on the canvas, not just a highlighted list row.",
             "tag": "ui", "pr": "#67", "ticket": "S2-06"},
            {"id": "graphbug-filters-narrow", "t": "Edge-type filters actually narrow the graph",
             "what": "The message/call/email filters truly remove connections of the deselected types from the drawing, so what's on screen always reflects exactly the communication types the investigator chose to look at.",
             "how": "Toggle comm-type filters (messages/calls/email) \u2014 edges of the deselected types disappear from the canvas and the per-node pie reflects only what's left.",
             "tag": "ui", "pr": "#67", "ticket": "S2-07"},
        ],
    },
    {
        "h": "Cross-Phone Graph — detail & flow panels (your \u201cflow through data\u201d ask)",
        "d": "Click into edges, see one combined event stream, lay the graph out by time, and trace how two people connect.",
        "items": [
            {"id": "edge-click-detail", "t": "Click an edge \u2192 the messages between that pair",
             "what": "Every line between two people in the graph is backed by their real communications. Clicking it opens the actual calls and messages between that pair in time order \u2014 turning an abstract link into readable evidence.",
             "how": "Click a directional edge between two people. A panel shows their actual calls/messages/emails in time order, with the per-direction counts in the header.",
             "tag": "data", "pr": "#70", "ticket": "Flow-edge"},
            {"id": "edge-detail-not-empty", "t": "Edge detail is populated (the empty-panel bug is fixed)",
             "what": "Fixes a bug where the edge panel came back empty for people who only talked inside group chats. The panel now reliably shows the conversation behind every relationship the graph draws.",
             "how": "The edge panel actually lists messages (previously it came back empty for group-chat participants). Confirm a pair you know talked shows their real messages.",
             "tag": "data", "pr": "#71", "ticket": "Flow-edge"},
            {"id": "flow-event-stream", "t": "\u201cEvent stream\u201d = one timeline across the whole graph",
             "what": "The Event stream merges every call, message and email among the people currently on the graph into one chronological feed, so the investigator can read the whole network's activity as a single unfolding story.",
             "how": "Click \u201cEvent stream\u201d in the graph header. A panel shows one chronological feed of every call/message/email across the people currently shown, grouped by day. Clicking a row opens its detail.",
             "tag": "data", "pr": "#72", "ticket": "Flow-1"},
            {"id": "flow-time-layout", "t": "\u201cTimeline layout\u201d lays people out by time",
             "what": "Timeline layout arranges people across the screen by when they first became active in the case, so the investigator can literally see the order in which people entered the picture.",
             "how": "Click \u201cTimeline layout\u201d. People spread left\u2192right by their earliest activity (earliest on the left). Toggle it off to return to the normal layout.",
             "tag": "data", "pr": "#73", "ticket": "Flow-2"},
            {"id": "flow-trace-path", "t": "\u201cTrace path\u201d between two people",
             "what": "Trace path answers the classic investigative question \u201chow are these two people connected?\u201d \u2014 it finds the shortest chain between two selected people (e.g. via a shared group chat) and shows the actual messages along each link.",
             "how": "Rubber-band-select exactly two people \u2192 a \u201cTrace path\u201d button appears \u2192 the panel shows how they're connected (the shortest path, e.g. via a shared chat) and the messages along each hop.",
             "tag": "data", "pr": "#74", "ticket": "Flow-3"},
            {"id": "flow-drill", "t": "\u201cDrill\u201d re-anchors the graph on a person",
             "what": "Drill rebuilds the graph centred on one person of interest, stripping away everything not connected to them. It lets the investigator study a single suspect's world without the noise of the entire case.",
             "how": "Click a person \u2192 in the flyout click \u201cDrill\u201d. The graph rebuilds around that person (you'll see a \u201cPerspective\u201d chip and a smaller focused graph).",
             "tag": "data", "pr": "#69", "ticket": "Flow-drill"},
        ],
    },
    {
        "h": "Adding your own nodes (with provenance)",
        "d": "Investigators can author nodes, and they're clearly marked as user-created vs imported phone data.",
        "items": [
            {"id": "node-add", "t": "Add a node from the Cross-Phone Graph",
             "what": "Investigators can add their own entities to the graph \u2014 for example a suspect known from other intelligence who doesn't appear in any phone \u2014 so the case picture isn't limited to what the extractions contained.",
             "how": "Click \u201cAdd node\u201d in the graph header \u2192 fill in name/type \u2192 create. The graph refreshes and the new node appears.",
             "tag": "ui", "pr": "#79", "ticket": "S2-25"},
            {"id": "node-distinct-style", "t": "Authored nodes look different from imported data",
             "what": "It is forensically critical that analyst-created content is never confused with data extracted from a phone. Nodes an investigator authored carry an unmistakable visual marker so the two can't be mixed up.",
             "how": "In the main case graph, a node you created shows a distinct amber dashed ring, so it's unmistakable from imported nodes.",
             "tag": "data", "pr": "#80", "ticket": "S2-26",
             "note": "Visible once you've created at least one node."},
            {"id": "node-provenance", "t": "Authored nodes carry an audit trail",
             "what": "Every node an investigator creates is recorded with who created it and when. That audit trail keeps user additions defensible in court and is what powers the distinct styling of authored nodes.",
             "how": "Backend: a created node records who made it and when (user_created / created_by / created_at). You won't see this directly, but it underpins the distinct styling above.",
             "tag": "data", "pr": "#78", "ticket": "S2-28"},
            {"id": "node-bool-serialization", "t": "Provenance flags serialize correctly (true, not 1)",
             "what": "A plumbing fix: the \u201cuser-created\u201d marker is stored as a proper true/false value rather than a number, so the styling and filtering that distinguish authored nodes from phone data work reliably everywhere.",
             "how": "Backend: the user_created flag stores as a real boolean true in the graph, not the integer 1. (Underpins reliable filtering/styling of authored nodes.)",
             "tag": "data", "pr": "#78", "ticket": "S2-28"},
        ],
    },
    {
        "h": "Client report (PDF)",
        "d": "Turn analysis into a client deliverable: device summaries, flagged key events, and a PDF export.",
        "items": [
            {"id": "report-device-cards", "t": "Per-device summary cards",
             "what": "The Report tab summarises each seized device \u2014 owner, model, activity window, headline counts \u2014 giving the client-facing deliverable a per-phone overview without the investigator writing it up by hand.",
             "how": "On the Report tab, each device shows a summary card (owner, model, activity window, contact/message/call counts, aliases).",
             "tag": "data", "pr": "#62", "ticket": "S3-06"},
            {"id": "report-star-callout", "t": "Star key events as \u201ccallouts\u201d",
             "what": "Investigators can star events as \u201ckey events\u201d while reviewing the timeline, and the stars are saved. Significant findings get captured the moment they're spotted and later feed straight into the client report.",
             "how": "On the Timeline, click the \u2605 on an important event. Reload \u2014 it stays starred (saved). Click again to unstar. Starring shouldn't open the row's detail flyout.",
             "tag": "data", "pr": "#81", "ticket": "S3-07"},
            {"id": "report-export-pdf", "t": "Export PDF includes the device summary",
             "what": "The analysis can be exported as a PDF \u2014 a deliverable an investigator can hand to a client, prosecutor or court \u2014 starting with the per-device summaries.",
             "how": "Go to the Report tab, click \u201cExport PDF\u201d. A PDF downloads with the per-device summary section.",
             "tag": "ui", "pr": "#62/#82", "ticket": "S3-05"},
            {"id": "report-callouts-in-pdf", "t": "Exported PDF includes the callouts section",
             "what": "The events an investigator starred flow into the exported PDF as a chronological \u201cKey Events\u201d section with their notes, so the report tells the story of the most important moments rather than just statistics.",
             "how": "Star a few events, then Export PDF. The PDF has a \u201cKey Events / Callouts\u201d section listing them chronologically with your notes.",
             "tag": "ui", "pr": "#82", "ticket": "S3-08",
             "note": "With no callouts, that section reads \u201cNo callouts flagged.\u201d"},
            {"id": "report-visualization-slot", "t": "Report has a visualization section",
             "what": "The report reserves a section for visualisations (such as the relationship graph), so the deliverable can include the pictures investigators rely on. Embedding live graph images is a known follow-up \u2014 for now the slot itself exists.",
             "how": "The assembled report includes a visualization section/slot. Live graph images embedded into the report are a known follow-up.",
             "tag": "ui", "pr": "#82", "ticket": "S3-09",
             "note": "Embedding live graph images is a documented follow-up."},
        ],
    },
    {
        "h": "Search & Discovery center (the unified omni-search you flagged)",
        "d": "A brand-new tab: one search box across EVERY phone and EVERY data type at once, with results grouped by type and one-click pivots into the right tab. This is the \u201csearch-and-discovery center\u201d from the call notes \u2014 it had not been built before; it is now.",
        "items": [
            {"id": "disc-tab-exists", "t": "\u201cSearch & Discovery\u201d tab is present",
             "what": "A brand-new workspace tab housing the unified search: one place for an investigator to ask \u201cwhere does X appear anywhere in this case?\u201d across all phones and all data types at once.",
             "how": "Open a case \u2192 Phone Reports workspace. There's a new \u201cSearch & Discovery\u201d tab near the top (after Report). Opening it shows a big search box.",
             "tag": "data", "pr": "#84", "ticket": "S2-01"},
            {"id": "disc-search-all-types", "t": "One search spans people, messages, places, files",
             "what": "A single query simultaneously searches people, message text, places, files and more across every phone in the case. Investigators no longer have to repeat the same search tab by tab and risk missing where else a term appears.",
             "how": "Type a name, a phone number, a phrase from a message, an address, or a filename. Results come back covering all of those at once \u2014 not just one slice.",
             "tag": "data", "pr": "#84", "ticket": "S2-01"},
            {"id": "disc-grouping", "t": "Results are grouped by type",
             "what": "Matches come back sorted into evidence-type buckets (People, Messages, Locations, Other, Files), each with a count, so the investigator can see at a glance what kinds of evidence a search term touched.",
             "how": "Matches are grouped into People / Messages / Locations / Other / Files, each with a count. Empty groups say \u201cno matches\u201d.",
             "tag": "data", "pr": "#84", "ticket": "S2-02"},
            {"id": "disc-type-filter", "t": "Type toggles narrow the result groups",
             "what": "Type chips let the investigator hide result groups that aren't relevant right now (e.g. show only Messages), while the UI guarantees at least one type always stays visible so the search never goes blank.",
             "how": "Use the type chips (People, Messages, Locations, Other, Files) to show/hide groups. You can't turn them all off (at least one stays on).",
             "tag": "ui", "pr": "#84", "ticket": "S2-02"},
            {"id": "disc-phone-scope", "t": "Search can be scoped to selected phones",
             "what": "Search can be limited to a chosen subset of the seized phones \u2014 important when a case has many devices and only some are of interest \u2014 and the bar states the scope so a narrowed search is never mistaken for a full one.",
             "how": "Select a subset of phones (phone selector) \u2014 results scope to those devices and the bar notes \u201cscoped to N phones\u201d.",
             "tag": "ui", "pr": "#84", "ticket": "S2-01"},
            {"id": "disc-more-counts", "t": "Groups show true totals + \u201c+N more\u201d",
             "what": "When a search has many hits, each group's header shows the true total \u2014 not just the handful displayed \u2014 so the investigator always knows how much evidence exists and is never misled by silent truncation.",
             "how": "A group with many matches shows the first several plus \u201c+N more \u2014 refine your search\u201d, and the count in the header is the real total (not just what's shown).",
             "tag": "data", "pr": "#84", "ticket": "S2-02"},
            {"id": "disc-pivot-comms", "t": "Open a person/message result \u2192 lands in Comms pre-filtered",
             "what": "A search hit is a doorway: opening a person or message result drops the investigator into the Comms Center already filtered to that person or conversation, going from \u201cfound it\u201d to \u201creading the conversation\u201d in one click.",
             "how": "Click the open (\u2197) action on a People or Messages result \u2014 it switches to the Comms Center pre-filtered to that person/those participants.",
             "tag": "data", "pr": "#84", "ticket": "S2-03"},
            {"id": "disc-pivot-tabs", "t": "Location/File results open their native tab",
             "what": "Each kind of result opens in its natural home \u2014 locations on the map (Location & Events), files in the Files tab \u2014 so every piece of evidence gets examined with the right tool rather than a generic detail page.",
             "how": "Open a Location result \u2192 lands on Location & Events; open a File result \u2192 lands on Files.",
             "tag": "ui", "pr": "#84", "ticket": "S2-03"},
            {"id": "disc-show-in-graph", "t": "\u201cShow in graph\u201d sends a result to the Cross-Phone Graph",
             "what": "Any person or place found in search can be sent straight to the Cross-Phone Graph, anchored on that entity, so the investigator can immediately see who and what it connects to across devices.",
             "how": "Use the graph (\u2317) action on a People/place result \u2014 it switches to the Cross-Phone Graph anchored on that entity (phrase search reaches the graph).",
             "tag": "data", "pr": "#84", "ticket": "S2-04"},
            {"id": "disc-address-search", "t": "Finds a place by its address (the \u201cPiney Bench Road\u201d ask)",
             "what": "The unified search matches against stored details like street addresses, not only names, so a place can be found by where it is rather than what it happens to be called \u2014 the original \u201cPiney Bench Road\u201d request, now in omni-search too.",
             "how": "Search an address that lives on a location's attributes (not its name). It still surfaces under Locations/Other. (On a case that contains such an address \u2014 demo cases may not.)",
             "tag": "ui", "pr": "#84", "ticket": "S2-04",
             "note": "Needs a case whose locations carry reverse-geocoded addresses."},
        ],
    },
    {
        "h": "Regression check \u2014 pre-existing features (not changed this round)",
        "d": "These shipped BEFORE this round of work. They're listed only so QA can confirm nothing regressed while the new features were added \u2014 they are not new deliverables.",
        "items": [
            {"id": "reg-comms-type-filter", "t": "Comms multi-select type filter still works",
             "what": "A pre-existing Comms Center filter that narrows the conversation feed to messages, calls and/or emails. Listed here purely to confirm this round of changes didn't break it.",
             "how": "In the Comms Center, toggle message/call/email types \u2014 the feed filters accordingly.",
             "tag": "ui", "pr": "pre-existing", "ticket": "S2-22"},
            {"id": "reg-comms-combined-filters", "t": "Combined comms filters still compose",
             "what": "The pre-existing ability to stack Comms filters \u2014 type, participant, app, attachments-only \u2014 and have them narrow the feed together. Checked here only as a regression guard.",
             "how": "Combine type \u00d7 participant \u00d7 app \u00d7 attachment-only filters in the Comms Center \u2014 they narrow together as expected.",
             "tag": "ui", "pr": "pre-existing", "ticket": "S2-23"},
            {"id": "reg-events-playback", "t": "Events Center playback bar still works",
             "what": "The pre-existing map playback in Location & Events that animates a phone's events over time, letting an investigator watch movement and activity unfold. A quick check that it still runs after this round's changes.",
             "how": "In Location & Events, the playback bar animates events over time on the map.",
             "tag": "ui", "pr": "pre-existing", "ticket": "(pre-existing)"},
        ],
    },
]


def flat_items():
    """Yield (section_heading, item) for every item, for validation/iteration."""
    for sec in CHECKLIST:
        for it in sec["items"]:
            yield sec["h"], it


def item_count() -> int:
    return sum(len(sec["items"]) for sec in CHECKLIST)


def all_ids():
    return [it["id"] for _, it in flat_items()]
