"""Cover section for case file exports."""

from __future__ import annotations

from html import escape

from services.case_export.registry import register_section
from services.case_export.types import ExportSection, SectionContext


def _display_user(context: SectionContext) -> str:
    return context.current_user.name or context.current_user.email


def render_cover(context: SectionContext) -> str:
    generated_at = context.generated_at.strftime("%Y-%m-%d %H:%M UTC")
    section_items = "".join(
        f"<li>{escape(section.label)}</li>"
        for section in context.included_sections
        if section.key != "cover"
    )
    if not section_items:
        section_items = "<li>Cover page only</li>"

    return f"""
        <div class="cover-page">
            <div class="document-label">Case File Export</div>
            <h1>{escape(context.case.title)}</h1>
            <dl class="cover-meta">
                <div>
                    <dt>Case ID</dt>
                    <dd>{escape(str(context.case.id))}</dd>
                </div>
                <div>
                    <dt>Generated by</dt>
                    <dd>{escape(_display_user(context))}</dd>
                </div>
                <div>
                    <dt>Generated</dt>
                    <dd>{escape(generated_at)}</dd>
                </div>
            </dl>
            <div class="included-sections">
                <h2>Included Sections</h2>
                <ol>{section_items}</ol>
            </div>
        </div>
    """


register_section(
    ExportSection(
        key="cover",
        label="Cover",
        description="Case title, export metadata, and included section list.",
        default_enabled=True,
        order=0,
        render=render_cover,
    )
)
