"""Tests for :mod:`services.financial.check_digits`.

Three things these tests are built to hold, beyond the obvious one that the
arithmetic is right.

**That the four outcomes stay four.**  The value of
:class:`~postgres.models.enums.CheckDigitOutcome` is entirely in the
distinctions it keeps, and every one of those distinctions is the sort a later
refactor collapses without noticing: ``malformed`` back into ``failed``
because both are "not good", or ``no_check_digit`` into ``passed`` because both
are "not bad".  So the tests assert the specific member rather than
:attr:`~services.financial.check_digits.CheckDigitResult.passes_gate`, except
where the gate itself is the subject.

**That the check digit algorithms are held against published values.**  A
check digit implementation is a thing that can be subtly wrong and still look
right — a reversed weight table, an off-by-one in which digit is doubled — and
self-consistent tests are exactly the kind that cannot see it.  So the vectors
here are real: routing numbers of the Federal Reserve, IBANs from the ISO 13616
registry examples, the card numbers the networks publish for testing, LEIs from
the GLEIF index.  A value generated by this module's own arithmetic proves only
that the module agrees with itself.

**That the properties claimed in prose are measured.**  The module docstring
makes falsifiable claims — Luhn misses ``09``↔``90`` categorically rather than
usually, MOD-97-10 catches every same-class substitution — and those claims are
the argument for what the checks are worth.  They are re-measured here, so that
the documentation cannot drift away from the code and quietly become a
statement about what somebody once believed.
"""

from __future__ import annotations

import random
import unittest

from postgres.models.enums import CheckDigitOutcome, IdentifierKind
from services.financial import check_digits as cd
from services.financial import nacha
from services.financial.check_digits import (
    CHECK_ABA_WEIGHTED_MOD10,
    CHECK_IBAN_COUNTRY_LENGTH,
    CHECK_ISO7064_MOD97_10,
    CHECK_LUHN_MOD10,
    CHECK_SSN_ISSUED_RANGES,
    CHECK_STRUCTURE,
    IBAN_COUNTRY_LENGTHS,
    CheckDigitError,
    CheckDigitResult,
    aba_check_digit,
    iso7064_mod97_10_residue,
    luhn_residue,
    normalise,
    verify,
)

ALNUM = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

#: Four real IBANs spanning both BBAN shapes: all-digit (DE, CH) and
#: letter-bearing (GB, NL).  The sweeps below need both, because the residual
#: gap in MOD-97-10 is precisely at the boundary between the two.
REAL_IBANS = (
    "GB82WEST12345698765432",
    "DE89370400440532013000",
    "NL91ABNA0417164300",
    "CH9300762011623852957",
)


def iban_check_digits(country: str, bban: str) -> str:
    """The two digits that make ``country + digits + bban`` a valid IBAN.

    Used to build values that are arithmetically sound but wrong in some other
    way, which is the only way to test a check that runs *after* the checksum.
    """
    residue = iso7064_mod97_10_residue(f"{bban}{country}00")
    return f"{98 - residue:02d}"


def build_iban(country: str, bban: str) -> str:
    """A checksum-valid IBAN with the country and BBAN given."""
    return f"{country}{iban_check_digits(country, bban)}{bban}"


class OutcomeVocabularyTests(unittest.TestCase):
    """The distinctions the four-valued outcome exists to keep."""

    def test_a_wrong_shape_and_a_wrong_number_are_different_verdicts(self) -> None:
        """The central design claim, asserted directly.

        Both of these are "not a good routing number" and a boolean would say
        the same thing about each.  They call for opposite responses: the first
        sends someone to the extractor, because nothing that read a routing
        number field correctly produces seven characters; the second sends
        someone to the document, because those nine digits were read fine and
        disagree with themselves.
        """
        wrong_shape = verify(IdentifierKind.aba_routing, "0210000")
        wrong_number = verify(IdentifierKind.aba_routing, "021000022")
        self.assertIs(wrong_shape.outcome, CheckDigitOutcome.malformed)
        self.assertIs(wrong_number.outcome, CheckDigitOutcome.failed)
        self.assertNotEqual(wrong_shape.outcome, wrong_number.outcome)

    def test_nothing_to_check_is_not_reported_as_a_pass(self) -> None:
        """A BIC is well-formed and unverified, and both halves are recorded.

        Reporting ``passed`` here would be the single most expensive mistake
        this module could make, because it would put "verified" against a value
        that no arithmetic has ever touched, in a corpus whose whole claim is
        that its numbers were checked.
        """
        result = verify(IdentifierKind.bic, "DEUTDEFF")
        self.assertIs(result.outcome, CheckDigitOutcome.no_check_digit)
        self.assertIsNot(result.outcome, CheckDigitOutcome.passed)
        self.assertEqual(result.checks_performed, (CHECK_STRUCTURE,))
        self.assertIn("no check digit", result.detail)

    def test_the_gate_admits_the_uncheckable_and_holds_the_wrong(self) -> None:
        """`13` §5.5's gate, and why ``no_check_digit`` has to pass it.

        Holding every BIC for human adjudication would stop a large fraction of
        the corpus for a reason that is a property of ISO 9362 rather than of
        anything in the documents, and the reviewers would learn within a day
        to wave them through — which is worse than not asking.
        """
        self.assertTrue(verify(IdentifierKind.bic, "DEUTDEFF").passes_gate)
        self.assertTrue(verify(IdentifierKind.us_ein, "123456789").passes_gate)
        self.assertTrue(verify(IdentifierKind.aba_routing, "021000021").passes_gate)
        self.assertFalse(verify(IdentifierKind.aba_routing, "021000022").passes_gate)
        self.assertFalse(verify(IdentifierKind.aba_routing, "02100002").passes_gate)

    def test_a_result_cannot_be_edited_after_it_is_recorded(self) -> None:
        """Frozen, because this is read back when an exhibit is challenged."""
        result = verify(IdentifierKind.aba_routing, "021000021")
        with self.assertRaises(Exception):
            result.outcome = CheckDigitOutcome.failed  # type: ignore[misc]
        self.assertIs(result.outcome, CheckDigitOutcome.passed)


class IbanTests(unittest.TestCase):
    """ISO 13616 with ISO 7064 MOD-97-10, and the country length table."""

    #: Registry examples plus two in-the-wild forms.  Spaced as they are
    #: conventionally printed, since that is how they arrive in a document.
    PUBLISHED = (
        "GB82 WEST 1234 5698 7654 32",
        "DE89 3704 0044 0532 0130 00",
        "FR14 2004 1010 0505 0001 3M02 606",
        "GB29 NWBK 6016 1331 9268 19",
        "NL91 ABNA 0417 1643 00",
        "CH93 0076 2011 6238 5295 7",
        "SA03 8000 0000 6080 1016 7519",
    )

    def test_published_ibans_pass_with_all_three_checks_named(self) -> None:
        """Every country here is in the table, so all three checks run."""
        for value in self.PUBLISHED:
            with self.subTest(value):
                result = verify(IdentifierKind.iban, value)
                self.assertIs(result.outcome, CheckDigitOutcome.passed)
                self.assertEqual(
                    result.checks_performed,
                    (CHECK_STRUCTURE, CHECK_ISO7064_MOD97_10, CHECK_IBAN_COUNTRY_LENGTH),
                )
                self.assertEqual(result.detail, "")

    def test_one_altered_digit_fails_the_checksum(self) -> None:
        result = verify(IdentifierKind.iban, "GB82 WEST 1234 5698 7654 33")
        self.assertIs(result.outcome, CheckDigitOutcome.failed)
        self.assertIn("MOD-97-10", result.detail)

    def test_the_shape_is_checked_before_the_arithmetic(self) -> None:
        """Each of these is malformed for a different reason, and says which."""
        for value, fragment in [
            ("", "empty"),
            ("GB82", "11 to 30"),
            ("1B82WEST12345698765432", "two letters"),
            ("GBB2WEST12345698765432", "two digits"),
            ("GB82WEST123456987654$2", "alphanumeric"),
            ("GB82" + "W" * 31, "11 to 30"),
        ]:
            with self.subTest(value):
                result = verify(IdentifierKind.iban, value)
                self.assertIs(result.outcome, CheckDigitOutcome.malformed)
                self.assertEqual(result.checks_performed, (CHECK_STRUCTURE,))
                self.assertIn(fragment, result.detail)

    def test_an_unknown_country_is_checked_by_checksum_alone_and_says_so(self) -> None:
        """Absence from the table is a limit of this module, not a defect.

        ``ZZ`` is a user-assigned code and will never be in the registry, which
        makes it a stable stand-in for a country the table has not yet caught
        up with.  The point of the assertion is the *checks_performed* tuple:
        the result passes, and it states that the length was never looked at,
        so a reader is not left to infer the difference from the country code.
        """
        self.assertNotIn("ZZ", IBAN_COUNTRY_LENGTHS)
        value = build_iban("ZZ", "12345678901234")
        result = verify(IdentifierKind.iban, value)
        self.assertIs(result.outcome, CheckDigitOutcome.passed)
        self.assertEqual(
            result.checks_performed, (CHECK_STRUCTURE, CHECK_ISO7064_MOD97_10)
        )
        self.assertNotIn(CHECK_IBAN_COUNTRY_LENGTH, result.checks_performed)

    def test_a_known_country_at_the_wrong_length_fails_and_names_both(self) -> None:
        """The self-contradictory verdict, which is deliberate.

        This value's checksum is genuinely correct — it was constructed that
        way — and its length is not what the table says GB uses.  Either the
        IBAN lost or gained a character in carriage, or the table is wrong.
        The detail says both facts so the reader can tell which, rather than
        reporting a bare rejection that would be indistinguishable from a bad
        number and would hide a defect in this module's own data.
        """
        value = build_iban("GB", "WEST1234569876543")  # one longer than GB's 22
        self.assertNotEqual(len(value), IBAN_COUNTRY_LENGTHS["GB"])
        result = verify(IdentifierKind.iban, value)
        self.assertIs(result.outcome, CheckDigitOutcome.failed)
        self.assertEqual(
            result.checks_performed,
            (CHECK_STRUCTURE, CHECK_ISO7064_MOD97_10, CHECK_IBAN_COUNTRY_LENGTH),
        )
        self.assertIn("checksum passed", result.detail)
        self.assertIn(str(IBAN_COUNTRY_LENGTHS["GB"]), result.detail)
        self.assertIn(str(len(value)), result.detail)
        self.assertIn("table in this module is wrong", result.detail)

    def test_the_country_length_table_is_internally_plausible(self) -> None:
        """Cheap guards on a human-entered table.

        These cannot tell whether an entry matches the registry — nothing
        available here can — but they catch the transcription slips that would
        otherwise reject every IBAN from one country: a two-digit length typed
        as one, a country code in lower case, a length outside what ISO 13616
        permits at all.
        """
        for country, length in IBAN_COUNTRY_LENGTHS.items():
            with self.subTest(country):
                self.assertRegex(country, r"^[A-Z]{2}$")
                self.assertGreaterEqual(length, cd.IBAN_MIN_LENGTH)
                self.assertLessEqual(length, cd.IBAN_MAX_LENGTH)

    def test_the_table_agrees_with_the_published_ibans(self) -> None:
        """The one external check on the table available offline."""
        for value in self.PUBLISHED:
            with self.subTest(value):
                flat = normalise(value)
                self.assertEqual(IBAN_COUNTRY_LENGTHS[flat[:2]], len(flat))


class LeiTests(unittest.TestCase):
    """ISO 17442: the same MOD-97-10, over the whole value rather than rotated."""

    def test_published_leis_pass(self) -> None:
        for value in ("5493001KJTIIGC8Y1R12", "549300MLUDYVRQOOXS22"):
            with self.subTest(value):
                result = verify(IdentifierKind.lei, value)
                self.assertIs(result.outcome, CheckDigitOutcome.passed)
                self.assertEqual(
                    result.checks_performed,
                    (CHECK_STRUCTURE, CHECK_ISO7064_MOD97_10),
                )

    def test_an_altered_check_digit_fails(self) -> None:
        result = verify(IdentifierKind.lei, "5493001KJTIIGC8Y1R13")
        self.assertIs(result.outcome, CheckDigitOutcome.failed)

    def test_the_last_two_characters_must_be_digits(self) -> None:
        """ISO 17442 puts the check digits there, so a letter is malformed.

        Worth its own test because the value is otherwise twenty valid
        alphanumerics, and a pattern that allowed alphanumerics throughout
        would accept it and then compute a residue over a value that has no
        check digits in it at all.
        """
        result = verify(IdentifierKind.lei, "5493001KJTIIGC8Y1R1A")
        self.assertIs(result.outcome, CheckDigitOutcome.malformed)
        self.assertIn("2 digits", result.detail)

    def test_the_length_is_exactly_twenty(self) -> None:
        for value in ("5493001KJTIIGC8Y1R1", "5493001KJTIIGC8Y1R123"):
            with self.subTest(value):
                self.assertIs(
                    verify(IdentifierKind.lei, value).outcome,
                    CheckDigitOutcome.malformed,
                )


class AbaRoutingTests(unittest.TestCase):
    """Nine digits, weights 3-7-1 repeating, sum a multiple of ten."""

    #: Live Federal Reserve routing numbers.  Not generated by this module.
    REAL = ("021000021", "011000015", "121000248", "071000013", "026009593")

    def test_real_routing_numbers_pass(self) -> None:
        for value in self.REAL:
            with self.subTest(value):
                result = verify(IdentifierKind.aba_routing, value)
                self.assertIs(result.outcome, CheckDigitOutcome.passed)
                self.assertEqual(
                    result.checks_performed,
                    (CHECK_STRUCTURE, CHECK_ABA_WEIGHTED_MOD10),
                )

    def test_the_failure_names_the_digit_it_expected(self) -> None:
        """So the reader can see the size of the discrepancy.

        A check digit off by one is a different kind of event from one that
        is off by five, and the second is much less likely to be a single
        misread character.  Stating both numbers lets that be judged without
        re-running anything.
        """
        result = verify(IdentifierKind.aba_routing, "021000022")
        self.assertIs(result.outcome, CheckDigitOutcome.failed)
        self.assertIn("check digit of 1", result.detail)
        self.assertIn("9th digit is 2", result.detail)

    def test_every_prefix_implies_exactly_one_valid_ninth_digit(self) -> None:
        """The property that makes the check worth anything.

        If two ninth digits verified for one prefix the check would catch half
        of what it claims to.  Swept over a thousand random prefixes rather
        than argued from the weights.
        """
        rng = random.Random(3)
        for _ in range(1000):
            prefix = f"{rng.randrange(10 ** 8):08d}"
            valid = [
                d
                for d in "0123456789"
                if verify(IdentifierKind.aba_routing, prefix + d).outcome
                is CheckDigitOutcome.passed
            ]
            self.assertEqual(len(valid), 1, prefix)
            self.assertEqual(int(valid[0]), aba_check_digit(prefix))

    def test_a_prefix_that_is_not_eight_digits_computes_nothing(self) -> None:
        for prefix in ("0210000", "021000021", "0210000A", "", "0210000 "):
            with self.subTest(prefix):
                self.assertIsNone(aba_check_digit(prefix))


class PaymentCardTests(unittest.TestCase):
    """ISO/IEC 7812-1 length, then Luhn."""

    #: Published network test numbers, plus the Wikipedia Luhn example.
    PUBLISHED = (
        "4111111111111111",
        "5500005555555559",
        "378282246310005",
        "6011111111111117",
        "3530111333300000",
        "79927398713",
    )

    def test_published_card_numbers_pass(self) -> None:
        for value in self.PUBLISHED:
            with self.subTest(value):
                if len(value) < cd.CARD_MIN_DIGITS:
                    continue
                result = verify(IdentifierKind.payment_card, value)
                self.assertIs(result.outcome, CheckDigitOutcome.passed)
                self.assertEqual(
                    result.checks_performed, (CHECK_STRUCTURE, CHECK_LUHN_MOD10)
                )

    def test_the_eleven_digit_luhn_example_is_too_short_to_be_a_card(self) -> None:
        """``79927398713`` checks out under Luhn and is not a card number.

        The distinction the two-stage check keeps: the arithmetic is fine and
        the value is still not the thing the caller said it was.  Reported as
        malformed, because that is a statement about shape.
        """
        self.assertEqual(luhn_residue("79927398713"), 0)
        result = verify(IdentifierKind.payment_card, "79927398713")
        self.assertIs(result.outcome, CheckDigitOutcome.malformed)
        self.assertIn("12 to 19", result.detail)

    def test_the_failure_states_the_residue(self) -> None:
        result = verify(IdentifierKind.payment_card, "4111111111111112")
        self.assertIs(result.outcome, CheckDigitOutcome.failed)
        self.assertIn("Luhn sum is 1", result.detail)

    def test_grouping_spaces_and_hyphens_are_not_an_error(self) -> None:
        """How a card number is written on a statement is not a finding."""
        for value in (
            "4111 1111 1111 1111",
            "4111-1111-1111-1111",
            "4111 1111-1111 1111",
        ):
            with self.subTest(value):
                result = verify(IdentifierKind.payment_card, value)
                self.assertIs(result.outcome, CheckDigitOutcome.passed)
                self.assertEqual(result.normalised, "4111111111111111")


class BicTests(unittest.TestCase):
    """ISO 9362 has no check digit, and this module refuses to pretend."""

    def test_both_legal_lengths_are_accepted(self) -> None:
        for value in ("DEUTDEFF", "DEUTDEFF500", "NEDSZAJJ", "UNCRITMMXXX"):
            with self.subTest(value):
                result = verify(IdentifierKind.bic, value)
                self.assertIs(result.outcome, CheckDigitOutcome.no_check_digit)

    def test_the_first_six_characters_must_be_letters(self) -> None:
        """Bank code then country code, neither of which admits a digit."""
        result = verify(IdentifierKind.bic, "DEUTD3FF")
        self.assertIs(result.outcome, CheckDigitOutcome.malformed)

    def test_nine_or_ten_characters_is_neither_length(self) -> None:
        for value in ("DEUTDEFF5", "DEUTDEFF50"):
            with self.subTest(value):
                self.assertIs(
                    verify(IdentifierKind.bic, value).outcome,
                    CheckDigitOutcome.malformed,
                )


class SsnTests(unittest.TestCase):
    """What survived randomisation, and the honesty about what did not."""

    def test_a_structurally_ordinary_ssn_is_unverified_not_verified(self) -> None:
        result = verify(IdentifierKind.us_ssn, "123-45-6789")
        self.assertIs(result.outcome, CheckDigitOutcome.no_check_digit)
        self.assertEqual(
            result.checks_performed, (CHECK_STRUCTURE, CHECK_SSN_ISSUED_RANGES)
        )
        self.assertIn("no check digit", result.detail)
        self.assertIn("randomisation", result.detail)

    def test_the_never_issued_ranges_are_refused_and_named(self) -> None:
        """Each exclusion tested separately, because each is a separate branch.

        A single test over one bad value would leave three of the four
        conditions unexercised, and the one most likely to be typed by a human
        filling a form — ``000-00-0000`` — would be caught by whichever
        condition happened to be checked first.
        """
        for value, fragment in [
            ("000-45-6789", "area 000"),
            ("666-45-6789", "area 666"),
            ("900-45-6789", "area 900"),
            ("999-45-6789", "area 999"),
            ("123-00-6789", "group 00"),
            ("123-45-0000", "serial 0000"),
        ]:
            with self.subTest(value):
                result = verify(IdentifierKind.us_ssn, value)
                self.assertIs(result.outcome, CheckDigitOutcome.malformed)
                self.assertIn(fragment, result.detail)
                self.assertFalse(result.passes_gate)

    def test_area_eight_hundred_something_is_not_excluded(self) -> None:
        """The boundary of the ``9xx`` rule, so it is not read as ``>= 800``."""
        self.assertIs(
            verify(IdentifierKind.us_ssn, "899-45-6789").outcome,
            CheckDigitOutcome.no_check_digit,
        )


class EinTests(unittest.TestCase):
    """Nine digits and a documented refusal to check the campus prefix."""

    def test_nine_digits_is_all_there_is(self) -> None:
        result = verify(IdentifierKind.us_ein, "12-3456789")
        self.assertIs(result.outcome, CheckDigitOutcome.no_check_digit)
        self.assertEqual(result.checks_performed, (CHECK_STRUCTURE,))
        self.assertEqual(result.normalised, "123456789")

    def test_an_unassigned_looking_prefix_is_not_rejected(self) -> None:
        """Deliberate: a stale prefix table would reject valid new EINs.

        ``07`` is not among the prefixes the IRS has historically published as
        assigned.  This module does not carry that table and so must not
        reject this, and the test exists to stop one being added without the
        staleness problem being solved first.
        """
        self.assertIs(
            verify(IdentifierKind.us_ein, "07-1234567").outcome,
            CheckDigitOutcome.no_check_digit,
        )

    def test_anything_that_is_not_nine_digits_is_malformed(self) -> None:
        """The one check an EIN does get must actually be applied.

        Because the passing verdict for an EIN is ``no_check_digit``, a
        structural guard that stopped working would not announce itself: every
        value, of every shape, would come back with the same unverified-looking
        result the good ones get.  This is the test that separates them.
        """
        for value in ("12345678", "1234567890", "12345678A", "1234-5678"):
            with self.subTest(value):
                result = verify(IdentifierKind.us_ein, value)
                self.assertIs(result.outcome, CheckDigitOutcome.malformed)
                self.assertEqual(result.checks_performed, (CHECK_STRUCTURE,))


class NormalisationTests(unittest.TestCase):
    """What is cleaned up, and the much larger set of what is not."""

    def test_spaces_hyphens_and_case_are_removed(self) -> None:
        self.assertEqual(normalise(" gb82 west-1234 "), "GB82WEST1234")

    def test_nothing_else_is_stripped(self) -> None:
        """A field carrying anything else went wrong upstream.

        The temptation is to strip punctuation generally, and the reason not to
        is that a value read from the wrong column — a currency amount, a
        reference with a slash in it — would then be quietly reshaped into
        something that could pass a structural check.  Malformed is the
        correct, and recoverable, answer.
        """
        for value in ("GB82.WEST", "GB82/WEST", "GB82\u00a0WEST", "GB82_WEST"):
            with self.subTest(value):
                self.assertIs(
                    verify(IdentifierKind.iban, value).outcome,
                    CheckDigitOutcome.malformed,
                )

    def test_a_non_string_is_a_caller_error_and_raises(self) -> None:
        """Not a verdict, because a verdict would be filed against a row."""
        for value in (None, 21000021, b"021000021", ["0"]):
            with self.subTest(value):
                with self.assertRaises(CheckDigitError):
                    verify(IdentifierKind.aba_routing, value)  # type: ignore[arg-type]

    def test_a_kind_that_is_not_the_enum_raises(self) -> None:
        """A string that happens to equal a member is still not the member.

        ``IdentifierKind`` inherits ``str``, so ``"iban" == IdentifierKind.iban``
        is true and a dictionary lookup on the plain string would succeed.  The
        guard is an ``isinstance`` check for that reason: accepting the string
        would make the enum decorative and let a typo become a silent lookup
        failure somewhere further along.
        """
        self.assertEqual("iban", IdentifierKind.iban)
        for kind in ("iban", None, 3):
            with self.subTest(kind):
                with self.assertRaises(CheckDigitError):
                    verify(kind, "GB82WEST12345698765432")  # type: ignore[arg-type]

    def test_an_empty_value_is_malformed_for_every_kind(self) -> None:
        for kind in IdentifierKind:
            with self.subTest(kind):
                for value in ("", "   ", "-", " - "):
                    result = verify(kind, value)
                    self.assertIs(result.outcome, CheckDigitOutcome.malformed)
                    self.assertEqual(result.detail, "the value is empty")


class NonAsciiDigitTests(unittest.TestCase):
    """Why the patterns use ``[0-9]`` and not ``\\d``.

    Python's ``\\d`` matches every Unicode decimal digit, and
    :meth:`str.isdigit` is true of more characters still.  Both would admit
    values that then behave unpredictably: ``int('\\u0663')`` is 3, so an
    Arabic-Indic digit would silently *convert*, while ``int('\\u00b2')``
    raises even though ``'\\u00b2'.isdigit()`` is true.  So one class of bad
    input would be quietly accepted with a changed value and another would
    crash the check.  Both must be ``malformed`` instead.
    """

    def test_arabic_indic_digits_are_malformed_not_converted(self) -> None:
        value = "411111111111111\u0663"  # trailing Arabic-Indic three
        self.assertTrue(value[-1].isdigit())
        self.assertEqual(int(value[-1]), 3)
        result = verify(IdentifierKind.payment_card, value)
        self.assertIs(result.outcome, CheckDigitOutcome.malformed)

    def test_a_superscript_two_is_malformed_rather_than_a_crash(self) -> None:
        value = "41111111111111\u00b21"
        self.assertTrue(value[-2].isdigit())
        with self.assertRaises(ValueError):
            int(value[-2])
        result = verify(IdentifierKind.payment_card, value)
        self.assertIs(result.outcome, CheckDigitOutcome.malformed)

    def test_every_pattern_refuses_them_and_not_just_the_card_one(self) -> None:
        """The rule has to hold for each pattern independently.

        ``_IBAN_RE``, ``_NINE_DIGITS_RE``, ``_CARD_RE`` and ``_LEI_RE`` each
        spell out ``[0-9]`` separately, so each can be relaxed to ``\\d``
        separately, and the three kinds that share ``_NINE_DIGITS_RE`` would all
        be relaxed at once.  What makes this worth a test per pattern rather
        than one for the module is that the damage differs by kind and none of
        it is a visible error: the IBAN raises out of the residue loop, the ABA
        computes ``ord('\\u0663') - 48`` and returns a confident *failed*
        against a number that was never nine digits, and the SSN and EIN return
        the same unverified verdict a well-formed value gets.
        """
        three = "\u0663"  # Arabic-Indic three; int() gives 3
        for kind, value in [
            (IdentifierKind.iban, "GB8" + three + "WEST12345698765432"),
            (IdentifierKind.aba_routing, "02100002" + three),
            (IdentifierKind.us_ssn, "12345678" + three),
            (IdentifierKind.us_ein, "12345678" + three),
            (IdentifierKind.lei, "5493001KJTIIGC8Y1R1" + three),
            (IdentifierKind.payment_card, "411111111111111" + three),
        ]:
            with self.subTest(kind):
                result = verify(kind, value)
                self.assertIs(result.outcome, CheckDigitOutcome.malformed)
                self.assertEqual(result.checks_performed, (CHECK_STRUCTURE,))

    def test_the_primitives_refuse_rather_than_return_a_wrong_residue(self) -> None:
        """Reached only by a caller bypassing :func:`verify`, and still safe."""
        with self.assertRaises(CheckDigitError):
            iso7064_mod97_10_residue("GB82\u0663")
        with self.assertRaises(CheckDigitError):
            luhn_residue("4111\u0663")
        with self.assertRaises(CheckDigitError):
            iso7064_mod97_10_residue("gb82")  # lower case is not handled here


class Iso7064PrimitiveTests(unittest.TestCase):
    """The incremental residue against the definition it optimises."""

    @staticmethod
    def expanded_residue(value: str) -> int:
        """MOD-97-10 by the textbook route: expand the whole thing, then mod."""
        return int("".join(str(ord(c) - 55) if c.isalpha() else c for c in value)) % 97

    def test_the_incremental_form_equals_the_expanded_form(self) -> None:
        """Twenty thousand random strings, because this is the one place where
        an optimisation could be wrong in a way no vector would show.

        A residue computed digit by digit is not obviously the same number as
        one computed by building a 60-digit integer, and the place it would
        diverge — a letter contributing two digits rather than one — is exactly
        the place the IBAN examples exercise least.
        """
        rng = random.Random(11)
        for _ in range(20000):
            value = "".join(
                rng.choice(ALNUM) for _ in range(rng.randint(1, 40))
            )
            self.assertEqual(
                iso7064_mod97_10_residue(value),
                self.expanded_residue(value),
                value,
            )

    def test_the_empty_string_has_residue_zero(self) -> None:
        """Stated so that a caller reaching it does not read it as valid."""
        self.assertEqual(iso7064_mod97_10_residue(""), 0)
        self.assertNotEqual(iso7064_mod97_10_residue(""), 1)


class MeasuredDetectionPowerTests(unittest.TestCase):
    """The claims the module docstring makes, re-measured rather than recited.

    `12` §6.4 says Luhn catches "roughly 80% of adjacent transpositions".  These
    tests exist because that is not merely imprecise, it is the wrong shape of
    claim: the misses are categorical.  A reader who believed the 80% figure
    would think a transposed ``09`` had a four-in-five chance of being caught,
    when it has none at all, and would rate a corpus of card numbers rather
    more trustworthy than it is.
    """

    @staticmethod
    def valid_luhn(rng: random.Random, length: int = 16) -> str:
        body = "".join(rng.choice("0123456789") for _ in range(length - 1))
        for digit in "0123456789":
            if luhn_residue(body + digit) == 0:
                return body + digit
        raise AssertionError("no check digit completes this body")

    def test_luhn_catches_every_single_digit_error(self) -> None:
        """No exceptions, not "almost all"."""
        rng = random.Random(7)
        numbers = [self.valid_luhn(rng) for _ in range(500)]
        tried = missed = 0
        for number in numbers:
            for index in range(len(number)):
                for digit in "0123456789":
                    if digit == number[index]:
                        continue
                    tried += 1
                    if luhn_residue(number[:index] + digit + number[index + 1:]) == 0:
                        missed += 1
        self.assertEqual(tried, 72000)
        self.assertEqual(missed, 0)

    def test_luhn_misses_only_zero_nine_and_misses_it_every_time(self) -> None:
        """Categorical, in both directions.

        The two assertions that matter are that ``09`` is *never* caught and
        that no other pair is *ever* missed.  Together they say the failure is
        a property of the digit pair alone and not of where it sits, which is
        what makes "all adjacent transpositions except 09" a safe thing to
        write down and "roughly 80%" a misleading one.
        """
        rng = random.Random(7)
        numbers = [self.valid_luhn(rng) for _ in range(3000)]
        missed: dict[str, int] = {}
        caught: dict[str, int] = {}
        for number in numbers:
            for index in range(len(number) - 1):
                first, second = number[index], number[index + 1]
                if first == second:
                    continue
                pair = "".join(sorted((first, second)))
                swapped = (
                    number[:index] + second + first + number[index + 2:]
                )
                bucket = missed if luhn_residue(swapped) == 0 else caught
                bucket[pair] = bucket.get(pair, 0) + 1

        self.assertEqual(len(missed) + len(caught) - len(set(missed) & set(caught)), 45)
        self.assertEqual(sorted(missed), ["09"])
        self.assertEqual(sorted(set(missed) & set(caught)), [])
        self.assertEqual(len(caught), 44)

    def test_luhn_misses_three_twin_errors_and_misses_them_categorically(self) -> None:
        """``22``↔``55``, ``33``↔``66``, ``44``↔``77``: absent from `12` entirely.

        A twin error is a doubled digit mistyped as a different doubled digit,
        which is a plausible slip on a keypad and not an exotic one.  Doubling
        under Luhn maps 2→4 and 5→1(0), and the pair differ by five, so the
        weighted contribution is unchanged in both positions at once.
        """
        rng = random.Random(13)
        numbers = [self.valid_luhn(rng) for _ in range(3000)]
        missed: set[str] = set()
        caught: set[str] = set()
        for number in numbers:
            for index in range(len(number) - 1):
                if number[index] != number[index + 1]:
                    continue
                original = number[index]
                for digit in "0123456789":
                    if digit == original:
                        continue
                    altered = (
                        number[:index] + digit + digit + number[index + 2:]
                    )
                    label = "".join(sorted((original * 2, digit * 2)))
                    target = missed if luhn_residue(altered) == 0 else caught
                    target.add(label)
        self.assertEqual(sorted(missed), ["2255", "3366", "4477"])
        self.assertEqual(sorted(missed & caught), [])

    def test_mod97_catches_every_same_class_substitution(self) -> None:
        """Digit for digit and letter for letter, across four real IBANs."""
        tried = missed = 0
        for base in REAL_IBANS:
            for index in range(4, len(base)):
                for char in ALNUM:
                    if char == base[index] or char.isalpha() != base[index].isalpha():
                        continue
                    tried += 1
                    candidate = base[:index] + char + base[index + 1:]
                    if (
                        verify(IdentifierKind.iban, candidate).outcome
                        is CheckDigitOutcome.passed
                    ):
                        missed += 1
        self.assertEqual(tried, 731)
        self.assertEqual(missed, 0)

    def test_mod97_catches_every_adjacent_transposition(self) -> None:
        tried = missed = 0
        for base in REAL_IBANS:
            for index in range(4, len(base) - 1):
                if base[index] == base[index + 1]:
                    continue
                tried += 1
                candidate = (
                    base[:index] + base[index + 1] + base[index] + base[index + 2:]
                )
                if (
                    verify(IdentifierKind.iban, candidate).outcome
                    is CheckDigitOutcome.passed
                ):
                    missed += 1
        self.assertEqual(tried, 56)
        self.assertEqual(missed, 0)

    def test_the_class_crossing_gap_is_real_and_the_length_table_does_not_close_it(
        self,
    ) -> None:
        """The module's least comfortable claim, held to a number.

        Thirteen escapes in 1,614 attempts, and the country length table makes
        no difference to that count because a substitution preserves length.
        The test asserts the equality directly so that nobody later reasons, as
        this module's own first draft did, that the table covers this gap.
        """
        tried = missed = 0
        for base in REAL_IBANS:
            for index in range(4, len(base)):
                for char in ALNUM:
                    if char == base[index] or char.isalpha() == base[index].isalpha():
                        continue
                    tried += 1
                    candidate = base[:index] + char + base[index + 1:]
                    if (
                        verify(IdentifierKind.iban, candidate).outcome
                        is CheckDigitOutcome.passed
                    ):
                        missed += 1
        self.assertEqual(tried, 1614)
        self.assertEqual(missed, 13)

        checksum_only = 0
        for base in REAL_IBANS:
            for index in range(4, len(base)):
                for char in ALNUM:
                    if char == base[index] or char.isalpha() == base[index].isalpha():
                        continue
                    candidate = base[:index] + char + base[index + 1:]
                    if iso7064_mod97_10_residue(candidate[4:] + candidate[:4]) == 1:
                        checksum_only += 1
        self.assertEqual(checksum_only, missed)


class DelegationTests(unittest.TestCase):
    """One implementation of each algorithm, held there."""

    def test_nacha_uses_this_modules_aba_function(self) -> None:
        """Identity, not equality of results.

        Asserting that the two agree on some values would pass just as well
        with a second copy of the algorithm sitting in ``nacha``, which is the
        thing the note in that module asked to have removed.  Identity is the
        only assertion that cannot be satisfied by a duplicate.
        """
        self.assertIs(nacha._aba_check_digit, aba_check_digit)

    def test_nacha_no_longer_carries_its_own_weights(self) -> None:
        self.assertFalse(hasattr(nacha, "_ABA_WEIGHTS"))
        self.assertEqual(cd.ABA_WEIGHTS, (3, 7, 1, 3, 7, 1, 3, 7))

    def test_nacha_entries_still_verify_their_routing_numbers(self) -> None:
        """The delegation did not change what NACHA concludes."""
        self.assertEqual(nacha._aba_check_digit("02100002"), 1)
        self.assertIsNone(nacha._aba_check_digit("0210000"))


class CoverageTests(unittest.TestCase):
    """That the dispatch table and the vocabulary cannot drift apart."""

    def test_every_identifier_kind_has_a_verifier(self) -> None:
        """Adding a member without a verifier should be caught here, not live.

        The guard inside :func:`verify` raises rather than falling through, but
        it raises at the call site — which in this system means during an
        ingestion run, over somebody's evidence.  This test moves the failure
        to where it is cheap.
        """
        self.assertEqual(set(cd._VERIFIERS), set(IdentifierKind))

    def test_a_kind_with_no_verifier_raises_rather_than_returning_a_verdict(
        self,
    ) -> None:
        """The unreachable branch, reached deliberately, because it matters.

        The test above keeps the dispatch table complete, so in a healthy tree
        this branch never runs.  That is exactly why it needs a test of its
        own: it is the code that decides what happens on the day the table
        *is* incomplete, and an untested branch there could be quietly changed
        to return a result instead of raising.  A returned result would be
        filed against the row as though a check had been performed on it.

        The table is restored in ``finally`` so a failure here cannot leak into
        the tests that follow.
        """
        original = dict(cd._VERIFIERS)
        try:
            del cd._VERIFIERS[IdentifierKind.iban]
            with self.assertRaises(CheckDigitError):
                verify(IdentifierKind.iban, "GB82WEST12345698765432")
        finally:
            cd._VERIFIERS.clear()
            cd._VERIFIERS.update(original)
        self.assertEqual(set(cd._VERIFIERS), set(IdentifierKind))

    def test_every_kind_returns_a_result_naming_itself(self) -> None:
        """No verifier may return a verdict labelled as a neighbouring kind."""
        for kind in IdentifierKind:
            with self.subTest(kind):
                result = verify(kind, "021000021")
                self.assertIsInstance(result, CheckDigitResult)
                self.assertIs(result.kind, kind)
                self.assertIsInstance(result.outcome, CheckDigitOutcome)
                self.assertIsInstance(result.checks_performed, tuple)

    def test_every_check_name_is_reachable(self) -> None:
        """A constant no result ever carries is a name for nothing."""
        seen: set[str] = set()
        for kind, value in [
            (IdentifierKind.iban, "GB82WEST12345698765432"),
            (IdentifierKind.lei, "5493001KJTIIGC8Y1R12"),
            (IdentifierKind.aba_routing, "021000021"),
            (IdentifierKind.payment_card, "4111111111111111"),
            (IdentifierKind.bic, "DEUTDEFF"),
            (IdentifierKind.us_ssn, "123456789"),
            (IdentifierKind.us_ein, "123456789"),
        ]:
            seen.update(verify(kind, value).checks_performed)
        self.assertEqual(
            seen,
            {
                CHECK_STRUCTURE,
                CHECK_ISO7064_MOD97_10,
                CHECK_ABA_WEIGHTED_MOD10,
                CHECK_LUHN_MOD10,
                CHECK_IBAN_COUNTRY_LENGTH,
                CHECK_SSN_ISSUED_RANGES,
            },
        )

    def test_a_pass_never_carries_a_detail(self) -> None:
        """Detail is the reason for a verdict, and a pass has no reason."""
        for kind, value in [
            (IdentifierKind.iban, "GB82WEST12345698765432"),
            (IdentifierKind.lei, "5493001KJTIIGC8Y1R12"),
            (IdentifierKind.aba_routing, "021000021"),
            (IdentifierKind.payment_card, "4111111111111111"),
        ]:
            with self.subTest(kind):
                result = verify(kind, value)
                self.assertIs(result.outcome, CheckDigitOutcome.passed)
                self.assertEqual(result.detail, "")

    def test_every_non_pass_carries_a_detail(self) -> None:
        """And a verdict that is not a pass always explains itself."""
        for kind, value in [
            (IdentifierKind.iban, "GB82WEST12345698765433"),
            (IdentifierKind.iban, "nonsense"),
            (IdentifierKind.lei, "5493001KJTIIGC8Y1R13"),
            (IdentifierKind.aba_routing, "021000022"),
            (IdentifierKind.payment_card, "4111111111111112"),
            (IdentifierKind.bic, "DEUTDEFF"),
            (IdentifierKind.us_ssn, "666456789"),
            (IdentifierKind.us_ein, "123456789"),
        ]:
            with self.subTest((kind, value)):
                result = verify(kind, value)
                self.assertIsNot(result.outcome, CheckDigitOutcome.passed)
                self.assertTrue(result.detail)


if __name__ == "__main__":
    unittest.main()
