"""Financial forensics: exact money handling, ledger, reconciliation and tracing.

This package is the system of record for financial evidence. Its governing
principle is that arithmetic, not model confidence, decides what is admitted:
a dropped row produces no low-confidence signal, so only a balance identity
that fails to close can detect an absence.

Nothing in this package may represent a monetary value as a float.
"""

from services.financial.adjudication import (
    Adjudication,
    AdjudicationError,
    BalanceFailure,
    Corroboration,
    MalformedVerdictError,
    UnpaidObligationError,
    restatement_delta,
)
from services.financial.bai2 import (
    BAI2_ACCOUNT_HEADER,
    BAI2_ACCOUNT_TRAILER,
    BAI2_CLOSING_LEDGER,
    BAI2_CONTINUATION,
    BAI2_CURRENCY_FROM_ACCOUNT,
    BAI2_CURRENCY_FROM_CALLER,
    BAI2_CURRENCY_FROM_GROUP,
    BAI2_FILE_HEADER,
    BAI2_FILE_TRAILER,
    BAI2_GROUP_HEADER,
    BAI2_GROUP_STATUS_CORRECTION,
    BAI2_GROUP_STATUS_DELETION,
    BAI2_GROUP_STATUS_TEST,
    BAI2_GROUP_STATUS_UPDATE,
    BAI2_GROUP_TRAILER,
    BAI2_LOCATOR,
    BAI2_MAX_FILE_BYTES,
    BAI2_OPENING_LEDGER,
    BAI2_TOTAL_CREDITS,
    BAI2_TOTAL_DEBITS,
    BAI2_TRANSACTION_DETAIL,
    BAI2_VERSION,
    Bai2Account,
    Bai2AmountError,
    Bai2BalanceIdentity,
    Bai2ControlTotal,
    Bai2CurrencyError,
    Bai2Error,
    Bai2File,
    Bai2Group,
    Bai2LogicalRecord,
    Bai2MalformedFileError,
    Bai2MissingFieldError,
    Bai2Summary,
    Bai2SummaryIdentity,
    Bai2Transaction,
    NotABai2Error,
    parse_bai2,
)
from services.financial.camt053 import (
    CAMT053_BALANCE_CLOSING_BOOKED,
    CAMT053_BALANCE_OPENING_BOOKED,
    CAMT053_BALANCE_PREVIOUSLY_CLOSED_BOOKED,
    CAMT053_LOCATOR,
    CAMT053_MAX_DOCUMENT_BYTES,
    Camt053Account,
    Camt053AmountError,
    Camt053Balance,
    Camt053BalanceIdentity,
    Camt053BatchIdentity,
    Camt053BatchTotals,
    Camt053Document,
    Camt053Entry,
    Camt053Error,
    Camt053MalformedDocumentError,
    Camt053MissingElementError,
    Camt053Statement,
    Camt053StatementCurrencyError,
    Camt053SummaryIdentity,
    Camt053TransactionDetail,
    Camt053TransactionsSummary,
    NotACamt053Error,
    parse_camt053,
)
from services.financial.check_digits import (
    ABA_WEIGHTS,
    CARD_MAX_DIGITS,
    CARD_MIN_DIGITS,
    CHECK_ABA_WEIGHTED_MOD10,
    CHECK_IBAN_COUNTRY_LENGTH,
    CHECK_ISO7064_MOD97_10,
    CHECK_LUHN_MOD10,
    CHECK_SSN_ISSUED_RANGES,
    CHECK_STRUCTURE,
    IBAN_COUNTRY_LENGTHS,
    IBAN_MAX_LENGTH,
    IBAN_MIN_LENGTH,
    CheckDigitError,
    CheckDigitResult,
    aba_check_digit,
    iso7064_mod97_10_residue,
    luhn_residue,
)

# Both of these are aliased, and for different reasons.
#
# ``normalise`` would collide outright: ``references`` exports a function of
# that name which folds Crockford's decodable confusions (I and L to 1, O to
# 0), and this one strips spaces and hyphens and upper-cases.  Imported under
# one name the later import would win silently and callers would get reference
# folding applied to an IBAN, or the reverse.
#
# ``verify`` collides with nothing today, but this package's namespace is flat
# and several hundred names wide, and a bare ``verify`` in it says nothing
# about what is being verified.  Both keep their short names inside
# :mod:`services.financial.check_digits`, where the module name supplies the
# context the package cannot.
from services.financial.check_digits import normalise as normalise_identifier
from services.financial.check_digits import verify as verify_check_digit
from services.financial.corpus import (
    HEADER_TOTALS_FIELD,
    INSTITUTION_FIELD,
    PRIVATE_PREFIX,
    TESTED_OUTCOMES,
    CorpusError,
    CorpusOutcome,
    CorpusReport,
    CorpusUnavailableError,
    Disagreement,
    DocumentReading,
    ExtractionFile,
    MalformedExtractionError,
    iter_extraction_files,
    load_corpus,
    read_extraction,
    survey,
)
from services.financial.continuity import (
    AccountContinuity,
    ContinuityError,
    ContinuityScopeError,
    ExcludedPeriod,
    ExclusionReason,
    PeriodLink,
    Seam,
    SeamAgreement,
    SeamKind,
    assess_seam,
    build_run,
    order_links,
    read_account_continuity,
)
from services.financial.dates import (
    CoverageFinding,
    DateCoherenceError,
    DateError,
    DateFinding,
    DatePlausibility,
    DateSurvey,
    RowDate,
    UngroundedDateQuarantineError,
    check_row_date,
    read_row_date,
    survey_row_dates,
)
from services.financial.decisions import (
    Actor,
    DecisionError,
    MalformedSnapshotError,
    SubjectMismatchError,
    history,
    record,
)
from services.financial.duplicates import (
    CrossCaseError,
    CrossMatterSighting,
    DocumentFingerprint,
    DuplicateError,
    DuplicateGroup,
    GroupMember,
    cross_matter_sightings,
    find_groups,
    fingerprint_document,
    nominate_primary,
    purge_document,
    resolve_duplicates,
    restore_document,
    store_fingerprint,
)
from services.financial.export_manifest import (
    DIGEST_COVERS_HTML,
    MANIFEST_SCHEMA,
    ExportManifest,
    ExportManifestError,
    describes,
    document_digest,
    manifest_for,
)
from services.financial.locators import (
    MILLIPOINTS_PER_POINT,
    Locator,
    LocatorCoherenceError,
    LocatorError,
    RectangleError,
    SourceRectangle,
    capture,
)
from services.financial.money import (
    AmbiguousAmountError,
    Currency,
    CurrencyMismatchError,
    Money,
    MoneyError,
    MoneyParseError,
    ParsedAmount,
    PrecisionError,
    UnknownCurrencyError,
    get_currency,
    parse_amount,
    parse_money,
    sum_money,
)
from services.financial.mt940 import (
    MT940_ACCOUNT_IDENTIFICATION,
    MT940_BALANCE_CREDIT,
    MT940_BALANCE_DEBIT,
    MT940_BALANCE_FINAL,
    MT940_BALANCE_INTERMEDIATE,
    MT940_CLOSING_AVAILABLE_BALANCE,
    MT940_CLOSING_BALANCE,
    MT940_FORWARD_AVAILABLE_BALANCE,
    MT940_INFORMATION,
    MT940_LINE_MARKS,
    MT940_LOCATOR,
    MT940_MAX_FILE_BYTES,
    MT940_NO_REFERENCE,
    MT940_OPENING_BALANCE,
    MT940_RELATED_REFERENCE,
    MT940_REVERSAL_MARKS,
    MT940_STATEMENT_LINE,
    MT940_STATEMENT_NUMBER,
    MT940_TRANSACTION_REFERENCE,
    Mt940AmountError,
    Mt940Balance,
    Mt940BalanceIdentity,
    Mt940CurrencyError,
    Mt940Error,
    Mt940File,
    Mt940MalformedFileError,
    Mt940MissingFieldError,
    Mt940Statement,
    Mt940StatementLine,
    Mt940Tag,
    NotAnMt940Error,
    parse_mt940,
)
from services.financial.nacha import (
    NACHA_ADDENDA,
    NACHA_ADDENDA_NOTIFICATION_OF_CHANGE,
    NACHA_ADDENDA_PAYMENT_INFORMATION,
    NACHA_ADDENDA_RETURN,
    NACHA_BATCH_CONTROL,
    NACHA_BATCH_HEADER,
    NACHA_BLOCKING_FACTOR,
    NACHA_CURRENCY,
    NACHA_ENTRY_DETAIL,
    NACHA_ENTRY_HASH_DIGITS,
    NACHA_FILE_CONTROL,
    NACHA_FILE_HEADER,
    NACHA_FORMAT_CODE,
    NACHA_LOCATOR,
    NACHA_MAX_FILE_BYTES,
    NACHA_PRENOTIFICATION_CODES,
    NACHA_RECORD_LENGTH,
    NACHA_RECORD_SIZE,
    NACHA_RETURN_OR_NOC_CODES,
    NACHA_SEC_CORPORATE_TRADE_EXCHANGE,
    NACHA_SEC_INTERNATIONAL,
    NACHA_SERVICE_CLASS_ADVICES,
    NACHA_SERVICE_CLASS_CODES,
    NACHA_SERVICE_CLASS_CREDITS_ONLY,
    NACHA_SERVICE_CLASS_DEBITS_ONLY,
    NACHA_SERVICE_CLASS_MIXED,
    NACHA_TRANSACTION_CODE_DIRECTIONS,
    NachaAddenda,
    NachaAmountError,
    NachaBatch,
    NachaControlTotal,
    NachaEntry,
    NachaError,
    NachaFile,
    NachaMalformedFileError,
    NachaMissingFieldError,
    NachaRecord,
    NotANachaError,
    parse_nacha,
)
from services.financial.native import (
    CENTURY_WINDOW_MAX_SPAN_YEARS,
    NATIVE_LOCATORS,
    PARSER_FINGERPRINT_CHARS,
    SNIFF_BYTES,
    AmbiguousFormatError,
    CenturyWindow,
    CenturyWindowError,
    DateResolutionError,
    NativeError,
    NativeFormat,
    NativeReading,
    NativeRow,
    UnmappedRow,
    UnrecognisedFormatError,
    detect_format,
    parser_name,
    parser_version,
    read_native,
    resolve_mmdd_near,
    sniff,
)
from services.financial.periods import (
    BalanceCoherenceError,
    BalanceObservation,
    PeriodBounds,
    PeriodBoundsError,
    PeriodCurrencyError,
    PeriodError,
    StatementPeriodDraft,
    read_bounds,
    read_closing,
    read_opening,
    record_statement_period,
)
from services.financial.pdf_tables import (
    TABLE_COORDINATE_SPACE,
    ExtractedTable,
    GeometrySource,
    chunks_of,
    geometry_summary,
    read_tables,
)
from services.financial.proof_class import (
    AUTO_ADMITTED_CLASSES,
    DEFAULT_TOTAL_CLASSES,
    LEDGER_CLASSES,
    ProofClassError,
    SourceShape,
    UnclassifiableSourceError,
    admits_automatically,
    assign_proof_class,
    counts_toward_totals,
    from_legacy_strength,
    may_produce_ledger_rows,
    requires_adjudication,
)
from services.financial.quarantine import (
    BalanceBreak,
    Candidate,
    CandidateKind,
    Localisation,
    LocalisationError,
    LocalisationStrength,
    QuarantineBasis,
    QuarantineError,
    RescueWarning,
    RowObservation,
    Signature,
    UngroundedQuarantineError,
    localise,
    quarantine_transaction,
    quarantined_row_ids,
    release_transaction,
    would_rescue,
)
from services.financial.reconcile import (
    IdentityOutcome,
    LedgerOverflowError,
    MixedCurrencyError,
    ReconciliationError,
    TransactionTotals,
    empty_totals,
    evaluate_identity,
    reconcile_period,
    total_transactions,
)
from services.financial.references import (
    REFERENCE_LENGTH,
    REFERENCE_PREFIX,
    MalformedReadingError,
    MalformedReferenceError,
    RowReading,
    RowReferenceError,
    canonical_form,
    content_hash,
    document_content_hashes,
    document_ref_ids,
    is_reference,
    normalise,
    ref_id,
)
from services.financial.runs import (
    IngestionRunHandle,
    RunAborted,
    RunCounts,
    RunError,
    RunScopeError,
    ingestion_run,
    open_ingestion_run,
    reap_stale_runs,
)
from services.financial.statement_totals import (
    CANDIDATE_CONVENTIONS,
    FIELD_ALIASES,
    INFLOW_ROLES,
    OUTFLOW_ROLES,
    ConventionError,
    ConventionInference,
    FigureReading,
    HeaderIdentityOutcome,
    HeaderTotals,
    StatementTotalsError,
    TotalsRole,
    UnreadableFigureError,
    check_header_identity,
    figure_to_money,
    infer_convention,
    is_figure,
    read_header_totals,
)
from services.financial.table_geometry import (
    CELL_OVERFLOW_TOLERANCE_MILLIPOINTS,
    LocatedCell,
    LocatedTable,
    TableGeometryError,
    cell_value,
    locate_table,
)
from services.financial.version import (
    PIPELINE_VERSION,
    code_fingerprint_detail,
    code_version,
    ruleset_version,
)

__all__ = [
    # Adjudication of failing balance identities
    "Adjudication",
    "AdjudicationError",
    "BalanceFailure",
    "Corroboration",
    "MalformedVerdictError",
    "UnpaidObligationError",
    "restatement_delta",
    # BAI2, read natively.  The second shape that can reach P0 unaided, and the
    # reason the camt.053 names were prefixed: these are its account, its
    # balance and its transaction, and neither parser gets the bare words.
    "BAI2_ACCOUNT_HEADER",
    "BAI2_ACCOUNT_TRAILER",
    "BAI2_CLOSING_LEDGER",
    "BAI2_CONTINUATION",
    "BAI2_CURRENCY_FROM_ACCOUNT",
    "BAI2_CURRENCY_FROM_CALLER",
    "BAI2_CURRENCY_FROM_GROUP",
    "BAI2_FILE_HEADER",
    "BAI2_FILE_TRAILER",
    "BAI2_GROUP_HEADER",
    "BAI2_GROUP_STATUS_CORRECTION",
    "BAI2_GROUP_STATUS_DELETION",
    "BAI2_GROUP_STATUS_TEST",
    "BAI2_GROUP_STATUS_UPDATE",
    "BAI2_GROUP_TRAILER",
    "BAI2_LOCATOR",
    "BAI2_MAX_FILE_BYTES",
    "BAI2_OPENING_LEDGER",
    "BAI2_TOTAL_CREDITS",
    "BAI2_TOTAL_DEBITS",
    "BAI2_TRANSACTION_DETAIL",
    "BAI2_VERSION",
    "Bai2Account",
    "Bai2AmountError",
    "Bai2BalanceIdentity",
    "Bai2ControlTotal",
    "Bai2CurrencyError",
    "Bai2Error",
    "Bai2File",
    "Bai2Group",
    "Bai2LogicalRecord",
    "Bai2MalformedFileError",
    "Bai2MissingFieldError",
    "Bai2Summary",
    "Bai2SummaryIdentity",
    "Bai2Transaction",
    "NotABai2Error",
    "parse_bai2",
    # camt.053, read natively: the first shape that can reach P0 unaided.
    # Every name is prefixed because BAI2, MT940 and NACHA each have their own
    # account, balance, entry and statement, and the package would otherwise
    # have to award those four words to whichever parser was written first.
    "CAMT053_BALANCE_CLOSING_BOOKED",
    "CAMT053_BALANCE_OPENING_BOOKED",
    "CAMT053_BALANCE_PREVIOUSLY_CLOSED_BOOKED",
    "CAMT053_LOCATOR",
    "CAMT053_MAX_DOCUMENT_BYTES",
    "Camt053Account",
    "Camt053AmountError",
    "Camt053Balance",
    "Camt053BalanceIdentity",
    "Camt053BatchIdentity",
    "Camt053BatchTotals",
    "Camt053Document",
    "Camt053Entry",
    "Camt053Error",
    "Camt053MalformedDocumentError",
    "Camt053MissingElementError",
    "Camt053Statement",
    "Camt053StatementCurrencyError",
    "Camt053SummaryIdentity",
    "Camt053TransactionDetail",
    "Camt053TransactionsSummary",
    "NotACamt053Error",
    "parse_camt053",
    # Field-level check digits: does a number agree with itself
    "ABA_WEIGHTS",
    "CARD_MAX_DIGITS",
    "CARD_MIN_DIGITS",
    "CHECK_ABA_WEIGHTED_MOD10",
    "CHECK_IBAN_COUNTRY_LENGTH",
    "CHECK_ISO7064_MOD97_10",
    "CHECK_LUHN_MOD10",
    "CHECK_SSN_ISSUED_RANGES",
    "CHECK_STRUCTURE",
    "IBAN_COUNTRY_LENGTHS",
    "IBAN_MAX_LENGTH",
    "IBAN_MIN_LENGTH",
    "CheckDigitError",
    "CheckDigitResult",
    "aba_check_digit",
    "iso7064_mod97_10_residue",
    "luhn_residue",
    "normalise_identifier",
    "verify_check_digit",
    # Measuring the reader against the corpus it is supposed to read
    "HEADER_TOTALS_FIELD",
    "INSTITUTION_FIELD",
    "PRIVATE_PREFIX",
    "TESTED_OUTCOMES",
    "CorpusError",
    "CorpusOutcome",
    "CorpusReport",
    "CorpusUnavailableError",
    "Disagreement",
    "DocumentReading",
    "ExtractionFile",
    "MalformedExtractionError",
    "iter_extraction_files",
    "load_corpus",
    "read_extraction",
    "survey",
    # Continuity across statement periods
    "AccountContinuity",
    "ContinuityError",
    "ContinuityScopeError",
    "ExcludedPeriod",
    "ExclusionReason",
    "PeriodLink",
    "Seam",
    "SeamAgreement",
    "SeamKind",
    "assess_seam",
    "build_run",
    "order_links",
    "read_account_continuity",
    # Whether a row's date can be believed, and what a disagreement proves
    "CoverageFinding",
    "DateCoherenceError",
    "DateError",
    "DateFinding",
    "DatePlausibility",
    "DateSurvey",
    "RowDate",
    "UngroundedDateQuarantineError",
    "check_row_date",
    "read_row_date",
    "survey_row_dates",
    # Decisions, appended before the state they describe changes
    "Actor",
    "DecisionError",
    "MalformedSnapshotError",
    "SubjectMismatchError",
    "history",
    "record",
    # Duplicate documents
    "CrossCaseError",
    "CrossMatterSighting",
    "DocumentFingerprint",
    "DuplicateError",
    "DuplicateGroup",
    "GroupMember",
    "cross_matter_sightings",
    "find_groups",
    "fingerprint_document",
    "nominate_primary",
    "purge_document",
    "resolve_duplicates",
    "restore_document",
    "store_fingerprint",
    # What was exported, and the separate record of when it was exported
    "DIGEST_COVERS_HTML",
    "MANIFEST_SCHEMA",
    "ExportManifest",
    "ExportManifestError",
    "describes",
    "document_digest",
    "manifest_for",
    # Where on a page a value was read from, in one declared coordinate space
    "MILLIPOINTS_PER_POINT",
    "Locator",
    "LocatorCoherenceError",
    "LocatorError",
    "RectangleError",
    "SourceRectangle",
    "capture",
    # Money
    "AmbiguousAmountError",
    "Currency",
    "CurrencyMismatchError",
    "Money",
    "MoneyError",
    "MoneyParseError",
    "ParsedAmount",
    "PrecisionError",
    "UnknownCurrencyError",
    "get_currency",
    "parse_amount",
    "parse_money",
    "sum_money",
    # MT940, read natively.  Structured and bank-originated like the two
    # above, but carrying no control total of any kind — no record count, no
    # entry count, no declared credit or debit total — so a clean message
    # earns P1 rather than P0.  See the module docstring for why that costs
    # nothing operationally and why claiming P0 here would cost a great deal.
    "MT940_ACCOUNT_IDENTIFICATION",
    "MT940_BALANCE_CREDIT",
    "MT940_BALANCE_DEBIT",
    "MT940_BALANCE_FINAL",
    "MT940_BALANCE_INTERMEDIATE",
    "MT940_CLOSING_AVAILABLE_BALANCE",
    "MT940_CLOSING_BALANCE",
    "MT940_FORWARD_AVAILABLE_BALANCE",
    "MT940_INFORMATION",
    "MT940_LINE_MARKS",
    "MT940_LOCATOR",
    "MT940_MAX_FILE_BYTES",
    "MT940_NO_REFERENCE",
    "MT940_OPENING_BALANCE",
    "MT940_RELATED_REFERENCE",
    "MT940_REVERSAL_MARKS",
    "MT940_STATEMENT_LINE",
    "MT940_STATEMENT_NUMBER",
    "MT940_TRANSACTION_REFERENCE",
    "Mt940AmountError",
    "Mt940Balance",
    "Mt940BalanceIdentity",
    "Mt940CurrencyError",
    "Mt940Error",
    "Mt940File",
    "Mt940MalformedFileError",
    "Mt940MissingFieldError",
    "Mt940Statement",
    "Mt940StatementLine",
    "Mt940Tag",
    "NotAnMt940Error",
    "parse_mt940",
    # NACHA, read natively: the only one of the four that states debits and
    # credits separately, so a direction error cannot cancel itself out.
    "NACHA_ADDENDA",
    "NACHA_ADDENDA_NOTIFICATION_OF_CHANGE",
    "NACHA_ADDENDA_PAYMENT_INFORMATION",
    "NACHA_ADDENDA_RETURN",
    "NACHA_BATCH_CONTROL",
    "NACHA_BATCH_HEADER",
    "NACHA_BLOCKING_FACTOR",
    "NACHA_CURRENCY",
    "NACHA_ENTRY_DETAIL",
    "NACHA_ENTRY_HASH_DIGITS",
    "NACHA_FILE_CONTROL",
    "NACHA_FILE_HEADER",
    "NACHA_FORMAT_CODE",
    "NACHA_LOCATOR",
    "NACHA_MAX_FILE_BYTES",
    "NACHA_PRENOTIFICATION_CODES",
    "NACHA_RECORD_LENGTH",
    "NACHA_RECORD_SIZE",
    "NACHA_RETURN_OR_NOC_CODES",
    "NACHA_SEC_CORPORATE_TRADE_EXCHANGE",
    "NACHA_SEC_INTERNATIONAL",
    "NACHA_SERVICE_CLASS_ADVICES",
    "NACHA_SERVICE_CLASS_CODES",
    "NACHA_SERVICE_CLASS_CREDITS_ONLY",
    "NACHA_SERVICE_CLASS_DEBITS_ONLY",
    "NACHA_SERVICE_CLASS_MIXED",
    "NACHA_TRANSACTION_CODE_DIRECTIONS",
    "NachaAddenda",
    "NachaAmountError",
    "NachaBatch",
    "NachaControlTotal",
    "NachaEntry",
    "NachaError",
    "NachaFile",
    "NachaMalformedFileError",
    "NachaMissingFieldError",
    "NachaRecord",
    "NotANachaError",
    "parse_nacha",
    # Layer 0: the four native parsers above read behind one door, and the
    # ledger-shaped rows they yield.  A row that reaches the ledger this way
    # records that it was read from the format's own structure rather than
    # recovered from a rendering of it, which is the whole of the difference
    # between a value a court can trace to the bank and one it can trace to an
    # extractor's guess.
    "CENTURY_WINDOW_MAX_SPAN_YEARS",
    "NATIVE_LOCATORS",
    "PARSER_FINGERPRINT_CHARS",
    "SNIFF_BYTES",
    "AmbiguousFormatError",
    "CenturyWindow",
    "CenturyWindowError",
    "DateResolutionError",
    "NativeError",
    "NativeFormat",
    "NativeReading",
    "NativeRow",
    "UnmappedRow",
    "UnrecognisedFormatError",
    "detect_format",
    "parser_name",
    "parser_version",
    "read_native",
    "resolve_mmdd_near",
    "sniff",
    # Statement periods and the provenance of their four values
    "BalanceCoherenceError",
    "BalanceObservation",
    "PeriodBounds",
    "PeriodBoundsError",
    "PeriodCurrencyError",
    "PeriodError",
    "StatementPeriodDraft",
    "read_bounds",
    "read_closing",
    "read_opening",
    "record_statement_period",
    # Reading a page's tables once, so text and geometry cannot disagree
    "TABLE_COORDINATE_SPACE",
    "ExtractedTable",
    "GeometrySource",
    "chunks_of",
    "geometry_summary",
    "read_tables",
    # The proof class a source earns, and what each class licenses
    "AUTO_ADMITTED_CLASSES",
    "DEFAULT_TOTAL_CLASSES",
    "LEDGER_CLASSES",
    "ProofClassError",
    "SourceShape",
    "UnclassifiableSourceError",
    "admits_automatically",
    "assign_proof_class",
    "counts_toward_totals",
    "from_legacy_strength",
    "may_produce_ledger_rows",
    "requires_adjudication",
    # Where a failing identity broke, and on what grounds a row is set aside
    "BalanceBreak",
    "Candidate",
    "CandidateKind",
    "Localisation",
    "LocalisationError",
    "LocalisationStrength",
    "QuarantineBasis",
    "QuarantineError",
    "RescueWarning",
    "RowObservation",
    "Signature",
    "UngroundedQuarantineError",
    "localise",
    "quarantine_transaction",
    "quarantined_row_ids",
    "release_transaction",
    "would_rescue",
    # The balance identity
    "IdentityOutcome",
    "LedgerOverflowError",
    "MixedCurrencyError",
    "ReconciliationError",
    "TransactionTotals",
    "empty_totals",
    "evaluate_identity",
    "reconcile_period",
    "total_transactions",
    # What a row's reading is, and the reference a reader cites it by
    "MalformedReadingError",
    "MalformedReferenceError",
    "REFERENCE_LENGTH",
    "REFERENCE_PREFIX",
    "RowReading",
    "RowReferenceError",
    "canonical_form",
    "content_hash",
    "document_content_hashes",
    "document_ref_ids",
    "is_reference",
    "normalise",
    "ref_id",
    # Run identity
    "IngestionRunHandle",
    "RunAborted",
    "RunCounts",
    "RunError",
    "RunScopeError",
    "ingestion_run",
    "open_ingestion_run",
    "reap_stale_runs",
    # The statement's own printed control totals, and which dialect they are in
    "CANDIDATE_CONVENTIONS",
    "FIELD_ALIASES",
    "INFLOW_ROLES",
    "OUTFLOW_ROLES",
    "ConventionError",
    "ConventionInference",
    "FigureReading",
    "HeaderIdentityOutcome",
    "HeaderTotals",
    "StatementTotalsError",
    "TotalsRole",
    "UnreadableFigureError",
    "check_header_identity",
    "figure_to_money",
    "infer_convention",
    "is_figure",
    "read_header_totals",
    # Pairing each value in an extracted table with the rectangle it came from
    "CELL_OVERFLOW_TOLERANCE_MILLIPOINTS",
    "LocatedCell",
    "LocatedTable",
    "TableGeometryError",
    "cell_value",
    "locate_table",
    # Code and ruleset identity
    "PIPELINE_VERSION",
    "code_fingerprint_detail",
    "code_version",
    "ruleset_version",
]
