// Read-only connected graph and group-flow check over the existing synthetic case.
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),{chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const fixture=JSON.parse(fs.readFileSync(path.join(root,'data/local-runtime/backward-review-check.json')));const browser=await chromium.launch({headless:true});let page;try{
 page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(30000);let writes=0;const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/financial/**',async route=>{if(!['GET','HEAD'].includes(route.request().method())&&!route.request().url().includes('/ledger-transfer-scenario?')){writes++;await route.abort()}else await route.continue()});
 await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));
 await page.goto(`http://127.0.0.1:55174/cases/${fixture.case_id}/financial`);await page.getByRole('tab',{name:'Transfers',exact:true}).click();await page.getByLabel('Transfer date tolerance',{exact:true}).selectOption('7');const loaded=page.waitForResponse(r=>r.url().includes('/ledger-transfer-candidates?'));await page.getByRole('button',{name:'Find possible transfers',exact:true}).click();const scope=await(await loaded).json();for(const pair of fixture.pairs){const index=scope.candidates.findIndex(p=>p.debit_id===pair.debit_id&&p.credit_id===pair.credit_id);if(index<0)throw Error('Expected pair missing');await page.getByLabel(`Pair transfer ${index+1}`,{exact:true}).check()}
 await page.getByLabel('Basis for transfer pairings',{exact:true}).fill('Synthetic explicitly selected pairs, including earlier receiving date; diagram is a hypothesis, not a causal or ownership conclusion.');const calculated=page.waitForResponse(r=>r.url().includes('/ledger-transfer-scenario?'));await page.getByRole('button',{name:'Calculate paired movement scenario',exact:true}).click();const response=await calculated;if(!response.ok())throw Error(await response.text());
 await page.getByRole('button',{name:'Show transfer relationship graph',exact:true}).click();const graph=page.getByRole('region',{name:'Calculated transfer relationships',exact:true});await graph.locator('canvas').waitFor();await graph.getByText(/3 accounts connected by 2 explicitly paired movements/).waitFor();await page.getByLabel('Inspect connected account',{exact:true}).selectOption(fixture.account_ids[1]);await graph.getByText('2 paired movements match this graph selection.',{exact:true}).waitFor();await page.getByLabel('Inspect connected account',{exact:true}).selectOption(fixture.account_ids[0]);await graph.getByText('1 paired movements match this graph selection.',{exact:true}).waitFor();
 for(const [side,id] of [['outgoing',fixture.pairs[0].debit_id],['incoming',fixture.pairs[0].credit_id]]){const opened=page.waitForResponse(r=>r.url().includes('/source?'));await graph.getByRole('button',{name:`Inspect paired ${side} ${id.slice(0,8)}`,exact:true}).click();const source=await opened;if(!source.ok()||(await source.json()).transaction_id!==id)throw Error('Wrong paired source');await page.keyboard.press('Escape')}
 await graph.getByRole('button',{name:'Show all paired movements',exact:true}).click();await graph.scrollIntoViewIfNeeded();await graph.getByRole('button',{name:'Fit graph',exact:true}).click();await page.waitForTimeout(400);await page.screenshot({path:'/tmp/loupe-connected-transfer-graph.png'});
 const perspective=page.getByRole('region',{name:'Account flow perspective',exact:true});for(const id of fixture.account_ids){const row=scope.rows.find(r=>r.account_id===id);await perspective.getByLabel(`Include account ${row.account_label}`,{exact:true}).check()}
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download account perspective and assumptions',exact:true}).click();const file=path.join(root,'data/local-runtime/connected-transfer-perspective.json');await(await download).saveAs(file);const captured=JSON.parse(fs.readFileSync(file));const total=captured.result.totals.find(t=>t.currency==='GBP');if(total.internal_minor!=='16000'||total.internal_count!==2||total.incoming_minor!=='20000'||total.outgoing_minor!=='2000'||total.net_minor!=='18000')throw Error('Group counts differ '+JSON.stringify(total));
 const chart=perspective.getByRole('region',{name:'Account group external flow',exact:true});await chart.getByRole('button',{name:'Inspect selected chart totals',exact:true}).click();await chart.getByText('Selected chart totals · 3 postings',{exact:true}).waitFor();const totalSource=page.waitForResponse(r=>r.url().includes('/source?'));await chart.getByRole('button',{name:'Open chart posting 1',exact:true}).click();const totalResponse=await totalSource;if(!totalResponse.ok())throw Error('Chart total source failed');await page.keyboard.press('Escape');
 if(writes||errors.length)throw Error(JSON.stringify({writes,errors}));const report={case_id:fixture.case_id,synthetic:true,connected_accounts:3,paired_movements:2,both_sources_verified:true,selected_total_sources_verified:true,group_totals:total,download_verified:true,financial_writes:writes};fs.writeFileSync(path.join(root,'data/local-runtime/connected-transfer-graph-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }catch(e){if(page){await page.screenshot({path:'/tmp/loupe-transfer-graph-failure.png'});fs.writeFileSync('/tmp/loupe-transfer-graph-failure.txt',await page.locator('body').innerText())}throw e}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
