// Read-only financial calculation; the separately seeded case is synthetic.
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');const {chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const fixture=JSON.parse(fs.readFileSync(path.join(root,'data/local-runtime/transfer-review-check.json')));if(fixture.status!=='ready')throw Error('Fixture not ready');const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1600,height:1100}});let writes=0;await page.route('**/api/financial/**',async route=>{if(!['GET','HEAD'].includes(route.request().method())&&!route.request().url().includes('/ledger-transfer-scenario?')){writes++;await route.abort()}else await route.continue()});
 await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));
 await page.goto(`http://127.0.0.1:55174/cases/${fixture.case_id}/financial`);await page.getByRole('tab',{name:'Transfers',exact:true}).click();await page.getByRole('button',{name:'Find possible transfers',exact:true}).click();await page.getByLabel('Pair transfer 1',{exact:true}).check();
 await page.getByLabel('Basis for transfer pairings',{exact:true}).fill('Synthetic local acceptance only: deliberately seeded debit and credit in two accounts. This tests conditional counting, not a real transfer conclusion.');
 const calculated=page.waitForResponse(r=>r.url().includes('/ledger-transfer-scenario?'));await page.getByRole('button',{name:'Calculate paired movement scenario',exact:true}).click();const response=await calculated;const data=await response.json();if(!response.ok()||data.figures[0].movement_count!==1||data.figures[0].paired_amount_minor!==fixture.amount_minor)throw Error('Pairing failed '+JSON.stringify(data));
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download scenario with source references',exact:true}).click();await(await download).saveAs(path.join(root,'data/local-runtime/transfer-scenario.json'));
 await page.getByRole('region',{name:'Paired transfer scenario',exact:true}).screenshot({path:'/tmp/loupe-transfer-scenario.png'});
 await page.getByLabel('Transfer population',{exact:true}).selectOption('verified');await page.getByRole('button',{name:'Find possible transfers',exact:true}).click();await page.getByText('No matching pair in this scope. Missing evidence, currencies or timing may prevent a match.',{exact:true}).waitFor();if(writes)throw Error('Unexpected write');
 console.log(JSON.stringify({case_id:fixture.case_id,postings:2,scenario_movements:1,exact_amount:fixture.amount_minor,verified_population_empty:true,scenario_downloaded:true,financial_writes:writes}));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
