// Read-only conditional scenario over the existing labelled synthetic coverage case.
const path=require('path'),fs=require('fs'),crypto=require('crypto');
const root=path.resolve(__dirname,'..');
const {chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
const partial=process.argv.includes('--partial');
(async()=>{
 const caseId='3dfbafe7-fa6b-4bdd-9af5-0e97975447b9',accountId='43e04760-190e-4183-aa1c-eb55334e8aaf';
 const browser=await chromium.launch({headless:true});
 let page;
 try{
  page=await browser.newPage({viewport:{width:1440,height:1200}});page.setDefaultTimeout(20000);
  let writes=0;await page.route('**/api/financial/**',async route=>{if(!['GET','HEAD'].includes(route.request().method())&&!route.request().url().includes('/ledger-trace?')){writes++;await route.abort()}else await route.continue()});
  await page.goto('http://127.0.0.1:55174/login');
  await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');
  await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));
  await page.goto(`http://127.0.0.1:55174/cases/${caseId}/financial`);
  await page.getByRole('tab',{name:'Conditional tracing',exact:true}).click();
  if(!await page.getByRole('button',{name:'Load tracing inputs',exact:true}).isDisabled())throw Error('Unscoped load enabled');
  const headers={Authorization:`Bearer ${await page.evaluate(()=>localStorage.getItem('authToken'))}`};
  const accounts=await (await page.request.get(`http://127.0.0.1:58002/api/financial/ledger-accounts?case_id=${caseId}`,{headers})).json();
  const account=accounts.items.find(a=>a.id===accountId);if(!account)throw Error('Missing synthetic account');
  const label=[account.display_label,account.identifier,account.holder,account.institution,account.currency].filter(Boolean).join(' · ')||account.id;
  await page.getByRole('button',{name:'Find accounts',exact:true}).click();
  await page.getByRole('button',{name:`Select ${label}${account.provisional?' (provisional identity)':''}`,exact:true}).click();
  await page.getByLabel('Ordering date from',{exact:true}).fill('2026-01-01');
  await page.getByLabel('Ordering date through',{exact:true}).fill('2026-01-31');
  await page.getByRole('button',{name:'Apply ledger filters',exact:true}).click();
  await page.getByLabel('Tracing population',{exact:true}).selectOption('working');
  const inputsResponse=page.waitForResponse(r=>r.url().includes("/ledger-trace-inputs?"));
  await page.getByRole('button',{name:'Load tracing inputs',exact:true}).click();
  const capturedInputs=await (await inputsResponse).json();
  await page.getByText('Record your scenario assumptions',{exact:true}).waitFor();
  await page.getByLabel('Opening balance (GBP)',{exact:true}).fill('0');
  await page.getByLabel('Opening balance basis',{exact:true}).fill('Synthetic acceptance assumption: no opening funds.');
  await page.getByLabel('Basis for accepting this movement order',{exact:true}).fill('Synthetic acceptance: displayed same-day order assumed, not bank-verified.');
  const deposit=page.getByLabel('Attributed deposit',{exact:true});
  await deposit.selectOption(capturedInputs.readings.find(r=>r.row.direction==='credit').row.key);
  await page.getByLabel('Claim label',{exact:true}).fill('synthetic-claim');
  await page.getByLabel('Attributed amount (GBP)',{exact:true}).fill('60.00');
  await page.getByLabel('Attribution basis',{exact:true}).fill('Synthetic test attribution only.');
  await page.getByRole('button',{name:'Add asset interpretation',exact:true}).click();
  await page.getByLabel('Asset withdrawal 1',{exact:true}).selectOption('d270ac84-f7bc-41f5-ab30-858ec4a6894c');
  await page.getByLabel('Asset description 1',{exact:true}).fill('Synthetic equipment');
  await page.getByLabel('Asset basis 1',{exact:true}).fill('Synthetic whole-payment hypothesis.');
  if(partial){await page.getByLabel('Use a proportional part of withdrawal 1',{exact:true}).check();await page.getByLabel('Asset purchase amount 1',{exact:true}).fill('12.00');await page.getByLabel('Asset basis 1',{exact:true}).fill('Synthetic purchase portion: explicitly assume proportional allocation of12of20GBP.');}
  await page.getByLabel('first in first out',{exact:true}).check();
  const responsePromise=page.waitForResponse(r=>r.url().includes('/ledger-trace?')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Calculate conditional scenario',exact:true}).click();
  const response=await responsePromise;const envelope=await response.json();if(!response.ok())throw Error(JSON.stringify(envelope));
  await page.getByRole('region',{name:'Conditional tracing results',exact:true}).waitFor();
  const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download conditional scenario',exact:true}).click();
  const destination=path.join(root,`data/local-runtime/${partial?'partial-':''}conditional-trace-asset-check.json`);await (await pending).saveAs(destination);
  const bytes=fs.readFileSync(destination),scenario=JSON.parse(bytes);
  if(crypto.createHash('sha256').update(bytes).digest('hex')!==envelope.scenario_sha256||bytes.length!==envelope.scenario_byte_count)throw Error('Downloaded bytes differ');
  if(scenario.comparison.results.first_in_first_out.outcomes['synthetic-claim'].surviving.minor_units!=='4000')throw Error('Unexpected conditional result');
  const asset=scenario.asset_uses.first_in_first_out[0];
  if(asset.allocated_by_claim['synthetic-claim']!==(partial?'1200':'2000')||asset.outside_claims_minor!=='0')throw Error('Asset allocation differs');
  if(partial&&(asset.asset_amount_minor!=='1200'||asset.remaining_withdrawal_minor!=='800'||asset.allocation_basis!=='proportional_share'))throw Error('Partial assumption differs');
  const source=page.waitForResponse(r=>r.url().includes('/source?'));await page.getByRole('button',{name:'Inspect asset payment 1',exact:true}).click();
  const sourceResponse=await source;if(!sourceResponse.ok()||(await sourceResponse.json()).transaction_id!==asset.transaction_id)throw Error('Asset source differs');await page.keyboard.press('Escape');
  await page.screenshot({path:`/tmp/loupe-${partial?'partial-':''}single-asset-ui.png`,fullPage:true});
  await page.getByLabel('Attributed amount (GBP)',{exact:true}).fill('1.01');
  if(await page.getByRole('region',{name:'Conditional tracing results',exact:true}).count())throw Error('Stale result survived changed assumptions');
  if(writes)throw Error("Unexpected financial write");
  const report={partial,asset_use_verified:true,source_verified:true,financial_writes:writes,case_id:caseId,account_id:accountId,included_rows:scenario.ledger_snapshot.ledger.included_rows,download_sha256:envelope.scenario_sha256,exact_download:true,assumption_change_clears_result:true,applied:scenario.applied};
  fs.writeFileSync(path.join(root,`data/local-runtime/${partial?'partial-':''}conditional-trace-asset-ui-check.json`),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }catch(error){ if(page){ await page.screenshot({path:"/tmp/loupe-single-asset-failure.png"});fs.writeFileSync("/tmp/loupe-single-asset-failure.txt",await page.locator("body").innerText()); } throw error; }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
