// Guarded real-PDF pending-review queue. Never finalize or rerun the writer.
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),{chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
const output=path.join(root,'data/local-runtime/scanned-queue-ui-check.json'),readOnly=process.argv.includes('--read-only');
(async()=>{if(fs.existsSync(output)&&!readOnly)throw Error('Queue checkpoint exists; inspect it and use --read-only');const caseId='3db2ae11-da7f-405a-a087-b465bdc9f12d',fileId='a31e783e-84f8-415b-9d43-b0c481acc43e';let report=readOnly?JSON.parse(fs.readFileSync(output)):{case_id:caseId,evidence_file_id:fileId,status:'not_started',mappings:[]};const persist=()=>fs.writeFileSync(output,JSON.stringify(report,null,2));const browser=await chromium.launch({headless:true});let page;try{
 page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(30000);let mappingWrites=0,otherWrites=0;const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/financial/**',async route=>{const request=route.request();if(['GET','HEAD'].includes(request.method())){await route.continue();return}const body=request.postDataJSON();if(readOnly||request.method()!=='POST'||!request.url().includes('/candidate-mappings?')||body.case_id!==caseId||body.evidence_file_id!==fileId||![4,6,10].includes(body.page_number)){otherWrites++;await route.abort();return}mappingWrites++;const response=await route.fetch();const data=await response.json();if(response.ok()){report.mappings.push({page:body.page_number,id:data.id,rows:data.candidates.length,candidate_ids:data.candidates.map(c=>c.id)});persist()}else{report.failure_status=response.status();persist()}await route.fulfill({response});});
 await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));const headers={Authorization:`Bearer ${await page.evaluate(()=>localStorage.getItem('authToken'))}`};
 await page.goto(`http://127.0.0.1:55174/cases/${caseId}/financial`);await page.getByRole('button',{name:'Open PDF readings',exact:true}).click();
 if(!readOnly){await page.getByRole('button',{name:'Choose PDF rows',exact:true}).click();await page.getByRole('button',{name:/ · page 4$/}).click();await page.getByRole('button',{name:'Find possible rows across PDF pages',exact:true}).click();await page.getByLabel('Propose columns on each page',{exact:true}).check();await page.getByLabel('Scan from page',{exact:true}).fill('4');await page.getByLabel('Scan through page',{exact:true}).fill('10');await page.getByLabel('Scan currency',{exact:true}).fill('USD');await page.getByRole('button',{name:'Scan selected page range',exact:true}).click();const queue=page.getByRole('region',{name:'Queue scanned PDF readings',exact:true});await queue.waitFor();await queue.getByLabel('Include undated fee and interest proposals, with dates unresolved',{exact:true}).check();for(const number of [4,6,10])await queue.getByLabel(`Queue proposals on page ${number}`,{exact:true}).check();await queue.getByText('7 possible rows on 3 selected pages. Unchecked pages and unselected rows stay outside this queue.',{exact:true}).waitFor();report.status='write_started';persist();await queue.getByRole('button',{name:'Add selected scan proposals to review',exact:true}).click();await queue.getByText(/Selected proposals are available in PDF readings/).waitFor();if(report.mappings.length!==3||mappingWrites!==3)throw Error('Queue saved unexpected mappings');await queue.scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-scanned-queue-saved.png'});report.status='saved';persist();}
 const first=report.mappings.find(m=>m.page===4);if(!first)throw Error('No confirmed page4 mapping; inspect checkpoint');
 for(const m of report.mappings){const response=await page.request.get(`http://127.0.0.1:58002/api/financial/candidate-mappings/${m.id}?case_id=${caseId}`,{headers});const saved=await response.json();if(!response.ok()||saved.evidence_file_id!==fileId||saved.original.proposal.page_number!==m.page||saved.candidates.length!==m.rows||saved.candidates.some(c=>c.status!=='pending'||!m.candidate_ids.includes(c.id)))throw Error('Persisted pending mappings differ');}
 await page.reload();await page.getByRole('button',{name:'Open PDF readings',exact:true}).click();const list=await(await page.request.get(`http://127.0.0.1:58002/api/financial/candidate-mappings?case_id=${caseId}&limit=25&offset=0`,{headers})).json();const index=list.items.findIndex(m=>m.id===first.id);if(index<0)throw Error('Saved queue absent from batch list');const loaded=page.waitForResponse(r=>r.url().includes(`/candidate-mappings/${first.id}?`));await page.getByRole('button',{name:'Open readings',exact:true}).nth(index).click();const saved=await(await loaded).json();await page.getByRole('button',{name:`Review source row ${saved.candidates[0].row_index+1}`,exact:true}).click();const image=page.getByRole('img',{name:'Page 4 of the source document',exact:true});await image.waitFor();await image.evaluate(img=>img.decode());await page.getByRole('region',{name:'Original document beside review',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-scanned-queue-review.png'});
 const ledger=await(await page.request.get(`http://127.0.0.1:58002/api/financial/ledger-working-summary?case_id=${caseId}`,{headers})).json();if(ledger.included_rows!==0||otherWrites||errors.length)throw Error(JSON.stringify({included:ledger.included_rows,otherWrites,errors}));Object.assign(report,{status:'verified_pending',pages:[4,6,10],readings:7,latest_mapping_writes:mappingWrites,ledger_writes:0,source_reopened:true,all_pending:true});persist();console.log(JSON.stringify(report));
 }catch(e){if(page){await page.screenshot({path:'/tmp/loupe-scanned-queue-failure.png'});fs.writeFileSync('/tmp/loupe-scanned-queue-failure.txt',await page.locator('body').innerText())}throw e}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
