// Read-only regression for measured amounts whose extracted column indices shift.
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),{chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const browser=await chromium.launch({headless:true});try{
const page=await browser.newPage();await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));
const caseId='3db2ae11-da7f-405a-a087-b465bdc9f12d',fileId='a31e783e-84f8-415b-9d43-b0c481acc43e',headers={Authorization:`Bearer ${await page.evaluate(()=>localStorage.getItem('authToken'))}`};
const response=await page.request.get(`http://127.0.0.1:58002/api/financial/candidate-sources/${fileId}/page-scan?case_id=${caseId}&start_page=4&end_page=4&table_index=0&currency=USD&auto_columns=true`,{headers});if(!response.ok())throw Error(await response.text());const data=await response.json(),scan=data.pages[0];
if(scan.suggestions.length!==4||!scan.chosen_columns.alignment_source||JSON.stringify(scan.suggestions.map(r=>r.amount_source.expected_text))!==JSON.stringify(['14.00','100.00','0.00','0.00']))throw Error(JSON.stringify(data));
if(scan.suggestions.some(r=>r.amount_source.locator.kind!=='page_rectangle')||data.applied!==false)throw Error('Missing measured source or scan wrote readings');
await page.goto(`http://127.0.0.1:55174/cases/${caseId}/financial`);await page.getByRole('button',{name:'Open PDF readings',exact:true}).click();await page.getByRole('button',{name:'Choose PDF rows',exact:true}).click();await page.getByRole('button',{name:/ · page 4$/}).click();await page.getByRole('button',{name:'Find possible rows across PDF pages',exact:true}).click();await page.getByLabel('Propose columns on each page',{exact:true}).check();await page.getByLabel('Scan from page',{exact:true}).fill('4');await page.getByLabel('Scan through page',{exact:true}).fill('4');await page.getByLabel('Scan currency',{exact:true}).fill('USD');await page.getByRole('button',{name:'Scan selected page range',exact:true}).click();await page.getByText(/Amount positions are grouped by measured alignment/).waitFor();await page.getByRole('region',{name:'Queue scanned PDF readings',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-shifted-amount-scan.png'});
const report={case_id:caseId,evidence_file_id:fileId,page:4,amounts:scan.suggestions.map(r=>r.amount_source.expected_text),measured_alignment:true,source_citations_retained:true,financial_writes:0};fs.writeFileSync(path.join(root,'data/local-runtime/shifted-amount-scan-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
