// Writes one deliberate acceptance correction in its isolated, checkpointed case only.
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');const {chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
const output=path.join(root,'data/local-runtime/real-pdf-correction-check.json');
(async()=>{if(fs.existsSync(output))throw Error('Correction checkpoint exists; inspect before any retry');const fixture=JSON.parse(fs.readFileSync(path.join(root,'data/local-runtime/correction-pdf-setup-check.json')));if(fixture.case_id!=='ea81df83-814c-4f9e-b3a8-3a989190b920'||fixture.status!=='finalized')throw Error('Unexpected fixture');
 const original=fixture.finalization.transactions[1];const report={case_id:fixture.case_id,original,status:'started'};const save=()=>fs.writeFileSync(output,JSON.stringify(report,null,2));
 const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(30000);
 await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));
 await page.goto(`http://127.0.0.1:55174/cases/${fixture.case_id}/financial`);
 await page.locator(`[data-row-key="${original.transaction_id}"]`).getByRole('button',{name:'Correct amount',exact:true}).click();await page.getByLabel('Proposed amount (USD)',{exact:true}).fill('61.62');
 const pending=page.waitForResponse(r=>r.url().includes('/correction-preview?'));await page.getByRole('button',{name:'Preview correction',exact:true}).click();const preview=await pending;report.preview=await preview.json();if(!preview.ok()||report.preview.original.amount_minor!=='6126'||report.preview.proposed.amount_minor!=='6162')throw Error('Unexpected correction preview');
 await page.getByLabel('Reason for correction',{exact:true}).fill('Real-PDF correction acceptance test. Correct the deliberately entered test error $61.26 to the actual $61.62 purchase printed on original PDF page 3. This does not alter the source or establish complete statement coverage.');
 save();const corrected=page.waitForResponse(r=>r.url().includes('/correction?'));await page.getByRole('button',{name:'Record correction',exact:true}).click();const response=await corrected;report.result=await response.json();save();if(!response.ok()||report.result.proof_class!=='p3')throw Error('Correction failed');
 await page.getByRole('tab',{name:'Decisions',exact:true}).click();const decision=page.locator(`[data-decision-id="${report.result.adjudication_id}"]`);await decision.getByText('Original and replacement readings',{exact:true}).click();await decision.scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-neilbyrne-real-pdf-correction-history.png'});
 await page.getByRole('tab',{name:'Ledger',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download ledger snapshot',exact:true}).click();await(await download).saveAs(path.join(root,'data/local-runtime/real-pdf-corrected-export.zip'));
 report.status='corrected_and_exported';save();console.log(JSON.stringify({case_id:report.case_id,result:report.result,status:report.status}));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
