// Isolated synthetic native ingestion and read-only correction preview.
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const {chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const reportPath=path.join(root,'data/local-runtime/native-controls-browser-check.json');
let report=fs.existsSync(reportPath)?JSON.parse(fs.readFileSync(reportPath)):{};
if(report.status==='verified')throw Error('Completed native check; do not rerun mutations');
const browser=await chromium.launch({headless:true});try{
const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(20000);
await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));
const headers={Authorization:`Bearer ${await page.evaluate(()=>localStorage.getItem('authToken'))}`};
const save=()=>fs.writeFileSync(reportPath,JSON.stringify(report,null,2));
if(!report.case_id){const response=await page.request.post('http://127.0.0.1:58002/api/cases',{headers,data:{title:'LOCAL ACCEPTANCE — synthetic native control corrections',description:'Generated camt.053 fixture; not bank evidence.'}});if(!response.ok())throw Error(await response.text());report.case_id=(await response.json()).id;save();}
if(!report.file_id){const response=await page.request.post('http://127.0.0.1:58002/api/evidence/upload',{headers,multipart:{case_id:report.case_id,files:{name:'synthetic-native-controls.xml',mimeType:'application/xml',buffer:fs.readFileSync(path.join(root,'data/local-runtime/synthetic-native-controls.xml'))}}});if(!response.ok())throw Error(await response.text());report.file_id=(await response.json()).files[0].id;save();}
if(!report.ingestion){const query=new URLSearchParams({case_id:report.case_id,file_id:report.file_id,window_start:'2020-01-01',window_end:'2029-12-31'});const response=await page.request.post(`http://127.0.0.1:58002/api/financial/ingest?${query}`,{headers});report.ingestion=await response.json();save();if(!response.ok())throw Error(JSON.stringify(report.ingestion));}
await page.goto(`http://127.0.0.1:55174/cases/${report.case_id}/financial`);await page.getByRole('tab',{name:'Ledger',exact:true}).click();const table=page.getByTestId('ledger-table');await table.locator('tbody tr').first().getByRole('button',{name:'Correct amount',exact:true}).click();await page.getByLabel('Proposed amount (USD)',{exact:true}).fill('5000.01');const pending=page.waitForResponse(r=>r.url().includes('/correction-preview?'));await page.getByRole('button',{name:'Preview correction',exact:true}).click();const response=await pending,preview=await response.json();if(!response.ok()||!preview.native_controls_rechecked)throw Error(JSON.stringify(preview));
const region=page.getByRole('region',{name:'Native bank-file control comparison',exact:true});await region.getByText('After proposed correction',{exact:true}).waitFor();if(!preview.native_controls.proposed.checks.some(c=>c.result.status==='unbalanced'))throw Error('Expected discrepancy missing');await region.scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-native-controls.png'});report.status='verified';report.source_hash=preview.native_controls.sha256;report.current=preview.native_controls.current;report.proposed=preview.native_controls.proposed;report.proposed_proof_class=preview.verification.proposed_proof_class;report.corrections_written=0;save();console.log(JSON.stringify({status:report.status,case_id:report.case_id,checks:report.proposed.checks.length,proof:report.proposed_proof_class}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
