// Read-only table view export against the saved real statement.
const path=require('path'),fs=require('fs'),root=path.resolve(__dirname,'..'),{chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(20000);let writes=0;await page.route('**/api/financial/**',async route=>{if(!['GET','HEAD'].includes(route.request().method())){writes++;await route.abort()}else await route.continue()});
 await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));
 const caseId='e8ecc646-7b29-49d6-b64d-7086a9a14ad4';await page.goto(`http://127.0.0.1:55174/cases/${caseId}/financial`);await page.getByLabel('Table currency',{exact:true}).selectOption('USD');await page.getByLabel('Table minimum amount',{exact:true}).fill('60.00');await page.getByLabel('Table maximum amount',{exact:true}).fill('70.00');await page.getByLabel('Table direction',{exact:true}).selectOption('debit');await page.getByLabel('Table proof class',{exact:true}).selectOption('p3');await page.getByLabel('Table order',{exact:true}).selectOption('amount-desc');await page.getByText(/1 of 3 loaded rows match/).waitFor();await page.getByLabel('Include a PDF in the table-view export',{exact:true}).check();
 const pending=page.waitForResponse(r=>r.url().includes('/ledger-export?')&&r.url().includes('table_view=')),downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Download this table view',exact:true}).click();const response=await pending;if(!response.ok())throw Error(await response.text());const view=JSON.parse(response.headers()['x-loupe-table-view']);if(view.search!==''||view.minimum_minor!=='6000'||view.maximum_minor!=='7000'||view.sort!=='amount-desc'||view.proof!=='p3')throw Error('Wrong scope echo');await(await downloaded).saveAs(path.join(root,'data/local-runtime/ledger-range-export.zip'));
 const region=page.getByRole('region',{name:'Export this table view',exact:true});await region.scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-range-export.png'});if(writes)throw Error('Unexpected write');const report={case_id:caseId,filters:view,visible_rows:1,loaded_rows:3,downloaded:true,financial_writes:0};fs.writeFileSync(path.join(root,'data/local-runtime/ledger-range-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
