// Four synthetic workpaper calculations; one guarded Workspace note, no ledger edits.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),root=path.resolve(__dirname,'..');const {chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
const output=path.join(root,'data/local-runtime/indirect-review-ui-check.json'),readOnly=process.argv.includes('--read-only');
(async()=>{if(fs.existsSync(output)&&!readOnly)throw Error('Workpaper writer checkpoint exists; inspect it or use --read-only');const fixture=JSON.parse(fs.readFileSync(path.join(root,'data/local-runtime/current-resilience-check.json')));const caseId=fixture.case_id;if(caseId!=='e9cafc92-85a7-497c-aec8-049157e823d0')throw Error('Wrong synthetic case');let report=readOnly?JSON.parse(fs.readFileSync(output)):{case_id:caseId,synthetic:true};const save=()=>fs.writeFileSync(output,JSON.stringify(report,null,2));const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(30000);let edits=0,workspaceWrites=0;const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/financial/**',async route=>{if(!['GET','HEAD'].includes(route.request().method())&&!route.request().url().includes('/indirect-review?')){edits++;await route.abort()}else await route.continue()});
 await page.route('**/api/workspace/**',async route=>{if(!['GET','HEAD'].includes(route.request().method())){if(readOnly||route.request().method()!=='POST'||!route.request().url().endsWith(`/workspace/${caseId}/entries`)){await route.abort();throw Error('Unexpected Workspace edit')}workspaceWrites++}await route.continue()});
 await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));await page.goto(`http://127.0.0.1:55174/cases/${caseId}/financial`);await page.getByRole('tab',{name:'Conditional tracing',exact:true}).click();
 const methodsResponse=page.waitForResponse(r=>r.url().includes('/indirect-review-methods?'));await page.getByRole('button',{name:'Indirect review methods',exact:true}).click();const catalog=await(await methodsResponse).json();
 await page.getByLabel('Indirect subject',{exact:true}).fill('SYNTHETIC workpaper acceptance only');await page.getByLabel('Indirect currency',{exact:true}).fill('GBP');await page.getByLabel('Indirect from',{exact:true}).fill('2026-01-01');await page.getByLabel('Indirect through',{exact:true}).fill('2026-12-31');
 const calculate=async()=>{const pending=page.waitForResponse(r=>r.url().includes('/indirect-review?')&&r.request().method()==='POST');await page.getByRole('button',{name:'Calculate indirect workpaper',exact:true}).click();const response=await pending;if(!response.ok())throw Error(JSON.stringify(await response.json()));const envelope=await response.json();if(crypto.createHash('sha256').update(envelope.scenario_json).digest('hex')!==envelope.scenario_sha256)throw Error('Capture hash differs');await page.getByRole('region',{name:'Indirect workpaper result',exact:true}).waitFor();return {envelope,value:JSON.parse(envelope.scenario_json)}};
 const incomplete=await calculate();if(incomplete.value.difference_minor!==null||incomplete.value.review_fields_complete)throw Error('Unknown inputs produced a result');
 await page.getByRole('button',{name:'Search indirect sources',exact:true}).click();await page.getByLabel('Amount source closing_assets',{exact:true}).locator(`option[value="${fixture.evidence_file_id}"]`).waitFor({state:'attached'});
 const fillRef=async(kind,key)=>{const select=page.getByLabel(`${kind} source ${key}`,{exact:true});if(!await select.isVisible())await select.locator('xpath=ancestor::details').locator('summary').click();await select.selectOption(fixture.evidence_file_id);await page.getByLabel(`${kind} location ${key}`,{exact:true}).fill('Page1of the synthetic fixture; interpretation is a test assumption');await page.getByLabel(`${kind} basis ${key}`,{exact:true}).fill('Synthetic imposed value or review for software acceptance only. This does not assert that the printed source establishes the entered value or completes an investigation.');};
 const values={net_worth:{closing_assets:'100.00',opening_assets:'60.00'},bank_deposits:{deposits:'100.00',reported_income:'60.00'},expenditure:{money_applied:'100.00',reported_income:'60.00'},cash_t:{cash_uses:'100.00',cash_sources:'60.00'}};
 let last;const checked=[];for(const id of ['cash_t','bank_deposits','expenditure','net_worth']){await page.getByLabel('Indirect method',{exact:true}).selectOption(id);const method=catalog.methods.find(m=>m.id===id);for(const term of method.terms){await fillRef('Amount',term.id);await page.getByLabel(`Indirect amount ${term.id}`,{exact:true}).fill(values[id][term.id]??'0.00')}for(const requirement of catalog.requirements){await fillRef('Review',requirement.id);await page.getByLabel(`Indirect reviewed ${requirement.id}`,{exact:true}).check()}last=await calculate();if(last.value.difference_minor!=='4000'||!last.value.review_fields_complete||last.value.sources.length!==1)throw Error('Conditional method result differs');checked.push(id)}
 await page.getByLabel('Indirect method',{exact:true}).selectOption('cash_t');if(await page.getByLabel('Indirect amount cash_uses',{exact:true}).inputValue()!=='100.00')throw Error('Method switch lost draft');await page.getByLabel('Indirect method',{exact:true}).selectOption('net_worth');last=await calculate();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download indirect workpaper',exact:true}).click();const destination=path.join(root,'data/local-runtime/indirect-workpaper.json');await(await download).saveAs(destination);if(JSON.parse(fs.readFileSync(destination)).scenario_sha256!==last.envelope.scenario_sha256)throw Error('Download mismatch');
 await page.getByLabel('Indirect subject',{exact:true}).fill('Changed draft');if(await page.getByRole('region',{name:'Indirect workpaper result',exact:true}).count())throw Error('Stale result retained');await page.getByLabel('Restore indirect workpaper',{exact:true}).setInputFiles(destination);await page.getByText('Conditional difference: 40.00 GBP',{exact:true}).waitFor();if(await page.getByLabel('Indirect subject',{exact:true}).inputValue()!=='SYNTHETIC workpaper acceptance only')throw Error('Restore lost subject');
 const source=page.waitForResponse(r=>r.url().includes(`/evidence/${fixture.evidence_file_id}/file`)).catch(()=>null);const sourceButton=page.getByRole('button',{name:'Inspect amount source closing_assets',exact:true});if(!await sourceButton.isVisible())await page.getByLabel('Amount source closing_assets',{exact:true}).locator('xpath=ancestor::details').locator('summary').click();try{await sourceButton.click();const opened=await source;if(!opened?.ok())throw Error('Original file did not open')}catch(e){await page.screenshot({path:'/tmp/loupe-indirect-failure.png'});console.error((await page.locator('body').innerText()).slice(-14000));throw e};await page.keyboard.press('Escape');
 if(!readOnly){report.status='write_started';save();const pending=page.waitForResponse(r=>r.url().endsWith(`/workspace/${caseId}/entries`)&&r.request().method()==='POST');await page.getByRole('button',{name:'Save workpaper in Workspace',exact:true}).click();const response=await pending,entry=await response.json();if(!response.ok())throw Error(JSON.stringify(entry));report.entry_id=entry.id;report.status='saved';save();}
 const headers={Authorization:`Bearer ${await page.evaluate(()=>localStorage.getItem('authToken'))}`};const savedResponse=await page.request.get(`http://127.0.0.1:58002/api/workspace/${caseId}/entries/${report.entry_id}`,{headers});const saved=await savedResponse.json();if(!savedResponse.ok()||saved.links[0].metadata.envelope.scenario_sha256!==last.envelope.scenario_sha256||saved.case_id!==caseId)throw Error('Persisted workpaper differs');
 await page.getByRole('region',{name:'Indirect workpaper result',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-indirect-workpaper.png'});if(edits||errors.length||workspaceWrites!==(readOnly?0:1))throw Error(JSON.stringify({edits,errors,workspaceWrites}));Object.assign(report,{status:'verified',methods:checked,conditional_difference_minor:'4000',unknowns_withhold_result:true,method_drafts_preserved:true,download_restore_verified:true,source_opened:true,workspace_reopened:true,latest_workspace_writes:workspaceWrites,ledger_writes:edits,limitation:'Synthetic assessed values only; sources are references, not asserted proof of the amounts or investigation completeness.'});save();console.log(JSON.stringify(report));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
