// Writes once into the synthetic printed-totals acceptance case, never real evidence.
const path=require('path'),fs=require('fs'),root=path.resolve(__dirname,'..'),{chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const checkpoint=path.join(root,'data/local-runtime/printed-totals-journey-check.json');const resume=process.argv[2]==='--resume-review';if(fs.existsSync(checkpoint)&&!resume)throw Error('Journey already started; inspect saved state before any further write.');const intake=JSON.parse(fs.readFileSync(path.join(root,'data/local-runtime/printed-totals-intake-check.json'))),caseId=intake.case_id,fileId=intake.upload.files[0].id;
 if(caseId!=='d72a4ac0-f990-415e-be89-838f955e6af2')throw Error('Unexpected case');const report=resume?JSON.parse(fs.readFileSync(checkpoint)):{case_id:caseId,file_id:fileId,status:'started'};if(resume&&(report.status!=='mapped'||report.reviewed||!report.account_id))throw Error('Not at untouched review checkpoint');const save=()=>fs.writeFileSync(checkpoint,JSON.stringify(report,null,2));const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(30000);await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));const headers={Authorization:`Bearer ${await page.evaluate(()=>localStorage.getItem('authToken'))}`};
 const raw=await page.request.get(`http://127.0.0.1:58002/api/financial/candidate-sources/${fileId}/pages/1?case_id=${caseId}&table_index=0`,{headers}),table=await raw.json();if(!raw.ok())throw Error(JSON.stringify(table));
 const rowFor=text=>{const rows=table.rows.filter(r=>r.cells.some(c=>c.expected_text===text));if(rows.length!==1)throw Error('Ambiguous synthetic row '+text);return rows[0].row_index+1};
 const selections=[['Customer deposit','100.00','credit','2026-01-02'],['Office cost','30.00','debit','2026-01-03']];
 if(!resume){ await page.goto(`http://127.0.0.1:55174/cases/${caseId}/financial`);await page.getByRole('button',{name:'Open PDF readings',exact:true}).click();await page.getByRole('button',{name:'Choose PDF rows',exact:true}).click();await page.getByRole('button',{name:`${intake.filename} · page 1`,exact:true}).click();for(const[col,role]of[[1,'transaction_date'],[2,'description'],[3,'amount'],[4,'direction']])await page.getByLabel(`Column ${col} meaning`,{exact:true}).selectOption(role);
 for(const[description]of selections)await page.getByLabel(`Select source row ${rowFor(description)}`,{exact:true}).check();save();const mappingPending=page.waitForResponse(r=>r.url().includes('/candidate-mappings?')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save selected rows for review',exact:true}).click();const mappingResponse=await mappingPending,mapping=await mappingResponse.json();if(!mappingResponse.ok())throw Error(JSON.stringify(mapping));report.mapping_id=mapping.id;report.status='mapped';save();
}else{await page.goto(`http://127.0.0.1:55174/cases/${caseId}/financial`);await page.getByRole('button',{name:'Open PDF readings',exact:true}).click();await page.getByRole('listitem').filter({hasText:'2 possible transactions'}).getByRole('button',{name:'Open readings',exact:true}).click();}
 for(const [i,[description,amount,direction,date]]of selections.entries()){
  await page.getByRole('button',{name:`Review source row ${rowFor(description)}`,exact:true}).click();await page.getByLabel('Currency',{exact:true}).fill('GBP');
  if(i===0&&!report.account_id){await page.getByRole('button',{name:'Set up a provisional account',exact:true}).click();await page.getByLabel('Provisional account label',{exact:true}).fill('SYNTHETIC — printed totals account');await page.getByLabel('Reason for provisional account',{exact:true}).fill('Generated acceptance statement; not real bank evidence.');const pending=page.waitForResponse(r=>r.url().includes('/provisional-account?')&&r.request().method()==='POST');await page.getByRole('button',{name:'Create provisional account',exact:true}).click();const response=await pending,a=await response.json();if(!response.ok())throw Error(JSON.stringify(a));report.account_id=a.account.id;save();}else await page.getByLabel('Account',{exact:true}).selectOption(report.account_id);
  await page.getByLabel('Reviewed amount',{exact:true}).fill(amount);await page.getByLabel('Direction',{exact:true}).selectOption(direction);await page.getByLabel('Transaction date',{exact:true}).fill(date);await page.getByLabel('Description',{exact:true}).fill(description);await page.getByLabel('Reason for decision',{exact:true}).fill('Visually checked generated synthetic statement; exact row and source retained.');const reviewed=page.waitForResponse(r=>r.url().includes('/review?')&&r.request().method()==='POST');await page.getByRole('button',{name:'Record resolved reading',exact:true}).click();const response=await reviewed;if(!response.ok())throw Error(await response.text());report.reviewed=i+1;save();
 }
 await page.getByRole('button',{name:'Preview finalization',exact:true}).click();await page.getByRole('button',{name:'Add printed statement controls',exact:true}).click();await page.getByLabel('Statement account',{exact:true}).selectOption(`${report.account_id}:GBP`);for(const n of[1,2])await page.getByLabel(`Assign reviewed row ${n} to statement`,{exact:true}).check();for(const[label,value]of[['Printed statement start','2026-01-01'],['Printed statement end','2026-01-31'],['Printed opening balance','0'],['Printed closing balance','70'],['Printed total money in','100'],['Printed total money out','30']])await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel('Printed balance convention',{exact:true}).selectOption('asset_balance');
 for(const[role,label]of[['statement start','Statement start'],['statement end','Statement end'],['opening balance','Opening balance'],['closing balance','Closing balance'],['total money in','Total money in'],['total money out','Total money out']]){await page.getByRole('button',{name:`Choose source for ${role}`,exact:true}).click();await page.getByLabel(`Control row ${rowFor(label)}, column 2`,{exact:true}).click();await page.getByRole('button',{name:'Use this control cell',exact:true}).click();}
 await page.getByLabel('Reason for statement control readings',{exact:true}).fill('Generated synthetic statement explicitly prints full incoming and outgoing totals. All six controls visually checked; no proof promotion.');await page.getByRole('button',{name:'Add statement to preview',exact:true}).click();const previewPending=page.waitForResponse(r=>r.url().includes('/finalization-preview?')&&r.request().method()==='POST');await page.getByRole('button',{name:'Preview finalization',exact:true}).click();const previewResponse=await previewPending;report.preview=await previewResponse.json();save();if(!previewResponse.ok())throw Error(JSON.stringify(report.preview));await page.getByRole('checkbox',{name:/These are documentary/}).check();await page.getByRole('checkbox',{name:/I accept incomplete/}).check();await page.getByLabel('Reason for finalization').fill('Synthetic printed-controls acceptance; retain P3 and all original source cells.');const finalized=page.waitForResponse(r=>r.url().includes('/finalize?')&&r.request().method()==='POST');await page.getByRole('button',{name:'Finalize selected rows',exact:true}).click();const finalResponse=await finalized;report.finalization=await finalResponse.json();save();if(!finalResponse.ok())throw Error(JSON.stringify(report.finalization));report.status='finalized';save();
 const checksResponse=await page.request.get(`http://127.0.0.1:58002/api/financial/statement-checks?case_id=${caseId}`,{headers}),checks=await checksResponse.json();if(!checksResponse.ok())throw Error(JSON.stringify(checks));const period=checks.items[0];if(period.status!=='balanced'||period.printed_totals.checks.some(c=>c.status!=='balanced'))throw Error('Printed controls did not match');report.period_id=period.period_id;report.printed_checks=period.printed_totals;report.status='verified';save();console.log(JSON.stringify({case_id:caseId,status:report.status,checks:period.printed_totals}));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
