// Read-only statement layout/context acceptance against the supplied Capital One PDF.
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),{chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const browser=await chromium.launch({headless:true});let page;try{
page=await browser.newPage({viewport:{width:1600,height:1200}});let writes=0;await page.route('**/api/financial/**',async route=>{if(!['GET','HEAD'].includes(route.request().method())){writes++;await route.abort()}else await route.continue()});
await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));
const caseId='e8ecc646-7b29-49d6-b64d-7086a9a14ad4',fileId='f256eda2-7ac7-46e9-855b-01a0ed0d7785',headers={Authorization:`Bearer ${await page.evaluate(()=>localStorage.getItem('authToken'))}`};
const contexts=[],unavailable=[];
for(let number=1;number<=108;number++){const response=await page.request.get(`http://127.0.0.1:58002/api/financial/candidate-sources/${fileId}/pages/${number}?case_id=${caseId}`,{headers});if(response.status()===404){unavailable.push({page:number,reason:await response.text()});continue}if(!response.ok())throw Error(`Source ${number}: ${response.status()}`);const data=await response.json();if(data.layout_context)contexts.push({page:number,...data.layout_context});}
const first=contexts.find(p=>p.page===3);if(!first||first.rows.length!==2||first.rows[0].card_ending!=='3539'||first.rows[0].date_proposals[0]!=='2020-05-30'||first.rows[1].date_proposals[0]!=='2020-05-29')throw Error('Known printed context not recovered');
await page.goto(`http://127.0.0.1:55174/cases/${caseId}/financial`);await page.getByRole('button',{name:'Open PDF readings',exact:true}).click();await page.getByRole('button',{name:'Choose PDF rows',exact:true}).click();await page.getByRole('button',{name:/ · page 3$/}).click();await page.getByRole('button',{name:'Inspect printed statement context',exact:true}).click();let panel=page.getByRole('region',{name:'Printed statement layout context',exact:true});await panel.getByRole('button',{name:'Inspect section for row 10',exact:true}).click();await page.getByRole('img',{name:'Page 3 of the source document',exact:true}).evaluate(img=>img.decode());await panel.scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-statement-layout-context.png'});
const list=await(await page.request.get(`http://127.0.0.1:58002/api/financial/candidate-mappings?case_id=${caseId}&limit=25&offset=0`,{headers})).json();let selected=null;
for(let index=0;index<list.items.length;index++){const mapping=await(await page.request.get(`http://127.0.0.1:58002/api/financial/candidate-mappings/${list.items[index].id}?case_id=${caseId}`,{headers})).json();if(mapping.evidence_file_id===fileId&&mapping.original.proposal.page_number===3){const candidate=mapping.candidates.find(c=>c.row_index===9);if(candidate){selected={index,candidate};break}}}
if(!selected)throw Error('Saved payment review missing');
await page.reload();await page.getByRole('button',{name:'Open PDF readings',exact:true}).click();await page.getByRole('button',{name:'Open readings',exact:true}).nth(selected.index).click();await page.getByRole('button',{name:'Review source row 10',exact:true}).click();await page.getByRole('button',{name:'Inspect printed statement context',exact:true}).click();panel=page.getByRole('region',{name:'Printed statement layout context',exact:true});await panel.getByRole('button',{name:'Inspect printed billing cycle',exact:true}).click();await page.getByRole('img',{name:'Page 3 of the source document',exact:true}).evaluate(img=>img.decode());await panel.scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-saved-statement-context.png'});
await page.getByRole('img',{name:'Page 3 of the source document',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-statement-context-source.png'});
if(writes)throw Error('Unexpected write');const report={requested_pages:108,unavailable_pages:unavailable,matched_pages:contexts.length,context_rows:contexts.reduce((n,p)=>n+p.rows.length,0),possible_dates:contexts.reduce((n,p)=>n+p.rows.filter(r=>r.date_proposals.length).length,0),first_payment_date:'2020-05-30',first_purchase_date:'2020-05-29',source_and_saved_review_context:true,financial_writes:writes};fs.writeFileSync(path.join(root,'data/local-runtime/statement-layout-context-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(error){if(page){fs.writeFileSync('/tmp/loupe-statement-layout-failure.txt',await page.locator('body').innerText());await page.screenshot({path:'/tmp/loupe-statement-layout-failure.png'})}throw error}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
