// Read-only current checks, source controls, correction preview and PDF export.
const path=require('path'),fs=require('fs'),root=path.resolve(__dirname,'..'),{chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const record=JSON.parse(fs.readFileSync(path.join(root,'data/local-runtime/printed-totals-journey-check.json')));if(record.status!=='verified')throw Error('Synthetic controls journey unfinished');const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(20000);let writes=0;await page.route('**/api/financial/**',async route=>{const r=route.request();if(!['GET','HEAD'].includes(r.method())&&!r.url().includes('/correction-preview?')){writes++;await route.abort()}else await route.continue()});
 await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));await page.goto(`http://127.0.0.1:55174/cases/${record.case_id}/financial`);
 await page.getByRole('tab',{name:'Statements',exact:true}).click();await page.getByRole('button',{name:'Check statement balances',exact:true}).click();const checks=page.getByRole('region',{name:'Printed transaction totals',exact:true});await checks.getByText('Money in: Agrees with printed total.',{exact:true}).waitFor();await checks.getByText('Money out: Agrees with printed total.',{exact:true}).waitFor();await checks.scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-printed-totals-checks.png'});
 await page.getByRole('button',{name:'Inspect statement source',exact:true}).click();await page.getByRole('button',{name:/Inspect total money in:/}).click();await page.getByText('Original text: 100.00',{exact:true}).waitFor();await page.keyboard.press('Escape');
 await page.getByRole('tab',{name:'Ledger',exact:true}).click();const debit=page.getByTestId('ledger-table').locator('tbody tr').filter({hasText:'Office cost'});await debit.getByRole('button',{name:'Correct amount',exact:true}).click();await page.getByLabel('Proposed amount (GBP)',{exact:true}).fill('30.01');const previewPending=page.waitForResponse(r=>r.url().includes('/correction-preview?'));await page.getByRole('button',{name:'Preview correction',exact:true}).click();const previewResponse=await previewPending,preview=await previewResponse.json();if(!previewResponse.ok()||preview.printed_totals.proposed.checks[1].difference_minor!=='1')throw Error(JSON.stringify(preview));const proposed=page.getByRole('region',{name:'Printed totals after proposed correction',exact:true});await proposed.getByText(/Money out: Differs from printed total/).waitFor();await proposed.scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-printed-total-correction.png'});await page.getByRole('button',{name:'Close correction',exact:true}).click();
 await page.getByLabel('Include a paginated PDF report',{exact:true}).check();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download ledger snapshot',exact:true}).click();await(await download).saveAs(path.join(root,'data/local-runtime/printed-totals-export.zip'));if(writes)throw Error('Unexpected ledger write');const report={case_id:record.case_id,visible_current_totals:true,source_controls_opened:true,proposed_debit_difference_minor:'1',export_downloaded:true,financial_writes:writes};fs.writeFileSync(path.join(root,'data/local-runtime/printed-totals-analysis-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
