// One synthetic change and restoration; both remain in audit history. Refuses reruns.
const path=require('path'),fs=require('fs'),root=path.resolve(__dirname,'..'),{chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const checkpoint=path.join(root,'data/local-runtime/correction-across-views-check.json');if(fs.existsSync(checkpoint))throw Error('Cross-view correction already started; inspect checkpoint before repeating any write.');const fixture=JSON.parse(fs.readFileSync(path.join(root,'data/local-runtime/printed-totals-journey-check.json')));if(fixture.status!=='verified')throw Error('Synthetic fixture unfinished');const caseId=fixture.case_id,report={case_id:caseId,status:'started'},save=()=>fs.writeFileSync(checkpoint,JSON.stringify(report,null,2));const browser=await chromium.launch({headless:true});let changed=false,page,headers;try{
 page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(25000);await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));headers={Authorization:`Bearer ${await page.evaluate(()=>localStorage.getItem('authToken'))}`};await page.goto(`http://127.0.0.1:55174/cases/${caseId}/financial`);
 const readLedger=async()=>{const r=await page.request.get(`http://127.0.0.1:58002/api/financial/ledger?case_id=${caseId}`,{headers});if(!r.ok())throw Error('Ledger read failed');return(await r.json()).transactions;};
 const original=(await readLedger()).find(r=>r.description==='Office cost');if(!original||original.amount_minor!=='3000'||original.proof_class!=='p3')throw Error('Unexpected synthetic starting reading');report.original_id=original.key;
 const correct=async(amount)=>{await page.getByRole('tab',{name:'Ledger',exact:true}).click();const row=page.getByTestId('ledger-table').locator('tbody tr').filter({hasText:'Office cost'});await row.getByRole('button',{name:'Correct amount',exact:true}).click();await page.getByLabel('Proposed amount (GBP)',{exact:true}).fill(amount);await page.getByRole('button',{name:'Preview correction',exact:true}).click();await page.getByLabel('Reason for correction',{exact:true}).fill('Synthetic cross-view acceptance only: '+(amount==='30.01'?'introduce one penny to check every current view.':'restore the printed amount after acceptance; preserve both decisions.'));const pending=page.waitForResponse(r=>r.url().includes('/correction?')&&r.request().method()==='POST');save();await page.getByRole('button',{name:'Record correction',exact:true}).click();const response=await pending,result=await response.json();if(!response.ok())throw Error(JSON.stringify(result));await page.getByText(/Correction recorded. Replacement citation/).waitFor();await page.getByRole('button',{name:'Close correction',exact:true}).click();return result;};
 changed=true;report.changed=await correct('30.01');report.status='changed';save();await page.getByRole('region',{name:'Working ledger totals',exact:true}).getByText('Debits: 30.01 GBP',{exact:true}).waitFor();report.ledger=true;
 await page.getByRole('tab',{name:'Transactions',exact:true}).click();await page.getByRole('region',{name:'Working ledger totals',exact:true}).getByText('Debits: 30.01 GBP',{exact:true}).waitFor();report.transactions=true;
 for(const[tab,region,button]of[['Counterparties','Ledger counterparty labels','Read ledger counterparty totals'],['Trends','Ledger totals by date','Read ledger date totals']]){await page.getByRole('tab',{name:tab,exact:true}).click();await page.getByLabel('Analysis population',{exact:true}).selectOption('working');await page.getByRole('button',{name:button,exact:true}).click();await page.getByRole('region',{name:region,exact:true}).getByText('Credits: 100.00 GBP · Debits: 30.01 GBP · Net postings: 69.99 GBP',{exact:true}).waitFor();report[tab]=true;save();}
 await page.getByRole('tab',{name:'Posting graph',exact:true}).click();const graphPending=page.waitForResponse(r=>r.url().includes('/ledger-posting-graph?'));await page.getByRole('button',{name:'Load posting graph',exact:true}).click();const graph=await(await graphPending).json();if(graph.edges.length!==2||!graph.edges.some(e=>e.amount_minor==='3001'))throw Error('Graph did not use corrected current rows');report.posting_graph=true;
 await page.getByRole('tab',{name:'Statements',exact:true}).click();await page.getByRole('button',{name:'Check statement balances',exact:true}).click();await page.getByRole('region',{name:'Printed transaction totals',exact:true}).getByText('Money out: Differs from printed total.',{exact:true}).waitFor();report.printed_controls=true;
 report.restored=await correct('30.00');changed=false;report.status='restored';save();await page.getByRole('region',{name:'Working ledger totals',exact:true}).getByText('Debits: 30.00 GBP',{exact:true}).waitFor();
 const rows=await readLedger();if(rows.length!==2||!rows.some(r=>r.key===report.restored.replacement_id&&r.amount_minor==='3000'&&r.proof_class==='p3'))throw Error('Restoration mismatch');const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Download ledger snapshot',exact:true}).click();await(await downloaded).saveAs(path.join(root,'data/local-runtime/correction-across-views-export.zip'));report.status='verified';save();console.log(JSON.stringify(report));
 }finally{
  if(changed&&page&&headers){try{const r=await page.request.get(`http://127.0.0.1:58002/api/financial/ledger?case_id=${caseId}`,{headers}),rows=(await r.json()).transactions,current=rows.find(r=>r.description==='Office cost');if(current?.amount_minor==='3001'){const base=`http://127.0.0.1:58002/api/financial/transactions/${current.key}`;const p=await page.request.post(`${base}/correction-preview?case_id=${caseId}`,{headers,data:{amount_minor:'3000',direction:'debit'}}),preview=await p.json();if(!p.ok())throw Error('Restoration preview failed');const restored=await page.request.post(`${base}/correction?case_id=${caseId}`,{headers,data:{amount_minor:'3000',direction:'debit',expected_revision:preview.document_revision,reason:'Restore synthetic source amount after interrupted cross-view acceptance.'}});if(!restored.ok())throw Error(await restored.text());report.restored_after_interruption=await restored.json();report.status='restored_after_interruption';save();}}catch(e){report.restoration_error=String(e);save();}}
  await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
