// One explicitly synthetic Workspace theory, with repeat-write protection.
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');const {chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const checkpoint=path.join(root,'data/local-runtime/pattern-theory-ui-check.json');if(fs.existsSync(checkpoint))throw Error('Pattern theory check already started; inspect checkpoint rather than repeat a write.');const fixture=JSON.parse(fs.readFileSync(path.join(root,'data/local-runtime/network-review-check.json')));const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(20000);let financialWrites=0;await page.route('**/api/financial/**',async route=>{if(!['GET','HEAD'].includes(route.request().method())){financialWrites++;await route.abort()}else await route.continue()});
 await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));await page.goto(`http://127.0.0.1:55174/cases/${fixture.case_id}/financial`);await page.getByRole('tab',{name:'Patterns',exact:true}).click();const loaded=page.waitForResponse(r=>r.url().includes('/pattern-review?'));await page.getByRole('button',{name:'Screen captured ledger',exact:true}).click();const response=await loaded,review=await response.json();if(!response.ok()||!review.hypotheses.length)throw Error('Screening failed '+JSON.stringify(review));const h=review.hypotheses.find(h=>h.kind==='repeated_equal_amount');if(!h)throw Error('Expected synthetic repeated amount absent');
 await page.getByLabel(`Theory title ${h.id}`,{exact:true}).fill('SYNTHETIC TEST — equal credits need explanation');await page.getByLabel(`Hypothesis reasoning ${h.id}`,{exact:true}).fill('Synthetic acceptance only: two equal seeded credits may have ordinary separate purposes. This is a proposed hypothesis, not a finding.');const card=page.getByLabel(`Theory title ${h.id}`,{exact:true}).locator('xpath=ancestor::article');
 fs.writeFileSync(checkpoint,JSON.stringify({status:'started',case_id:fixture.case_id,pattern_id:h.id},null,2));const saved=page.waitForResponse(r=>r.url().includes(`/api/workspace/${fixture.case_id}/entries`)&&r.request().method()==='POST');await card.getByRole('button',{name:'Save proposed theory with sources',exact:true}).click();const saveResponse=await saved,theory=await saveResponse.json();if(!saveResponse.ok())throw Error('Theory save failed '+JSON.stringify(theory));fs.writeFileSync(checkpoint,JSON.stringify({status:'saved',case_id:fixture.case_id,entry_id:theory.id,pattern_id:h.id},null,2));
 await page.getByText('Saved as proposed Workspace theory:',{exact:false}).waitFor();const headers={Authorization:`Bearer ${await page.evaluate(()=>localStorage.getItem('authToken'))}`};const retrieved=await(await page.request.get(`http://127.0.0.1:58002/api/workspace/${fixture.case_id}/entries/${theory.id}`,{headers})).json();if(retrieved.entry_type!=='theory'||retrieved.lifecycle_state!=='proposed'||retrieved.links.length!==2||!retrieved.revisions.length||!retrieved.events.length)throw Error('Persisted theory incomplete');for(const link of retrieved.links){if(link.target_type!=='evidence'||link.relationship!=='context'||link.metadata.snapshot_sha256!==review.snapshot_sha256||link.metadata.sources[0].row.proof_class!=='p3')throw Error('Source metadata differs')}
 await page.screenshot({path:'/tmp/loupe-pattern-theory.png'});if(financialWrites)throw Error('Unexpected ledger write');fs.writeFileSync(checkpoint,JSON.stringify({status:'verified',case_id:fixture.case_id,entry_id:theory.id,pattern_id:h.id,synthetic:true,source_links:retrieved.links.length,history_preserved:true,financial_writes:financialWrites},null,2));console.log(fs.readFileSync(checkpoint,'utf8'));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
