const path=require('path'),fs=require('fs');
const root=path.resolve(__dirname,'..');
const {chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{
 const fixture=JSON.parse(fs.readFileSync(path.join(root,'data/local-runtime/candidate-check.json'),'utf8'));
 const browser=await chromium.launch({headless:true});
 try {
  const page=await browser.newPage({viewport:{width:1440,height:1200}});
  page.setDefaultTimeout(20000);
  await page.goto('http://127.0.0.1:55174/login');
  await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');
  await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.waitForURL(url=>!url.pathname.includes('login'));
  await page.goto(`http://127.0.0.1:55174/cases/${fixture.case_id}/financial`);
  await page.getByRole('tab',{name:'Ledger',exact:true}).click();
  await page.getByRole('button',{name:'Open PDF readings',exact:true}).click();
  await page.getByRole('button',{name:'Open readings',exact:true}).first().click();
  await page.getByRole('button',{name:'Preview finalization',exact:true}).click();
  await page.getByText(/2 resolved rows will become/).waitFor();
  const button=page.getByRole('button',{name:'Finalize selected rows',exact:true});
  if(!await button.isDisabled())throw new Error('Finalization did not require explicit acceptance');
  await page.getByRole('checkbox',{name:/These are documentary/}).check();
  await page.getByRole('checkbox',{name:/I accept incomplete/}).check();
  await page.getByLabel('Reason for finalization').fill('Synthetic browser finalization of selected documentary rows; incomplete coverage accepted');
  await button.scrollIntoViewIfNeeded();
  await page.screenshot({path:'/tmp/loupe-neilbyrne-finalization-preview-ui.png'});
  const completed=page.waitForResponse(r=>r.url().includes('/finalize?')&&r.request().method()==='POST');
  await button.click();
  const response=await completed, result=await response.json();
  if(response.status()!==200||!result.created||result.transaction_count!==2||result.included_in_default_totals!==false)throw new Error(JSON.stringify(result));
  await page.getByText(/Finalized 2 transactions/).waitFor();
  await page.locator(`[data-row-key="${result.transactions[0].transaction_id}"]`).waitFor();
  await page.screenshot({path:'/tmp/loupe-neilbyrne-finalization-result-ui.png'});
  const request=response.request(),body=request.postDataJSON(),headers=await request.allHeaders();
  const repeated=await page.request.post(request.url(),{headers:{authorization:headers.authorization},data:body});
  const repeat=await repeated.json();
  if(repeated.status()!==200||repeat.created!==false||repeat.finalization_id!==result.finalization_id||JSON.stringify(repeat.transactions)!==JSON.stringify(result.transactions))throw new Error('HTTP retry was not stable');
  const forged=await page.request.post(request.url(),{headers:{authorization:headers.authorization},data:{...body,proof_class:'p2'}});
  if(forged.status()!==422)throw new Error('Caller could provide proof class');
  const changed=await page.request.post(request.url(),{headers:{authorization:headers.authorization},data:{...body,expected_revision:'f'.repeat(64)}});
  if(changed.status()!==409)throw new Error('Changed finalization request did not conflict');
  await page.getByRole('button',{name:'Reload finalization preview',exact:true}).click();
  await page.getByText(/Finalized 2 transactions/).waitFor();
  if(await page.getByRole('button',{name:'Finalize selected rows',exact:true}).count())throw new Error('Reload offered duplicate finalization');
  await page.getByRole('button',{name:`View source: ${result.transactions[0].ref_id}`,exact:true}).click();
  await page.getByRole('dialog').waitFor();
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('[role="dialog"] img')).some(img=>img.complete&&img.naturalWidth>0));
  await page.screenshot({path:'/tmp/loupe-neilbyrne-finalization-source-ui.png'});
  fs.writeFileSync(path.join(root,'data/local-runtime/finalization-ui-check.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify({...result,ui:'passed',http_retry:'passed',source_image:'passed'}));
 } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1});
