// Browser-only synthetic directory response; no source or identity data is changed.
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');const {chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
const variants=process.argv.includes('--variants');
(async()=>{const caseId='e9cafc92-85a7-497c-aec8-049157e823d0';const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(30000);let writes=0,fixture;
 await page.route('**/api/financial/**',async route=>{const request=route.request();if(!['GET','HEAD'].includes(request.method())){writes++;await route.abort();return}
 if(request.url().includes('/counterparty-parties?')){const response=await route.fetch();const state=await response.json();if(state.case_id!==caseId||state.readings.length!==2||!state.readings[0].party)throw Error('Unexpected synthetic source fixture');fixture=structuredClone(state);fixture.readings[0].counterparty_raw='SYNTHETIC ACME';fixture.readings[1]={...fixture.readings[1],counterparty_raw:variants?'SYNTHETIC ACNE':' synthetic  acme ',party:null,decision_transaction_id:null};fixture.limitation='Synthetic browser acceptance response only. These names are not stored or asserted by the source.';await route.fulfill({response,json:fixture});return}await route.continue()});
 await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));
 await page.goto(`http://127.0.0.1:55174/cases/${caseId}/financial`);await page.getByRole('tab',{name:'Counterparties',exact:true}).click();await page.getByRole('button',{name:'Open payment identity review',exact:true}).click();await page.getByRole('button',{name:'Find possible identity links',exact:true}).click();if(variants){if(await page.getByRole('button',{name:'Review 1 possible links to SYNTHETIC reviewed recipient',exact:true}).count())throw Error('Weak match offered without opt-in');await page.getByLabel('Include possible spelling and formatting variants',{exact:true}).check();await page.getByText('Why suggested: One character differs after formatting normalization',{exact:true}).waitFor();}await page.getByRole('button',{name:'Review 1 possible links to SYNTHETIC reviewed recipient',exact:true}).click();
 if(!await page.getByLabel(`Link payment ${fixture.readings[1].ref_id}`,{exact:true}).isChecked()||await page.getByLabel(`Link payment ${fixture.readings[0].ref_id}`,{exact:true}).isChecked())throw Error('Wrong proposal selection');if(!await page.getByRole('button',{name:'Save payment identity links',exact:true}).isDisabled()||await page.getByLabel('Payment identity reason',{exact:true}).inputValue()!=='')throw Error('Review reason was bypassed');
 await page.getByRole('region',{name:'Possible payment identity links',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`/tmp/loupe-identity-${variants?'variants':'suggestions'}.png`});if(writes)throw Error('Unexpected financial write');const report={variants,case_id:caseId,synthetic_directory_response:true,selected_unlinked_readings:1,already_linked_readings_selected:0,reason_required:true,financial_writes:0};fs.writeFileSync(path.join(root,`data/local-runtime/identity-${variants?'variants':'suggestions'}-ui-check.json`),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
