// Read-only case-context review over isolated synthetic records.
const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');const {chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const fixture=JSON.parse(fs.readFileSync(path.join(root,'data/local-runtime/financial-context-fixture.json')));const browser=await chromium.launch({headless:true});try{
const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(20000);let writes=0;await page.route('**/api/financial/**',async route=>{if(!['GET','HEAD'].includes(route.request().method())){writes++;await route.abort()}else await route.continue()});
await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));
await page.goto(`http://127.0.0.1:55174/cases/${fixture.case_id}/financial`);await page.getByRole('tab',{name:'Case context',exact:true}).click();const loaded=page.waitForResponse(r=>r.url().includes('/ledger-timeline?'));await page.getByRole('button',{name:'Load payments and case events',exact:true}).click();const response=await loaded,ledger=await response.json();if(!response.ok()||ledger.rows.length!==7)throw Error('Wrong ledger timeline '+JSON.stringify(ledger));await page.getByText('8 items match this display. Case-event amounts are context and are never added to ledger totals.',{exact:true}).waitFor();
await page.getByRole('button',{name:'Open case event SYNTHETIC — discussion of transfer',exact:true}).click();await page.waitForTimeout(300);if(!await page.getByText('SYNTHETIC — discussion of transfer',{exact:true}).count())throw Error('Event details absent');await page.screenshot({path:'/tmp/loupe-financial-case-context.png'});
await page.getByLabel('Search this timeline',{exact:true}).fill('discussion');await page.getByText('1 items match this display. Case-event amounts are context and are never added to ledger totals.',{exact:true}).waitFor();
const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download captured timeline and display filters',exact:true}).click();const output=path.join(root,'data/local-runtime/financial-context-export.json');await(await download).saveAs(output);const result=JSON.parse(fs.readFileSync(output));if(result.ledger.rows.length!==7||result.case_events.events.length!==1||result.display.search!=='discussion'||result.ledger.snapshot_sha256!==ledger.snapshot_sha256)throw Error('Capture differs');
await page.getByLabel('Timeline population',{exact:true}).selectOption('verified');await page.getByRole('button',{name:'Load payments and case events',exact:true}).click();await page.getByText('0 current ledger postings; 7 excluded readings. Case events are shown for the case and selected dates, independently of the selected ledger account.',{exact:true}).waitFor();if(writes)throw Error('Unexpected financial writes');const report={case_id:fixture.case_id,synthetic:true,postings:7,case_events:1,export_verified:true,verified_postings:0,financial_writes:writes};fs.writeFileSync(path.join(root,'data/local-runtime/financial-context-ui-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
