// Synthetic, read-only conditional transfer and account-group comparison.
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');const {chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const fixture=JSON.parse(fs.readFileSync(path.join(root,'data/local-runtime/network-review-check.json'))),browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(20000);let writes=0;await page.route('**/api/financial/**',async route=>{if(!['GET','HEAD'].includes(route.request().method())&&!route.request().url().includes('/ledger-transfer-scenario?')){writes++;await route.abort()}else await route.continue()});
 await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));await page.goto(`http://127.0.0.1:55174/cases/${fixture.case_id}/financial`);await page.getByRole('tab',{name:'Transfers',exact:true}).click();
 const loaded=page.waitForResponse(r=>r.url().includes('/ledger-transfer-candidates?'));await page.getByRole('button',{name:'Find possible transfers',exact:true}).click();const scope=await(await loaded).json();for(const pair of fixture.pairs){const i=scope.candidates.findIndex(p=>p.debit_id===pair.debit_id&&p.credit_id===pair.credit_id);await page.getByLabel(`Pair transfer ${i+1}`,{exact:true}).check()}
 await page.getByLabel('Basis for transfer pairings',{exact:true}).fill('Explicit two-hop synthetic test pairings, not real evidence.');await page.getByRole('button',{name:'Calculate paired movement scenario',exact:true}).click();await page.getByRole('region',{name:'Paired transfer scenario',exact:true}).waitFor();
 const perspective=page.getByRole('region',{name:'Account flow perspective',exact:true});for(const checkbox of await perspective.getByRole('checkbox').all())await checkbox.check();const totals=perspective.getByRole('table',{name:'Account group movement totals',exact:true});await totals.waitFor();const row=totals.getByRole('row').nth(1);const cells=await row.getByRole('cell').allTextContents();if(JSON.stringify(cells)!==JSON.stringify(['200.00 GBP','20.00 GBP','180.00 GBP','160.00 GBP','2']))throw Error('Incorrect group totals '+JSON.stringify(cells));
 await perspective.locator('summary').click();await page.getByRole('button',{name:'Open internal 1 debit',exact:true}).waitFor();await page.screenshot({path:'/tmp/loupe-account-perspective.png'});
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download account perspective and assumptions',exact:true}).click();const output=path.join(root,'data/local-runtime/account-perspective-export.json');await(await download).saveAs(output);const saved=JSON.parse(fs.readFileSync(output));if(saved.result.totals[0].internal_minor!=='16000'||saved.selected_account_ids.length!==3||saved.transfer_scenario.inputs.pairs.length!==2)throw Error('Wrong perspective capture');
 const first=scope.rows.find(r=>r.account_id===fixture.account_ids[0]);await perspective.getByLabel(`Include account ${first.account_label}`,{exact:true}).uncheck();if((await totals.getByRole('row').nth(1).getByRole('cell').allTextContents())[3]!=='60.00 GBP')throw Error('Changed selection not recalculated');if(writes)throw Error('Unexpected ledger writes');const report={case_id:fixture.case_id,synthetic:true,accounts:3,incoming_minor:'20000',outgoing_minor:'2000',net_minor:'18000',internal_minor:'16000',internal_count:2,selection_recalculated:true,export_verified:true,financial_writes:writes};fs.writeFileSync(path.join(root,'data/local-runtime/account-perspective-ui-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
