"""Local generated-PDF preparation record and temporary-table persistence check."""
import asyncio
import hashlib
import json
import os
import sys
from pathlib import Path
from uuid import uuid4
os.environ['PYTHON_DOTENV_DISABLED']='1'
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'evidence-engine'))
sys.path.insert(0,str(ROOT/'backend'))
import fitz
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from app.pipeline.extract_text import extract_text, ExtractedDocument
from app.services.evidence_document_text import upsert_evidence_document_text
from services.financial.pdf_processing_manifest import validate_pdf_processing_manifest

async def main():
    path=Path('/tmp/loupe-processing-synthetic.pdf')
    document=fitz.open();page=document.new_page()
    page.insert_textbox(fitz.Rect(40,40,540,700),
        'SYNTHETIC SOFTWARE ACCEPTANCE ONLY. This generated page checks local PDF preparation provenance. '
        'It contains no customer statement or real financial transaction. Runtime versions are recorded for this execution.',fontsize=12)
    document.save(path);document.close()
    before=hashlib.sha256(path.read_bytes()).hexdigest()
    extracted=await extract_text(str(path),path.name)
    manifest=validate_pdf_processing_manifest(extracted.metadata['processing_manifest'])
    assert extracted.metadata['ocr_page_count']==0 and manifest['content']['tesseract']['status']=='not_used'
    assert hashlib.sha256(path.read_bytes()).hexdigest()==before
    scanned_path=Path('/tmp/loupe-processing-synthetic-scanned.pdf')
    original=fitz.open(path); scanned=fitz.open()
    try:
        picture=original[0].get_pixmap(dpi=150,alpha=False)
        scanned.new_page().insert_image(original[0].rect,stream=picture.tobytes('png'))
        scanned.save(scanned_path)
    finally:original.close();scanned.close()
    scanned_result=await extract_text(str(scanned_path),scanned_path.name)
    scanned_manifest=validate_pdf_processing_manifest(scanned_result.metadata['processing_manifest'])
    assert scanned_result.metadata['ocr_page_count']==1
    assert scanned_manifest['content']['tesseract']['status']=='reported'
    assert 'SYNTHETIC' in scanned_result.text
    Path('/tmp/loupe-processing-ocr-runtime-record.json').write_text(json.dumps(scanned_manifest,indent=2))
    engine=create_async_engine('postgresql+asyncpg://loupe_local:loupe_local_dev@127.0.0.1:55434/loupe_local')
    try:
        async with engine.begin() as connection:
            # PostgreSQL LIKE does not copy foreign keys. The temporary table
            # shadows the public name only on this connection and drops on commit.
            await connection.execute(text('CREATE TEMP TABLE evidence_document_texts (LIKE public.evidence_document_texts INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES) ON COMMIT DROP'))
            file_id,job=uuid4(),uuid4()
            async with AsyncSession(bind=connection) as db:
                await upsert_evidence_document_text(db,evidence_file_id=file_id,engine_job_id=job,doc=extracted,commit=False)
                stored=(await db.execute(text('SELECT processing_manifest FROM pg_temp.evidence_document_texts WHERE evidence_file_id=:id'),dict(id=file_id))).scalar_one()
                assert validate_pdf_processing_manifest(stored)==manifest
                await upsert_evidence_document_text(db,evidence_file_id=file_id,engine_job_id=uuid4(),doc=scanned_result,commit=False)
                stored=(await db.execute(text('SELECT processing_manifest FROM pg_temp.evidence_document_texts WHERE evidence_file_id=:id'),dict(id=file_id))).scalar_one()
                assert validate_pdf_processing_manifest(stored)==scanned_manifest
                await upsert_evidence_document_text(db,evidence_file_id=file_id,engine_job_id=job,
                    doc=ExtractedDocument(text='Synthetic replacement without recorded provenance',metadata={'file_type':'text'}),commit=False)
                assert (await db.execute(text('SELECT processing_manifest IS NULL FROM pg_temp.evidence_document_texts WHERE evidence_file_id=:id'),dict(id=file_id))).scalar_one()
        Path('/tmp/loupe-processing-runtime-record.json').write_text(json.dumps(manifest,indent=2))
    finally:await engine.dispose()
    print('PASS: generated native and scanned PDFs; actual local runtime and Tesseract version records; backend schema/digest validation; PostgreSQL engine upsert preserves metadata and clears it on unrecorded replacement; temporary table removed; original generated bytes unchanged; no existing case writes or external provider.')

if __name__=='__main__':asyncio.run(main())
