// Read-only browser acceptance: opens fallback and stored history; never calls a model.
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const {chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const browser=await chromium.launch({headless:true});let page;try{
page=await browser.newPage({viewport:{width:1440,height:1100}});let writes=0;
await page.route('**/api/financial/**',async route=>{if(!['GET','HEAD'].includes(route.request().method())){writes++;return route.abort()}return route.continue()});
await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));
await page.goto('http://127.0.0.1:55174/cases/3db2ae11-da7f-405a-a087-b465bdc9f12d/financial');await page.getByRole('button',{name:'Open PDF readings',exact:true}).click();await page.getByRole('button',{name:'Choose PDF rows',exact:true}).click();await page.getByRole('button',{name:/ · page 4$/}).click();
await page.getByRole('button',{name:'Model-assisted row proposals',exact:true}).click();const panel=page.getByRole('region',{name:'Model-assisted PDF nominations',exact:true});await panel.getByText('Saved attempts for this source table',{exact:true}).click();await panel.getByRole('button',{name:'Next attempts',exact:true}).waitFor();await panel.scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-model-nomination-panel.png'});if(writes)throw Error('Unexpected financial write');console.log(JSON.stringify({financial_writes:0,provider_requests:0,real_source_page:4,optional_panel_and_history:true}));
}catch(error){if(page)fs.writeFileSync('/tmp/loupe-model-ui-failure.txt',await page.locator('body').innerText());throw error}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
