// Save a party assumption only in the existing synthetic three-account test case.
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),{chromium}=require(path.join(root,'frontend_v2/node_modules/playwright'));
(async()=>{const output=path.join(root,'data/local-runtime/account-parties-browser-check.json');let report=fs.existsSync(output)?JSON.parse(fs.readFileSync(output)):{};if(report.status==='verified'&&!process.argv.includes('--read-only'))throw Error('Completed party-link journey; do not rerun writes');const fixture=JSON.parse(fs.readFileSync(path.join(root,'data/local-runtime/network-review-check.json')));const browser=await chromium.launch({headless:true});try{
const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(20000);await page.goto('http://127.0.0.1:55174/login');await page.getByPlaceholder('Enter your username').fill('loupe-local@example.com');await page.getByPlaceholder('Enter your password').fill('Loupe-local-test-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(u=>!u.pathname.includes('login'));
const load=async()=>{await page.goto(`http://127.0.0.1:55174/cases/${fixture.case_id}/financial`);await page.getByRole('tab',{name:'Transfers',exact:true}).click();const pending=page.waitForResponse(r=>r.url().includes('/ledger-transfer-candidates?'));await page.getByRole('button',{name:'Find possible transfers',exact:true}).click();return await(await pending).json()};const scope=await load();
const open=async()=>{await page.getByRole('button',{name:'Review account-to-party links',exact:true}).click();await page.getByRole('button',{name:'Reload account links',exact:true}).waitFor()};await open();
if(!report.saved){for(const id of fixture.account_ids)await page.getByLabel(`Select account ${id}`,{exact:true}).check();await page.getByLabel('New account party name',{exact:true}).fill('Synthetic account group');await page.getByLabel('Account party link reason',{exact:true}).fill('Synthetic UI acceptance: group all three generated fixture accounts for the perspective; not an assertion about real ownership.');const pending=page.waitForResponse(r=>r.url().includes('/account-parties?')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save account links',exact:true}).click();const response=await pending,data=await response.json();report={case_id:fixture.case_id,saved:data,status:'saved'};fs.writeFileSync(output,JSON.stringify(report,null,2));if(!response.ok()||!data.applied)throw Error(JSON.stringify(data));}
await load();await open();await page.getByRole('button',{name:'Use Synthetic account group in this perspective',exact:true}).click();
const perspective=page.getByRole('region',{name:'Account flow perspective',exact:true});for(const a of fixture.account_ids){const row=scope.rows.find(r=>r.account_id===a);if(!await perspective.getByLabel(`Include account ${row.account_label}`,{exact:true}).isChecked())throw Error('Saved party did not select account');}
const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download account perspective and assumptions',exact:true}).click();const destination=path.join(root,'data/local-runtime/account-party-perspective.json');await(await download).saveAs(destination);const captured=JSON.parse(fs.readFileSync(destination));if(captured.selected_account_ids.length!==3||captured.account_party_decisions.history.length!==3)throw Error('Decision capture missing');await perspective.scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/loupe-account-party-links.png'});await page.getByRole('tab',{name:'Ledger',exact:true}).click();const ledgerDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download ledger snapshot',exact:true}).click();await(await ledgerDownload).saveAs(path.join(root,'data/local-runtime/account-party-ledger-export.zip'));report.status='verified';report.selection_reloaded=true;report.download_includes_decisions=true;report.accounts=3;fs.writeFileSync(output,JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,case_id:report.case_id,accounts:3,history:captured.account_party_decisions.history.length}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
